
events {}
http {
    # -------------------------------------------------------------
    # BLOQUE CATCH-ALL (CONTROL DE ERRORES MEC)
    # Atrapa peticiones a dominios de apps que ya han sido apagadas
    # para que NGINX no muestre por error la web de otra app.
    # -------------------------------------------------------------
    server {
        listen 80 default_server;
        server_name _;
        
        default_type text/html;
        return 404 "<!DOCTYPE html><html><head><meta charset='utf-8'><title>MEC Edge Error</title></head><body style='font-family:sans-serif; text-align:center; padding-top:50px; color:#333;'><h2>❌ ERROR 404: SERVICIO EDGE APAGADO</h2><p>La aplicación solicitada ha sido detenida o el dominio no existe en el catálogo actual.</p></body></html>";
    }
}
