version: "3.8"

services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail-edge
    volumes:
      # Montamos la ruta donde Docker guarda los logs nativos
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-edge.yaml:/etc/promtail/config.yml:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-edge
    expose:
      - "8080/tcp"
    ports:
      - "8080:8080/tcp"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
  beyla:
    image: grafana/beyla:latest
    container_name: beyla-dn-gw
    pid: "host"          # Obligatorio para ver procesos del host
    network_mode: "host" # Obligatorio para igualar a tu eUPF
    privileged: true     # Necesario para inyectar sondas eBPF
    volumes:
      # Montamos el sistema de archivos de depuración del kernel
      - /sys/kernel/debug:/sys/kernel/debug:ro 
    environment:
      # 1. ¿A quién miramos? (El binario dentro de ghcr.io/edgecomllc/eupf se llama eupf)
      - BEYLA_EXECUTABLE_NAME=dn-gw 
      
      # 2. ¿A dónde enviamos las trazas? (Tu Nodo Central donde está Jaeger)
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://192.168.0.102:4317
      
      # 3. Para depurar: muestra las trazas capturadas en el log del propio contenedor
      - BEYLA_PRINT_TRACE=true 
    restart: unless-stopped
