from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Addresses(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, host=None, port=None):  # noqa: E501
        """Addresses - a model defined in OpenAPI

        :param host: The host of this Addresses.  # noqa: E501
        :type host: str
        :param port: The port of this Addresses.  # noqa: E501
        :type port: int
        """
        self.openapi_types = {
            'host': str,
            'port': int
        }

        self.attribute_map = {
            'host': 'host',
            'port': 'port'
        }

        self._host = host
        self._port = port

    @classmethod
    def from_dict(cls, dikt) -> 'Addresses':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Addresses of this Addresses.  # noqa: E501
        :rtype: Addresses
        """
        return util.deserialize_model(dikt, cls)

    @property
    def host(self) -> str:
        """Gets the host of this Addresses.

        Host portion of the address.  # noqa: E501

        :return: The host of this Addresses.
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host: str):
        """Sets the host of this Addresses.

        Host portion of the address.  # noqa: E501

        :param host: The host of this Addresses.
        :type host: str
        """
        if host is None:
            raise ValueError("Invalid value for `host`, must not be `None`")  # noqa: E501

        self._host = host

    @property
    def port(self) -> int:
        """Gets the port of this Addresses.

        Port portion of the address.  # noqa: E501

        :return: The port of this Addresses.
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port: int):
        """Sets the port of this Addresses.

        Port portion of the address.  # noqa: E501

        :param port: The port of this Addresses.
        :type port: int
        """
        if port is None:
            raise ValueError("Invalid value for `port`, must not be `None`")  # noqa: E501

        self._port = port
