from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AppTerminationConfirmation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, operation_action=None):  # noqa: E501
        """AppTerminationConfirmation - a model defined in OpenAPI

        :param operation_action: The operation_action of this AppTerminationConfirmation.  # noqa: E501
        :type operation_action: str
        """
        self.openapi_types = {
            'operation_action': str
        }

        self.attribute_map = {
            'operation_action': 'operationAction'
        }

        self._operation_action = operation_action

    @classmethod
    def from_dict(cls, dikt) -> 'AppTerminationConfirmation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AppTerminationConfirmation of this AppTerminationConfirmation.  # noqa: E501
        :rtype: AppTerminationConfirmation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def operation_action(self) -> str:
        """Gets the operation_action of this AppTerminationConfirmation.

        Operation that is being performed on the MEC application instance: STOPPPING TERMINATING The value shall match that sent in the corresponding AppTerminationNotification.  # noqa: E501

        :return: The operation_action of this AppTerminationConfirmation.
        :rtype: str
        """
        return self._operation_action

    @operation_action.setter
    def operation_action(self, operation_action: str):
        """Sets the operation_action of this AppTerminationConfirmation.

        Operation that is being performed on the MEC application instance: STOPPPING TERMINATING The value shall match that sent in the corresponding AppTerminationNotification.  # noqa: E501

        :param operation_action: The operation_action of this AppTerminationConfirmation.
        :type operation_action: str
        """
        allowed_values = ["SEE_DESCRIPTION"]  # noqa: E501
        if operation_action not in allowed_values:
            raise ValueError(
                "Invalid value for `operation_action` ({0}), must be one of {1}"
                .format(operation_action, allowed_values)
            )

        self._operation_action = operation_action
