from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.dns_rule import DnsRule
from openapi_server import util

from openapi_server.models.dns_rule import DnsRule  # noqa: E501

class ApplicationsDnsrulesGETAppinstanceidDnsruleid200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, dns_rule=None):  # noqa: E501
        """ApplicationsDnsrulesGETAppinstanceidDnsruleid200Response - a model defined in OpenAPI

        :param dns_rule: The dns_rule of this ApplicationsDnsrulesGETAppinstanceidDnsruleid200Response.  # noqa: E501
        :type dns_rule: DnsRule
        """
        self.openapi_types = {
            'dns_rule': DnsRule
        }

        self.attribute_map = {
            'dns_rule': 'DnsRule'
        }

        self._dns_rule = dns_rule

    @classmethod
    def from_dict(cls, dikt) -> 'ApplicationsDnsrulesGETAppinstanceidDnsruleid200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApplicationsDnsrulesGETAppinstanceidDnsruleid_200_response of this ApplicationsDnsrulesGETAppinstanceidDnsruleid200Response.  # noqa: E501
        :rtype: ApplicationsDnsrulesGETAppinstanceidDnsruleid200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dns_rule(self) -> DnsRule:
        """Gets the dns_rule of this ApplicationsDnsrulesGETAppinstanceidDnsruleid200Response.


        :return: The dns_rule of this ApplicationsDnsrulesGETAppinstanceidDnsruleid200Response.
        :rtype: DnsRule
        """
        return self._dns_rule

    @dns_rule.setter
    def dns_rule(self, dns_rule: DnsRule):
        """Sets the dns_rule of this ApplicationsDnsrulesGETAppinstanceidDnsruleid200Response.


        :param dns_rule: The dns_rule of this ApplicationsDnsrulesGETAppinstanceidDnsruleid200Response.
        :type dns_rule: DnsRule
        """

        self._dns_rule = dns_rule
