from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.app_termination_notification_subscription import AppTerminationNotificationSubscription
from openapi_server import util

from openapi_server.models.app_termination_notification_subscription import AppTerminationNotificationSubscription  # noqa: E501

class ApplicationsSubscriptionsPOSTAppinstanceidRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, app_termination_notification_subscription=None):  # noqa: E501
        """ApplicationsSubscriptionsPOSTAppinstanceidRequest - a model defined in OpenAPI

        :param app_termination_notification_subscription: The app_termination_notification_subscription of this ApplicationsSubscriptionsPOSTAppinstanceidRequest.  # noqa: E501
        :type app_termination_notification_subscription: AppTerminationNotificationSubscription
        """
        self.openapi_types = {
            'app_termination_notification_subscription': AppTerminationNotificationSubscription
        }

        self.attribute_map = {
            'app_termination_notification_subscription': 'AppTerminationNotificationSubscription'
        }

        self._app_termination_notification_subscription = app_termination_notification_subscription

    @classmethod
    def from_dict(cls, dikt) -> 'ApplicationsSubscriptionsPOSTAppinstanceidRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApplicationsSubscriptionsPOSTAppinstanceid_request of this ApplicationsSubscriptionsPOSTAppinstanceidRequest.  # noqa: E501
        :rtype: ApplicationsSubscriptionsPOSTAppinstanceidRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def app_termination_notification_subscription(self) -> AppTerminationNotificationSubscription:
        """Gets the app_termination_notification_subscription of this ApplicationsSubscriptionsPOSTAppinstanceidRequest.


        :return: The app_termination_notification_subscription of this ApplicationsSubscriptionsPOSTAppinstanceidRequest.
        :rtype: AppTerminationNotificationSubscription
        """
        return self._app_termination_notification_subscription

    @app_termination_notification_subscription.setter
    def app_termination_notification_subscription(self, app_termination_notification_subscription: AppTerminationNotificationSubscription):
        """Sets the app_termination_notification_subscription of this ApplicationsSubscriptionsPOSTAppinstanceidRequest.


        :param app_termination_notification_subscription: The app_termination_notification_subscription of this ApplicationsSubscriptionsPOSTAppinstanceidRequest.
        :type app_termination_notification_subscription: AppTerminationNotificationSubscription
        """

        self._app_termination_notification_subscription = app_termination_notification_subscription
