from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.app_termination_confirmation import AppTerminationConfirmation
from openapi_server import util

from openapi_server.models.app_termination_confirmation import AppTerminationConfirmation  # noqa: E501

class ApplicationsConfirmterminationPOSTAppinstanceidRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, app_termination_confirmation=None):  # noqa: E501
        """ApplicationsConfirmterminationPOSTAppinstanceidRequest - a model defined in OpenAPI

        :param app_termination_confirmation: The app_termination_confirmation of this ApplicationsConfirmterminationPOSTAppinstanceidRequest.  # noqa: E501
        :type app_termination_confirmation: AppTerminationConfirmation
        """
        self.openapi_types = {
            'app_termination_confirmation': AppTerminationConfirmation
        }

        self.attribute_map = {
            'app_termination_confirmation': 'AppTerminationConfirmation'
        }

        self._app_termination_confirmation = app_termination_confirmation

    @classmethod
    def from_dict(cls, dikt) -> 'ApplicationsConfirmterminationPOSTAppinstanceidRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApplicationsConfirmterminationPOSTAppinstanceid_request of this ApplicationsConfirmterminationPOSTAppinstanceidRequest.  # noqa: E501
        :rtype: ApplicationsConfirmterminationPOSTAppinstanceidRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def app_termination_confirmation(self) -> AppTerminationConfirmation:
        """Gets the app_termination_confirmation of this ApplicationsConfirmterminationPOSTAppinstanceidRequest.


        :return: The app_termination_confirmation of this ApplicationsConfirmterminationPOSTAppinstanceidRequest.
        :rtype: AppTerminationConfirmation
        """
        return self._app_termination_confirmation

    @app_termination_confirmation.setter
    def app_termination_confirmation(self, app_termination_confirmation: AppTerminationConfirmation):
        """Sets the app_termination_confirmation of this ApplicationsConfirmterminationPOSTAppinstanceidRequest.


        :param app_termination_confirmation: The app_termination_confirmation of this ApplicationsConfirmterminationPOSTAppinstanceidRequest.
        :type app_termination_confirmation: AppTerminationConfirmation
        """

        self._app_termination_confirmation = app_termination_confirmation
