from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.traffic_rule import TrafficRule
from openapi_server import util

from openapi_server.models.traffic_rule import TrafficRule  # noqa: E501

class ApplicationsTrafficrulesGETAppinstanceidTrafficruleid200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, traffic_rule=None):  # noqa: E501
        """ApplicationsTrafficrulesGETAppinstanceidTrafficruleid200Response - a model defined in OpenAPI

        :param traffic_rule: The traffic_rule of this ApplicationsTrafficrulesGETAppinstanceidTrafficruleid200Response.  # noqa: E501
        :type traffic_rule: TrafficRule
        """
        self.openapi_types = {
            'traffic_rule': TrafficRule
        }

        self.attribute_map = {
            'traffic_rule': 'TrafficRule'
        }

        self._traffic_rule = traffic_rule

    @classmethod
    def from_dict(cls, dikt) -> 'ApplicationsTrafficrulesGETAppinstanceidTrafficruleid200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApplicationsTrafficrulesGETAppinstanceidTrafficruleid_200_response of this ApplicationsTrafficrulesGETAppinstanceidTrafficruleid200Response.  # noqa: E501
        :rtype: ApplicationsTrafficrulesGETAppinstanceidTrafficruleid200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def traffic_rule(self) -> TrafficRule:
        """Gets the traffic_rule of this ApplicationsTrafficrulesGETAppinstanceidTrafficruleid200Response.


        :return: The traffic_rule of this ApplicationsTrafficrulesGETAppinstanceidTrafficruleid200Response.
        :rtype: TrafficRule
        """
        return self._traffic_rule

    @traffic_rule.setter
    def traffic_rule(self, traffic_rule: TrafficRule):
        """Sets the traffic_rule of this ApplicationsTrafficrulesGETAppinstanceidTrafficruleid200Response.


        :param traffic_rule: The traffic_rule of this ApplicationsTrafficrulesGETAppinstanceidTrafficruleid200Response.
        :type traffic_rule: TrafficRule
        """

        self._traffic_rule = traffic_rule
