from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DnsRule(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, dns_rule_id=None, domain_name=None, ip_address_type=None, ip_address=None, ttl=None, state=None):  # noqa: E501
        """DnsRule - a model defined in OpenAPI

        :param dns_rule_id: The dns_rule_id of this DnsRule.  # noqa: E501
        :type dns_rule_id: str
        :param domain_name: The domain_name of this DnsRule.  # noqa: E501
        :type domain_name: str
        :param ip_address_type: The ip_address_type of this DnsRule.  # noqa: E501
        :type ip_address_type: str
        :param ip_address: The ip_address of this DnsRule.  # noqa: E501
        :type ip_address: str
        :param ttl: The ttl of this DnsRule.  # noqa: E501
        :type ttl: int
        :param state: The state of this DnsRule.  # noqa: E501
        :type state: str
        """
        self.openapi_types = {
            'dns_rule_id': str,
            'domain_name': str,
            'ip_address_type': str,
            'ip_address': str,
            'ttl': int,
            'state': str
        }

        self.attribute_map = {
            'dns_rule_id': 'dnsRuleId',
            'domain_name': 'domainName',
            'ip_address_type': 'ipAddressType',
            'ip_address': 'ipAddress',
            'ttl': 'ttl',
            'state': 'state'
        }

        self._dns_rule_id = dns_rule_id
        self._domain_name = domain_name
        self._ip_address_type = ip_address_type
        self._ip_address = ip_address
        self._ttl = ttl
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'DnsRule':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DnsRule of this DnsRule.  # noqa: E501
        :rtype: DnsRule
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dns_rule_id(self) -> str:
        """Gets the dns_rule_id of this DnsRule.

        Identifies the DNS Rule.  # noqa: E501

        :return: The dns_rule_id of this DnsRule.
        :rtype: str
        """
        return self._dns_rule_id

    @dns_rule_id.setter
    def dns_rule_id(self, dns_rule_id: str):
        """Sets the dns_rule_id of this DnsRule.

        Identifies the DNS Rule.  # noqa: E501

        :param dns_rule_id: The dns_rule_id of this DnsRule.
        :type dns_rule_id: str
        """
        if dns_rule_id is None:
            raise ValueError("Invalid value for `dns_rule_id`, must not be `None`")  # noqa: E501

        self._dns_rule_id = dns_rule_id

    @property
    def domain_name(self) -> str:
        """Gets the domain_name of this DnsRule.

        FQDN resolved by the DNS rule.  # noqa: E501

        :return: The domain_name of this DnsRule.
        :rtype: str
        """
        return self._domain_name

    @domain_name.setter
    def domain_name(self, domain_name: str):
        """Sets the domain_name of this DnsRule.

        FQDN resolved by the DNS rule.  # noqa: E501

        :param domain_name: The domain_name of this DnsRule.
        :type domain_name: str
        """
        if domain_name is None:
            raise ValueError("Invalid value for `domain_name`, must not be `None`")  # noqa: E501

        self._domain_name = domain_name

    @property
    def ip_address_type(self) -> str:
        """Gets the ip_address_type of this DnsRule.

        Specify the IP address type, value: IP_V6, IP_V4.  # noqa: E501

        :return: The ip_address_type of this DnsRule.
        :rtype: str
        """
        return self._ip_address_type

    @ip_address_type.setter
    def ip_address_type(self, ip_address_type: str):
        """Sets the ip_address_type of this DnsRule.

        Specify the IP address type, value: IP_V6, IP_V4.  # noqa: E501

        :param ip_address_type: The ip_address_type of this DnsRule.
        :type ip_address_type: str
        """
        allowed_values = ["SEE_DESCRIPTION"]  # noqa: E501
        if ip_address_type not in allowed_values:
            raise ValueError(
                "Invalid value for `ip_address_type` ({0}), must be one of {1}"
                .format(ip_address_type, allowed_values)
            )

        self._ip_address_type = ip_address_type

    @property
    def ip_address(self) -> str:
        """Gets the ip_address of this DnsRule.

        IP address associated with the FQDN resolved by the DNS rule.  # noqa: E501

        :return: The ip_address of this DnsRule.
        :rtype: str
        """
        return self._ip_address

    @ip_address.setter
    def ip_address(self, ip_address: str):
        """Sets the ip_address of this DnsRule.

        IP address associated with the FQDN resolved by the DNS rule.  # noqa: E501

        :param ip_address: The ip_address of this DnsRule.
        :type ip_address: str
        """
        if ip_address is None:
            raise ValueError("Invalid value for `ip_address`, must not be `None`")  # noqa: E501

        self._ip_address = ip_address

    @property
    def ttl(self) -> int:
        """Gets the ttl of this DnsRule.

        Time to live value, in seconds.  # noqa: E501

        :return: The ttl of this DnsRule.
        :rtype: int
        """
        return self._ttl

    @ttl.setter
    def ttl(self, ttl: int):
        """Sets the ttl of this DnsRule.

        Time to live value, in seconds.  # noqa: E501

        :param ttl: The ttl of this DnsRule.
        :type ttl: int
        """

        self._ttl = ttl

    @property
    def state(self) -> str:
        """Gets the state of this DnsRule.

        Contains the DNS rule state: ACTIVE, INACTIVE. This attribute may be updated using HTTP PUT method.  # noqa: E501

        :return: The state of this DnsRule.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this DnsRule.

        Contains the DNS rule state: ACTIVE, INACTIVE. This attribute may be updated using HTTP PUT method.  # noqa: E501

        :param state: The state of this DnsRule.
        :type state: str
        """
        allowed_values = ["SEE_DESCRIPTION"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"
                .format(state, allowed_values)
            )

        self._state = state
