from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.addresses import Addresses
from openapi_server import util

from openapi_server.models.addresses import Addresses  # noqa: E501

class EndPointInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uris=None, fqdn=None, addresses=None, alternative=None):  # noqa: E501
        """EndPointInfo - a model defined in OpenAPI

        :param uris: The uris of this EndPointInfo.  # noqa: E501
        :type uris: List[str]
        :param fqdn: The fqdn of this EndPointInfo.  # noqa: E501
        :type fqdn: List[str]
        :param addresses: The addresses of this EndPointInfo.  # noqa: E501
        :type addresses: List[Addresses]
        :param alternative: The alternative of this EndPointInfo.  # noqa: E501
        :type alternative: object
        """
        self.openapi_types = {
            'uris': List[str],
            'fqdn': List[str],
            'addresses': List[Addresses],
            'alternative': object
        }

        self.attribute_map = {
            'uris': 'uris',
            'fqdn': 'fqdn',
            'addresses': 'addresses',
            'alternative': 'alternative'
        }

        self._uris = uris
        self._fqdn = fqdn
        self._addresses = addresses
        self._alternative = alternative

    @classmethod
    def from_dict(cls, dikt) -> 'EndPointInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EndPointInfo of this EndPointInfo.  # noqa: E501
        :rtype: EndPointInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uris(self) -> List[str]:
        """Gets the uris of this EndPointInfo.

        Entry point information of the service as string, formatted according to URI syntax (see IETF RFC 3986 [8]). Shall be used for REST APIs. See note.  # noqa: E501

        :return: The uris of this EndPointInfo.
        :rtype: List[str]
        """
        return self._uris

    @uris.setter
    def uris(self, uris: List[str]):
        """Sets the uris of this EndPointInfo.

        Entry point information of the service as string, formatted according to URI syntax (see IETF RFC 3986 [8]). Shall be used for REST APIs. See note.  # noqa: E501

        :param uris: The uris of this EndPointInfo.
        :type uris: List[str]
        """
        if uris is not None and len(uris) < 0:
            raise ValueError("Invalid value for `uris`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._uris = uris

    @property
    def fqdn(self) -> List[str]:
        """Gets the fqdn of this EndPointInfo.

        Fully Qualified Domain Name of the service. See note.  # noqa: E501

        :return: The fqdn of this EndPointInfo.
        :rtype: List[str]
        """
        return self._fqdn

    @fqdn.setter
    def fqdn(self, fqdn: List[str]):
        """Sets the fqdn of this EndPointInfo.

        Fully Qualified Domain Name of the service. See note.  # noqa: E501

        :param fqdn: The fqdn of this EndPointInfo.
        :type fqdn: List[str]
        """
        if fqdn is not None and len(fqdn) < 0:
            raise ValueError("Invalid value for `fqdn`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._fqdn = fqdn

    @property
    def addresses(self) -> List[Addresses]:
        """Gets the addresses of this EndPointInfo.


        :return: The addresses of this EndPointInfo.
        :rtype: List[Addresses]
        """
        return self._addresses

    @addresses.setter
    def addresses(self, addresses: List[Addresses]):
        """Sets the addresses of this EndPointInfo.


        :param addresses: The addresses of this EndPointInfo.
        :type addresses: List[Addresses]
        """

        self._addresses = addresses

    @property
    def alternative(self) -> object:
        """Gets the alternative of this EndPointInfo.

        Entry point information of the service in a format defined by an implementation, or in an external specification. See note.  # noqa: E501

        :return: The alternative of this EndPointInfo.
        :rtype: object
        """
        return self._alternative

    @alternative.setter
    def alternative(self, alternative: object):
        """Sets the alternative of this EndPointInfo.

        Entry point information of the service in a format defined by an implementation, or in an external specification. See note.  # noqa: E501

        :param alternative: The alternative of this EndPointInfo.
        :type alternative: object
        """

        self._alternative = alternative
