from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.link_type import LinkType
from openapi_server import util

from openapi_server.models.link_type import LinkType  # noqa: E501

class Links1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _self=None):  # noqa: E501
        """Links1 - a model defined in OpenAPI

        :param _self: The _self of this Links1.  # noqa: E501
        :type _self: LinkType
        """
        self.openapi_types = {
            '_self': LinkType
        }

        self.attribute_map = {
            '_self': 'self'
        }

        self.__self = _self

    @classmethod
    def from_dict(cls, dikt) -> 'Links1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _links1 of this Links1.  # noqa: E501
        :rtype: Links1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _self(self) -> LinkType:
        """Gets the _self of this Links1.

        Self-referring URI.  # noqa: E501

        :return: The _self of this Links1.
        :rtype: LinkType
        """
        return self.__self

    @_self.setter
    def _self(self, _self: LinkType):
        """Sets the _self of this Links1.

        Self-referring URI.  # noqa: E501

        :param _self: The _self of this Links1.
        :type _self: LinkType
        """
        if _self is None:
            raise ValueError("Invalid value for `_self`, must not be `None`")  # noqa: E501

        self.__self = _self
