from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.link_type import LinkType
from openapi_server import util

from openapi_server.models.link_type import LinkType  # noqa: E501

class Links2(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, subscription=None, confirm_termination=None):  # noqa: E501
        """Links2 - a model defined in OpenAPI

        :param subscription: The subscription of this Links2.  # noqa: E501
        :type subscription: LinkType
        :param confirm_termination: The confirm_termination of this Links2.  # noqa: E501
        :type confirm_termination: LinkType
        """
        self.openapi_types = {
            'subscription': LinkType,
            'confirm_termination': LinkType
        }

        self.attribute_map = {
            'subscription': 'subscription',
            'confirm_termination': 'confirmTermination'
        }

        self._subscription = subscription
        self._confirm_termination = confirm_termination

    @classmethod
    def from_dict(cls, dikt) -> 'Links2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _links2 of this Links2.  # noqa: E501
        :rtype: Links2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subscription(self) -> LinkType:
        """Gets the subscription of this Links2.

        A link to the related subscription.  # noqa: E501

        :return: The subscription of this Links2.
        :rtype: LinkType
        """
        return self._subscription

    @subscription.setter
    def subscription(self, subscription: LinkType):
        """Sets the subscription of this Links2.

        A link to the related subscription.  # noqa: E501

        :param subscription: The subscription of this Links2.
        :type subscription: LinkType
        """
        if subscription is None:
            raise ValueError("Invalid value for `subscription`, must not be `None`")  # noqa: E501

        self._subscription = subscription

    @property
    def confirm_termination(self) -> LinkType:
        """Gets the confirm_termination of this Links2.

        Link to the task resource where to confirm termination/stop in case the application is ready to be terminated, or to be considered stopped by the MEC Platform, before expiry of the timeout.  # noqa: E501

        :return: The confirm_termination of this Links2.
        :rtype: LinkType
        """
        return self._confirm_termination

    @confirm_termination.setter
    def confirm_termination(self, confirm_termination: LinkType):
        """Sets the confirm_termination of this Links2.

        Link to the task resource where to confirm termination/stop in case the application is ready to be terminated, or to be considered stopped by the MEC Platform, before expiry of the timeout.  # noqa: E501

        :param confirm_termination: The confirm_termination of this Links2.
        :type confirm_termination: LinkType
        """

        self._confirm_termination = confirm_termination
