from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.app_termination_notification_subscription import AppTerminationNotificationSubscription
from openapi_server import util

from openapi_server.models.app_termination_notification_subscription import AppTerminationNotificationSubscription  # noqa: E501

class NotificationPOST637029Request(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, subscription_notification=None):  # noqa: E501
        """NotificationPOST637029Request - a model defined in OpenAPI

        :param subscription_notification: The subscription_notification of this NotificationPOST637029Request.  # noqa: E501
        :type subscription_notification: AppTerminationNotificationSubscription
        """
        self.openapi_types = {
            'subscription_notification': AppTerminationNotificationSubscription
        }

        self.attribute_map = {
            'subscription_notification': 'subscriptionNotification'
        }

        self._subscription_notification = subscription_notification

    @classmethod
    def from_dict(cls, dikt) -> 'NotificationPOST637029Request':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The notificationPOST637029_request of this NotificationPOST637029Request.  # noqa: E501
        :rtype: NotificationPOST637029Request
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subscription_notification(self) -> AppTerminationNotificationSubscription:
        """Gets the subscription_notification of this NotificationPOST637029Request.


        :return: The subscription_notification of this NotificationPOST637029Request.
        :rtype: AppTerminationNotificationSubscription
        """
        return self._subscription_notification

    @subscription_notification.setter
    def subscription_notification(self, subscription_notification: AppTerminationNotificationSubscription):
        """Sets the subscription_notification of this NotificationPOST637029Request.


        :param subscription_notification: The subscription_notification of this NotificationPOST637029Request.
        :type subscription_notification: AppTerminationNotificationSubscription
        """

        self._subscription_notification = subscription_notification
