from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class NtpServers(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ntp_server_addr_type=None, ntp_server_addr=None, min_polling_interval=None, max_polling_interval=None, local_priority=None, authentication_option=None, authentication_key_num=None):  # noqa: E501
        """NtpServers - a model defined in OpenAPI

        :param ntp_server_addr_type: The ntp_server_addr_type of this NtpServers.  # noqa: E501
        :type ntp_server_addr_type: List[str]
        :param ntp_server_addr: The ntp_server_addr of this NtpServers.  # noqa: E501
        :type ntp_server_addr: List[str]
        :param min_polling_interval: The min_polling_interval of this NtpServers.  # noqa: E501
        :type min_polling_interval: List[int]
        :param max_polling_interval: The max_polling_interval of this NtpServers.  # noqa: E501
        :type max_polling_interval: List[int]
        :param local_priority: The local_priority of this NtpServers.  # noqa: E501
        :type local_priority: List[int]
        :param authentication_option: The authentication_option of this NtpServers.  # noqa: E501
        :type authentication_option: List[str]
        :param authentication_key_num: The authentication_key_num of this NtpServers.  # noqa: E501
        :type authentication_key_num: List[int]
        """
        self.openapi_types = {
            'ntp_server_addr_type': List[str],
            'ntp_server_addr': List[str],
            'min_polling_interval': List[int],
            'max_polling_interval': List[int],
            'local_priority': List[int],
            'authentication_option': List[str],
            'authentication_key_num': List[int]
        }

        self.attribute_map = {
            'ntp_server_addr_type': 'ntpServerAddrType',
            'ntp_server_addr': 'ntpServerAddr',
            'min_polling_interval': 'minPollingInterval',
            'max_polling_interval': 'maxPollingInterval',
            'local_priority': 'localPriority',
            'authentication_option': 'authenticationOption',
            'authentication_key_num': 'authenticationKeyNum'
        }

        self._ntp_server_addr_type = ntp_server_addr_type
        self._ntp_server_addr = ntp_server_addr
        self._min_polling_interval = min_polling_interval
        self._max_polling_interval = max_polling_interval
        self._local_priority = local_priority
        self._authentication_option = authentication_option
        self._authentication_key_num = authentication_key_num

    @classmethod
    def from_dict(cls, dikt) -> 'NtpServers':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NtpServers of this NtpServers.  # noqa: E501
        :rtype: NtpServers
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ntp_server_addr_type(self) -> List[str]:
        """Gets the ntp_server_addr_type of this NtpServers.

        1  # noqa: E501

        :return: The ntp_server_addr_type of this NtpServers.
        :rtype: List[str]
        """
        return self._ntp_server_addr_type

    @ntp_server_addr_type.setter
    def ntp_server_addr_type(self, ntp_server_addr_type: List[str]):
        """Sets the ntp_server_addr_type of this NtpServers.

        1  # noqa: E501

        :param ntp_server_addr_type: The ntp_server_addr_type of this NtpServers.
        :type ntp_server_addr_type: List[str]
        """
        if ntp_server_addr_type is None:
            raise ValueError("Invalid value for `ntp_server_addr_type`, must not be `None`")  # noqa: E501

        self._ntp_server_addr_type = ntp_server_addr_type

    @property
    def ntp_server_addr(self) -> List[str]:
        """Gets the ntp_server_addr of this NtpServers.

        1  # noqa: E501

        :return: The ntp_server_addr of this NtpServers.
        :rtype: List[str]
        """
        return self._ntp_server_addr

    @ntp_server_addr.setter
    def ntp_server_addr(self, ntp_server_addr: List[str]):
        """Sets the ntp_server_addr of this NtpServers.

        1  # noqa: E501

        :param ntp_server_addr: The ntp_server_addr of this NtpServers.
        :type ntp_server_addr: List[str]
        """
        if ntp_server_addr is None:
            raise ValueError("Invalid value for `ntp_server_addr`, must not be `None`")  # noqa: E501

        self._ntp_server_addr = ntp_server_addr

    @property
    def min_polling_interval(self) -> List[int]:
        """Gets the min_polling_interval of this NtpServers.

        1  # noqa: E501

        :return: The min_polling_interval of this NtpServers.
        :rtype: List[int]
        """
        return self._min_polling_interval

    @min_polling_interval.setter
    def min_polling_interval(self, min_polling_interval: List[int]):
        """Sets the min_polling_interval of this NtpServers.

        1  # noqa: E501

        :param min_polling_interval: The min_polling_interval of this NtpServers.
        :type min_polling_interval: List[int]
        """
        if min_polling_interval is None:
            raise ValueError("Invalid value for `min_polling_interval`, must not be `None`")  # noqa: E501

        self._min_polling_interval = min_polling_interval

    @property
    def max_polling_interval(self) -> List[int]:
        """Gets the max_polling_interval of this NtpServers.

        1  # noqa: E501

        :return: The max_polling_interval of this NtpServers.
        :rtype: List[int]
        """
        return self._max_polling_interval

    @max_polling_interval.setter
    def max_polling_interval(self, max_polling_interval: List[int]):
        """Sets the max_polling_interval of this NtpServers.

        1  # noqa: E501

        :param max_polling_interval: The max_polling_interval of this NtpServers.
        :type max_polling_interval: List[int]
        """
        if max_polling_interval is None:
            raise ValueError("Invalid value for `max_polling_interval`, must not be `None`")  # noqa: E501

        self._max_polling_interval = max_polling_interval

    @property
    def local_priority(self) -> List[int]:
        """Gets the local_priority of this NtpServers.

        1  # noqa: E501

        :return: The local_priority of this NtpServers.
        :rtype: List[int]
        """
        return self._local_priority

    @local_priority.setter
    def local_priority(self, local_priority: List[int]):
        """Sets the local_priority of this NtpServers.

        1  # noqa: E501

        :param local_priority: The local_priority of this NtpServers.
        :type local_priority: List[int]
        """
        if local_priority is None:
            raise ValueError("Invalid value for `local_priority`, must not be `None`")  # noqa: E501

        self._local_priority = local_priority

    @property
    def authentication_option(self) -> List[str]:
        """Gets the authentication_option of this NtpServers.

        1  # noqa: E501

        :return: The authentication_option of this NtpServers.
        :rtype: List[str]
        """
        return self._authentication_option

    @authentication_option.setter
    def authentication_option(self, authentication_option: List[str]):
        """Sets the authentication_option of this NtpServers.

        1  # noqa: E501

        :param authentication_option: The authentication_option of this NtpServers.
        :type authentication_option: List[str]
        """
        if authentication_option is None:
            raise ValueError("Invalid value for `authentication_option`, must not be `None`")  # noqa: E501

        self._authentication_option = authentication_option

    @property
    def authentication_key_num(self) -> List[int]:
        """Gets the authentication_key_num of this NtpServers.

        0..1  # noqa: E501

        :return: The authentication_key_num of this NtpServers.
        :rtype: List[int]
        """
        return self._authentication_key_num

    @authentication_key_num.setter
    def authentication_key_num(self, authentication_key_num: List[int]):
        """Sets the authentication_key_num of this NtpServers.

        0..1  # noqa: E501

        :param authentication_key_num: The authentication_key_num of this NtpServers.
        :type authentication_key_num: List[int]
        """
        if authentication_key_num is None:
            raise ValueError("Invalid value for `authentication_key_num`, must not be `None`")  # noqa: E501

        self._authentication_key_num = authentication_key_num
