from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class OAuth2Info(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, grant_types=None, token_endpoint=None):  # noqa: E501
        """OAuth2Info - a model defined in OpenAPI

        :param grant_types: The grant_types of this OAuth2Info.  # noqa: E501
        :type grant_types: List[str]
        :param token_endpoint: The token_endpoint of this OAuth2Info.  # noqa: E501
        :type token_endpoint: str
        """
        self.openapi_types = {
            'grant_types': List[str],
            'token_endpoint': str
        }

        self.attribute_map = {
            'grant_types': 'grantTypes',
            'token_endpoint': 'tokenEndpoint'
        }

        self._grant_types = grant_types
        self._token_endpoint = token_endpoint

    @classmethod
    def from_dict(cls, dikt) -> 'OAuth2Info':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OAuth2Info of this OAuth2Info.  # noqa: E501
        :rtype: OAuth2Info
        """
        return util.deserialize_model(dikt, cls)

    @property
    def grant_types(self) -> List[str]:
        """Gets the grant_types of this OAuth2Info.

        List of supported OAuth 2.0 grant types. Each entry shall be one of the following permitted values: • OAUTH2_AUTHORIZATION_CODE (Authorization code grant type) • OAUTH2_IMPLICIT_GRANT (Implicit grant type) • OAUTH2_RESOURCE_OWNER (Resource owner password credentials grant type) • OAUTH2_CLIENT_CREDENTIALS (Client credentials grant type) Only the value \"OAUTH2_CLIENT_CREDENTIALS\" is supported in the present document.  # noqa: E501

        :return: The grant_types of this OAuth2Info.
        :rtype: List[str]
        """
        return self._grant_types

    @grant_types.setter
    def grant_types(self, grant_types: List[str]):
        """Sets the grant_types of this OAuth2Info.

        List of supported OAuth 2.0 grant types. Each entry shall be one of the following permitted values: • OAUTH2_AUTHORIZATION_CODE (Authorization code grant type) • OAUTH2_IMPLICIT_GRANT (Implicit grant type) • OAUTH2_RESOURCE_OWNER (Resource owner password credentials grant type) • OAUTH2_CLIENT_CREDENTIALS (Client credentials grant type) Only the value \"OAUTH2_CLIENT_CREDENTIALS\" is supported in the present document.  # noqa: E501

        :param grant_types: The grant_types of this OAuth2Info.
        :type grant_types: List[str]
        """
        allowed_values = ["SEE_DESCRIPTION"]  # noqa: E501
        if not set(grant_types).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `grant_types` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(grant_types) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._grant_types = grant_types

    @property
    def token_endpoint(self) -> str:
        """Gets the token_endpoint of this OAuth2Info.

        The token endpoint. Shall be present unless the grant type is OAUTH2_IMPLICIT_GRANT.  # noqa: E501

        :return: The token_endpoint of this OAuth2Info.
        :rtype: str
        """
        return self._token_endpoint

    @token_endpoint.setter
    def token_endpoint(self, token_endpoint: str):
        """Sets the token_endpoint of this OAuth2Info.

        The token endpoint. Shall be present unless the grant type is OAUTH2_IMPLICIT_GRANT.  # noqa: E501

        :param token_endpoint: The token_endpoint of this OAuth2Info.
        :type token_endpoint: str
        """

        self._token_endpoint = token_endpoint
