from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class PtpMasters(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ptp_master_ip_address=None, ptp_master_local_priority=None, delay_req_max_rate=None):  # noqa: E501
        """PtpMasters - a model defined in OpenAPI

        :param ptp_master_ip_address: The ptp_master_ip_address of this PtpMasters.  # noqa: E501
        :type ptp_master_ip_address: List[str]
        :param ptp_master_local_priority: The ptp_master_local_priority of this PtpMasters.  # noqa: E501
        :type ptp_master_local_priority: List[int]
        :param delay_req_max_rate: The delay_req_max_rate of this PtpMasters.  # noqa: E501
        :type delay_req_max_rate: List[int]
        """
        self.openapi_types = {
            'ptp_master_ip_address': List[str],
            'ptp_master_local_priority': List[int],
            'delay_req_max_rate': List[int]
        }

        self.attribute_map = {
            'ptp_master_ip_address': 'ptpMasterIpAddress',
            'ptp_master_local_priority': 'ptpMasterLocalPriority',
            'delay_req_max_rate': 'delayReqMaxRate'
        }

        self._ptp_master_ip_address = ptp_master_ip_address
        self._ptp_master_local_priority = ptp_master_local_priority
        self._delay_req_max_rate = delay_req_max_rate

    @classmethod
    def from_dict(cls, dikt) -> 'PtpMasters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PtpMasters of this PtpMasters.  # noqa: E501
        :rtype: PtpMasters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ptp_master_ip_address(self) -> List[str]:
        """Gets the ptp_master_ip_address of this PtpMasters.

        1  # noqa: E501

        :return: The ptp_master_ip_address of this PtpMasters.
        :rtype: List[str]
        """
        return self._ptp_master_ip_address

    @ptp_master_ip_address.setter
    def ptp_master_ip_address(self, ptp_master_ip_address: List[str]):
        """Sets the ptp_master_ip_address of this PtpMasters.

        1  # noqa: E501

        :param ptp_master_ip_address: The ptp_master_ip_address of this PtpMasters.
        :type ptp_master_ip_address: List[str]
        """
        if ptp_master_ip_address is None:
            raise ValueError("Invalid value for `ptp_master_ip_address`, must not be `None`")  # noqa: E501

        self._ptp_master_ip_address = ptp_master_ip_address

    @property
    def ptp_master_local_priority(self) -> List[int]:
        """Gets the ptp_master_local_priority of this PtpMasters.

        1  # noqa: E501

        :return: The ptp_master_local_priority of this PtpMasters.
        :rtype: List[int]
        """
        return self._ptp_master_local_priority

    @ptp_master_local_priority.setter
    def ptp_master_local_priority(self, ptp_master_local_priority: List[int]):
        """Sets the ptp_master_local_priority of this PtpMasters.

        1  # noqa: E501

        :param ptp_master_local_priority: The ptp_master_local_priority of this PtpMasters.
        :type ptp_master_local_priority: List[int]
        """
        if ptp_master_local_priority is None:
            raise ValueError("Invalid value for `ptp_master_local_priority`, must not be `None`")  # noqa: E501

        self._ptp_master_local_priority = ptp_master_local_priority

    @property
    def delay_req_max_rate(self) -> List[int]:
        """Gets the delay_req_max_rate of this PtpMasters.

        1  # noqa: E501

        :return: The delay_req_max_rate of this PtpMasters.
        :rtype: List[int]
        """
        return self._delay_req_max_rate

    @delay_req_max_rate.setter
    def delay_req_max_rate(self, delay_req_max_rate: List[int]):
        """Sets the delay_req_max_rate of this PtpMasters.

        1  # noqa: E501

        :param delay_req_max_rate: The delay_req_max_rate of this PtpMasters.
        :type delay_req_max_rate: List[int]
        """
        if delay_req_max_rate is None:
            raise ValueError("Invalid value for `delay_req_max_rate`, must not be `None`")  # noqa: E501

        self._delay_req_max_rate = delay_req_max_rate
