from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.ntp_servers import NtpServers
from openapi_server.models.ptp_masters import PtpMasters
from openapi_server.models.time_stamp import TimeStamp
from openapi_server import util

from openapi_server.models.ntp_servers import NtpServers  # noqa: E501
from openapi_server.models.ptp_masters import PtpMasters  # noqa: E501
from openapi_server.models.time_stamp import TimeStamp  # noqa: E501

class TimingCaps(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, time_stamp=None, ntp_servers=None, ptp_masters=None):  # noqa: E501
        """TimingCaps - a model defined in OpenAPI

        :param time_stamp: The time_stamp of this TimingCaps.  # noqa: E501
        :type time_stamp: List[TimeStamp]
        :param ntp_servers: The ntp_servers of this TimingCaps.  # noqa: E501
        :type ntp_servers: List[NtpServers]
        :param ptp_masters: The ptp_masters of this TimingCaps.  # noqa: E501
        :type ptp_masters: List[PtpMasters]
        """
        self.openapi_types = {
            'time_stamp': List[TimeStamp],
            'ntp_servers': List[NtpServers],
            'ptp_masters': List[PtpMasters]
        }

        self.attribute_map = {
            'time_stamp': 'timeStamp',
            'ntp_servers': 'ntpServers',
            'ptp_masters': 'ptpMasters'
        }

        self._time_stamp = time_stamp
        self._ntp_servers = ntp_servers
        self._ptp_masters = ptp_masters

    @classmethod
    def from_dict(cls, dikt) -> 'TimingCaps':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TimingCaps of this TimingCaps.  # noqa: E501
        :rtype: TimingCaps
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time_stamp(self) -> List[TimeStamp]:
        """Gets the time_stamp of this TimingCaps.


        :return: The time_stamp of this TimingCaps.
        :rtype: List[TimeStamp]
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: List[TimeStamp]):
        """Sets the time_stamp of this TimingCaps.


        :param time_stamp: The time_stamp of this TimingCaps.
        :type time_stamp: List[TimeStamp]
        """
        if time_stamp is None:
            raise ValueError("Invalid value for `time_stamp`, must not be `None`")  # noqa: E501

        self._time_stamp = time_stamp

    @property
    def ntp_servers(self) -> List[NtpServers]:
        """Gets the ntp_servers of this TimingCaps.


        :return: The ntp_servers of this TimingCaps.
        :rtype: List[NtpServers]
        """
        return self._ntp_servers

    @ntp_servers.setter
    def ntp_servers(self, ntp_servers: List[NtpServers]):
        """Sets the ntp_servers of this TimingCaps.


        :param ntp_servers: The ntp_servers of this TimingCaps.
        :type ntp_servers: List[NtpServers]
        """
        if ntp_servers is None:
            raise ValueError("Invalid value for `ntp_servers`, must not be `None`")  # noqa: E501

        self._ntp_servers = ntp_servers

    @property
    def ptp_masters(self) -> List[PtpMasters]:
        """Gets the ptp_masters of this TimingCaps.


        :return: The ptp_masters of this TimingCaps.
        :rtype: List[PtpMasters]
        """
        return self._ptp_masters

    @ptp_masters.setter
    def ptp_masters(self, ptp_masters: List[PtpMasters]):
        """Sets the ptp_masters of this TimingCaps.


        :param ptp_masters: The ptp_masters of this TimingCaps.
        :type ptp_masters: List[PtpMasters]
        """
        if ptp_masters is None:
            raise ValueError("Invalid value for `ptp_masters`, must not be `None`")  # noqa: E501

        self._ptp_masters = ptp_masters
