from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.timing_caps import TimingCaps
from openapi_server import util

from openapi_server.models.timing_caps import TimingCaps  # noqa: E501

class TimingTimingcapsGET200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, timing_caps=None):  # noqa: E501
        """TimingTimingcapsGET200Response - a model defined in OpenAPI

        :param timing_caps: The timing_caps of this TimingTimingcapsGET200Response.  # noqa: E501
        :type timing_caps: TimingCaps
        """
        self.openapi_types = {
            'timing_caps': TimingCaps
        }

        self.attribute_map = {
            'timing_caps': 'TimingCaps'
        }

        self._timing_caps = timing_caps

    @classmethod
    def from_dict(cls, dikt) -> 'TimingTimingcapsGET200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TimingTimingcapsGET_200_response of this TimingTimingcapsGET200Response.  # noqa: E501
        :rtype: TimingTimingcapsGET200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timing_caps(self) -> TimingCaps:
        """Gets the timing_caps of this TimingTimingcapsGET200Response.


        :return: The timing_caps of this TimingTimingcapsGET200Response.
        :rtype: TimingCaps
        """
        return self._timing_caps

    @timing_caps.setter
    def timing_caps(self, timing_caps: TimingCaps):
        """Sets the timing_caps of this TimingTimingcapsGET200Response.


        :param timing_caps: The timing_caps of this TimingTimingcapsGET200Response.
        :type timing_caps: TimingCaps
        """

        self._timing_caps = timing_caps
