from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.destination_interface import DestinationInterface
from openapi_server.models.traffic_filter import TrafficFilter
from openapi_server import util

from openapi_server.models.destination_interface import DestinationInterface  # noqa: E501
from openapi_server.models.traffic_filter import TrafficFilter  # noqa: E501

class TrafficRule(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, traffic_rule_id=None, filter_type=None, priority=None, traffic_filter=None, action=None, dst_interface=None, state=None):  # noqa: E501
        """TrafficRule - a model defined in OpenAPI

        :param traffic_rule_id: The traffic_rule_id of this TrafficRule.  # noqa: E501
        :type traffic_rule_id: str
        :param filter_type: The filter_type of this TrafficRule.  # noqa: E501
        :type filter_type: str
        :param priority: The priority of this TrafficRule.  # noqa: E501
        :type priority: int
        :param traffic_filter: The traffic_filter of this TrafficRule.  # noqa: E501
        :type traffic_filter: List[TrafficFilter]
        :param action: The action of this TrafficRule.  # noqa: E501
        :type action: str
        :param dst_interface: The dst_interface of this TrafficRule.  # noqa: E501
        :type dst_interface: DestinationInterface
        :param state: The state of this TrafficRule.  # noqa: E501
        :type state: str
        """
        self.openapi_types = {
            'traffic_rule_id': str,
            'filter_type': str,
            'priority': int,
            'traffic_filter': List[TrafficFilter],
            'action': str,
            'dst_interface': DestinationInterface,
            'state': str
        }

        self.attribute_map = {
            'traffic_rule_id': 'trafficRuleId',
            'filter_type': 'filterType',
            'priority': 'priority',
            'traffic_filter': 'trafficFilter',
            'action': 'action',
            'dst_interface': 'dstInterface',
            'state': 'state'
        }

        self._traffic_rule_id = traffic_rule_id
        self._filter_type = filter_type
        self._priority = priority
        self._traffic_filter = traffic_filter
        self._action = action
        self._dst_interface = dst_interface
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'TrafficRule':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrafficRule of this TrafficRule.  # noqa: E501
        :rtype: TrafficRule
        """
        return util.deserialize_model(dikt, cls)

    @property
    def traffic_rule_id(self) -> str:
        """Gets the traffic_rule_id of this TrafficRule.

        Identify the traffic rule.  # noqa: E501

        :return: The traffic_rule_id of this TrafficRule.
        :rtype: str
        """
        return self._traffic_rule_id

    @traffic_rule_id.setter
    def traffic_rule_id(self, traffic_rule_id: str):
        """Sets the traffic_rule_id of this TrafficRule.

        Identify the traffic rule.  # noqa: E501

        :param traffic_rule_id: The traffic_rule_id of this TrafficRule.
        :type traffic_rule_id: str
        """
        if traffic_rule_id is None:
            raise ValueError("Invalid value for `traffic_rule_id`, must not be `None`")  # noqa: E501

        self._traffic_rule_id = traffic_rule_id

    @property
    def filter_type(self) -> str:
        """Gets the filter_type of this TrafficRule.

        Definition of filter per FLOW or PACKET. If FLOW, the filter matches upstream (e.g. UEEPC) packets and upstream (e.g. EPCUE) packets are handled in the same context.  # noqa: E501

        :return: The filter_type of this TrafficRule.
        :rtype: str
        """
        return self._filter_type

    @filter_type.setter
    def filter_type(self, filter_type: str):
        """Sets the filter_type of this TrafficRule.

        Definition of filter per FLOW or PACKET. If FLOW, the filter matches upstream (e.g. UEEPC) packets and upstream (e.g. EPCUE) packets are handled in the same context.  # noqa: E501

        :param filter_type: The filter_type of this TrafficRule.
        :type filter_type: str
        """
        allowed_values = ["SEE_DESCRIPTION"]  # noqa: E501
        if filter_type not in allowed_values:
            raise ValueError(
                "Invalid value for `filter_type` ({0}), must be one of {1}"
                .format(filter_type, allowed_values)
            )

        self._filter_type = filter_type

    @property
    def priority(self) -> int:
        """Gets the priority of this TrafficRule.

        Priority of this traffic rule within the range 0 to 255. If traffic rules conflict, the one with higher priority take precedence. See note 1.  # noqa: E501

        :return: The priority of this TrafficRule.
        :rtype: int
        """
        return self._priority

    @priority.setter
    def priority(self, priority: int):
        """Sets the priority of this TrafficRule.

        Priority of this traffic rule within the range 0 to 255. If traffic rules conflict, the one with higher priority take precedence. See note 1.  # noqa: E501

        :param priority: The priority of this TrafficRule.
        :type priority: int
        """
        if priority is None:
            raise ValueError("Invalid value for `priority`, must not be `None`")  # noqa: E501

        self._priority = priority

    @property
    def traffic_filter(self) -> List[TrafficFilter]:
        """Gets the traffic_filter of this TrafficRule.

        The filter used to identify specific packets that need to be handled by the MEC host.  # noqa: E501

        :return: The traffic_filter of this TrafficRule.
        :rtype: List[TrafficFilter]
        """
        return self._traffic_filter

    @traffic_filter.setter
    def traffic_filter(self, traffic_filter: List[TrafficFilter]):
        """Sets the traffic_filter of this TrafficRule.

        The filter used to identify specific packets that need to be handled by the MEC host.  # noqa: E501

        :param traffic_filter: The traffic_filter of this TrafficRule.
        :type traffic_filter: List[TrafficFilter]
        """
        if traffic_filter is None:
            raise ValueError("Invalid value for `traffic_filter`, must not be `None`")  # noqa: E501
        if traffic_filter is not None and len(traffic_filter) < 1:
            raise ValueError("Invalid value for `traffic_filter`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._traffic_filter = traffic_filter

    @property
    def action(self) -> str:
        """Gets the action of this TrafficRule.

        The action of the MEC host data plane when a packet matches the trafficFilter, the following actions are defined: DROP FORWARD_DECAPSULATED FORWARD_ENCAPSULATED PASSTHROUGH DUPLICATE_DECAPSULATED DUPLICATE_ENCAPSULATED  # noqa: E501

        :return: The action of this TrafficRule.
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action: str):
        """Sets the action of this TrafficRule.

        The action of the MEC host data plane when a packet matches the trafficFilter, the following actions are defined: DROP FORWARD_DECAPSULATED FORWARD_ENCAPSULATED PASSTHROUGH DUPLICATE_DECAPSULATED DUPLICATE_ENCAPSULATED  # noqa: E501

        :param action: The action of this TrafficRule.
        :type action: str
        """
        allowed_values = ["DUPLICATE_ENCAPSULATED"]  # noqa: E501
        if action not in allowed_values:
            raise ValueError(
                "Invalid value for `action` ({0}), must be one of {1}"
                .format(action, allowed_values)
            )

        self._action = action

    @property
    def dst_interface(self) -> DestinationInterface:
        """Gets the dst_interface of this TrafficRule.

        Describes the destination interface information. If the action is FORWARD_DECAPSULATED, FORWARD_ENCAPSULATED or PASSTHROUGH one value shall be provided. If the action is DUPLICATE_DECAPSULATED or DUPLICATE_ENCAPSULATED, two values shall be provided. See note 2. If the action is DROP, no value shall be provided.  # noqa: E501

        :return: The dst_interface of this TrafficRule.
        :rtype: DestinationInterface
        """
        return self._dst_interface

    @dst_interface.setter
    def dst_interface(self, dst_interface: DestinationInterface):
        """Sets the dst_interface of this TrafficRule.

        Describes the destination interface information. If the action is FORWARD_DECAPSULATED, FORWARD_ENCAPSULATED or PASSTHROUGH one value shall be provided. If the action is DUPLICATE_DECAPSULATED or DUPLICATE_ENCAPSULATED, two values shall be provided. See note 2. If the action is DROP, no value shall be provided.  # noqa: E501

        :param dst_interface: The dst_interface of this TrafficRule.
        :type dst_interface: DestinationInterface
        """

        self._dst_interface = dst_interface

    @property
    def state(self) -> str:
        """Gets the state of this TrafficRule.

        Contains the traffic rule state: ACTIVE, INACTIVE. This attribute may be updated using HTTP PUT method.  # noqa: E501

        :return: The state of this TrafficRule.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this TrafficRule.

        Contains the traffic rule state: ACTIVE, INACTIVE. This attribute may be updated using HTTP PUT method.  # noqa: E501

        :param state: The state of this TrafficRule.
        :type state: str
        """
        allowed_values = ["SEE_DESCRIPTION"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"
                .format(state, allowed_values)
            )

        self._state = state
