from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TrafficFilter(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, src_address=None, dst_address=None, src_port=None, dst_port=None, protocol=None, tag=None, src_tunnel_address=None, tgt_tunnel_address=None, src_tunnel_port=None, dst_tunnel_port=None, q_ci=None, d_scp=None, t_c=None):  # noqa: E501
        """TrafficFilter - a model defined in OpenAPI

        :param src_address: The src_address of this TrafficFilter.  # noqa: E501
        :type src_address: List[str]
        :param dst_address: The dst_address of this TrafficFilter.  # noqa: E501
        :type dst_address: List[str]
        :param src_port: The src_port of this TrafficFilter.  # noqa: E501
        :type src_port: List[str]
        :param dst_port: The dst_port of this TrafficFilter.  # noqa: E501
        :type dst_port: List[str]
        :param protocol: The protocol of this TrafficFilter.  # noqa: E501
        :type protocol: List[str]
        :param tag: The tag of this TrafficFilter.  # noqa: E501
        :type tag: List[str]
        :param src_tunnel_address: The src_tunnel_address of this TrafficFilter.  # noqa: E501
        :type src_tunnel_address: List[str]
        :param tgt_tunnel_address: The tgt_tunnel_address of this TrafficFilter.  # noqa: E501
        :type tgt_tunnel_address: List[str]
        :param src_tunnel_port: The src_tunnel_port of this TrafficFilter.  # noqa: E501
        :type src_tunnel_port: List[str]
        :param dst_tunnel_port: The dst_tunnel_port of this TrafficFilter.  # noqa: E501
        :type dst_tunnel_port: List[str]
        :param q_ci: The q_ci of this TrafficFilter.  # noqa: E501
        :type q_ci: int
        :param d_scp: The d_scp of this TrafficFilter.  # noqa: E501
        :type d_scp: int
        :param t_c: The t_c of this TrafficFilter.  # noqa: E501
        :type t_c: int
        """
        self.openapi_types = {
            'src_address': List[str],
            'dst_address': List[str],
            'src_port': List[str],
            'dst_port': List[str],
            'protocol': List[str],
            'tag': List[str],
            'src_tunnel_address': List[str],
            'tgt_tunnel_address': List[str],
            'src_tunnel_port': List[str],
            'dst_tunnel_port': List[str],
            'q_ci': int,
            'd_scp': int,
            't_c': int
        }

        self.attribute_map = {
            'src_address': 'srcAddress',
            'dst_address': 'dstAddress',
            'src_port': 'srcPort',
            'dst_port': 'dstPort',
            'protocol': 'protocol',
            'tag': 'tag',
            'src_tunnel_address': 'srcTunnelAddress',
            'tgt_tunnel_address': 'tgtTunnelAddress',
            'src_tunnel_port': 'srcTunnelPort',
            'dst_tunnel_port': 'dstTunnelPort',
            'q_ci': 'qCI',
            'd_scp': 'dSCP',
            't_c': 'tC'
        }

        self._src_address = src_address
        self._dst_address = dst_address
        self._src_port = src_port
        self._dst_port = dst_port
        self._protocol = protocol
        self._tag = tag
        self._src_tunnel_address = src_tunnel_address
        self._tgt_tunnel_address = tgt_tunnel_address
        self._src_tunnel_port = src_tunnel_port
        self._dst_tunnel_port = dst_tunnel_port
        self._q_ci = q_ci
        self._d_scp = d_scp
        self._t_c = t_c

    @classmethod
    def from_dict(cls, dikt) -> 'TrafficFilter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrafficFilter of this TrafficFilter.  # noqa: E501
        :rtype: TrafficFilter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def src_address(self) -> List[str]:
        """Gets the src_address of this TrafficFilter.

        An IP address or a range of IP address. For IPv4, the IP address could be an IP address plus mask, or an individual IP address, or a range of IP addresses. For IPv6, the IP address could be an IP prefix, or a range of IP prefixes.  # noqa: E501

        :return: The src_address of this TrafficFilter.
        :rtype: List[str]
        """
        return self._src_address

    @src_address.setter
    def src_address(self, src_address: List[str]):
        """Sets the src_address of this TrafficFilter.

        An IP address or a range of IP address. For IPv4, the IP address could be an IP address plus mask, or an individual IP address, or a range of IP addresses. For IPv6, the IP address could be an IP prefix, or a range of IP prefixes.  # noqa: E501

        :param src_address: The src_address of this TrafficFilter.
        :type src_address: List[str]
        """
        if src_address is not None and len(src_address) < 0:
            raise ValueError("Invalid value for `src_address`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._src_address = src_address

    @property
    def dst_address(self) -> List[str]:
        """Gets the dst_address of this TrafficFilter.

        An IP address or a range of IP address. For IPv4, the IP address could be an IP address plus mask, or an individual IP address, or a range of IP addresses. For IPv6, the IP address could be an IP prefix, or a range of IP prefixes.  # noqa: E501

        :return: The dst_address of this TrafficFilter.
        :rtype: List[str]
        """
        return self._dst_address

    @dst_address.setter
    def dst_address(self, dst_address: List[str]):
        """Sets the dst_address of this TrafficFilter.

        An IP address or a range of IP address. For IPv4, the IP address could be an IP address plus mask, or an individual IP address, or a range of IP addresses. For IPv6, the IP address could be an IP prefix, or a range of IP prefixes.  # noqa: E501

        :param dst_address: The dst_address of this TrafficFilter.
        :type dst_address: List[str]
        """
        if dst_address is not None and len(dst_address) < 0:
            raise ValueError("Invalid value for `dst_address`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._dst_address = dst_address

    @property
    def src_port(self) -> List[str]:
        """Gets the src_port of this TrafficFilter.

        A port or a range of ports.  # noqa: E501

        :return: The src_port of this TrafficFilter.
        :rtype: List[str]
        """
        return self._src_port

    @src_port.setter
    def src_port(self, src_port: List[str]):
        """Sets the src_port of this TrafficFilter.

        A port or a range of ports.  # noqa: E501

        :param src_port: The src_port of this TrafficFilter.
        :type src_port: List[str]
        """
        if src_port is not None and len(src_port) < 0:
            raise ValueError("Invalid value for `src_port`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._src_port = src_port

    @property
    def dst_port(self) -> List[str]:
        """Gets the dst_port of this TrafficFilter.

        A port or a range of ports.  # noqa: E501

        :return: The dst_port of this TrafficFilter.
        :rtype: List[str]
        """
        return self._dst_port

    @dst_port.setter
    def dst_port(self, dst_port: List[str]):
        """Sets the dst_port of this TrafficFilter.

        A port or a range of ports.  # noqa: E501

        :param dst_port: The dst_port of this TrafficFilter.
        :type dst_port: List[str]
        """
        if dst_port is not None and len(dst_port) < 0:
            raise ValueError("Invalid value for `dst_port`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._dst_port = dst_port

    @property
    def protocol(self) -> List[str]:
        """Gets the protocol of this TrafficFilter.

        Specify the protocol of the traffic filter.  # noqa: E501

        :return: The protocol of this TrafficFilter.
        :rtype: List[str]
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol: List[str]):
        """Sets the protocol of this TrafficFilter.

        Specify the protocol of the traffic filter.  # noqa: E501

        :param protocol: The protocol of this TrafficFilter.
        :type protocol: List[str]
        """
        if protocol is not None and len(protocol) < 0:
            raise ValueError("Invalid value for `protocol`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._protocol = protocol

    @property
    def tag(self) -> List[str]:
        """Gets the tag of this TrafficFilter.

        Used for tag based traffic rule.  # noqa: E501

        :return: The tag of this TrafficFilter.
        :rtype: List[str]
        """
        return self._tag

    @tag.setter
    def tag(self, tag: List[str]):
        """Sets the tag of this TrafficFilter.

        Used for tag based traffic rule.  # noqa: E501

        :param tag: The tag of this TrafficFilter.
        :type tag: List[str]
        """
        if tag is not None and len(tag) < 0:
            raise ValueError("Invalid value for `tag`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._tag = tag

    @property
    def src_tunnel_address(self) -> List[str]:
        """Gets the src_tunnel_address of this TrafficFilter.

        Used for GTP tunnel based traffic rule.  # noqa: E501

        :return: The src_tunnel_address of this TrafficFilter.
        :rtype: List[str]
        """
        return self._src_tunnel_address

    @src_tunnel_address.setter
    def src_tunnel_address(self, src_tunnel_address: List[str]):
        """Sets the src_tunnel_address of this TrafficFilter.

        Used for GTP tunnel based traffic rule.  # noqa: E501

        :param src_tunnel_address: The src_tunnel_address of this TrafficFilter.
        :type src_tunnel_address: List[str]
        """
        if src_tunnel_address is not None and len(src_tunnel_address) < 0:
            raise ValueError("Invalid value for `src_tunnel_address`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._src_tunnel_address = src_tunnel_address

    @property
    def tgt_tunnel_address(self) -> List[str]:
        """Gets the tgt_tunnel_address of this TrafficFilter.

        Used for GTP tunnel based traffic rule.  # noqa: E501

        :return: The tgt_tunnel_address of this TrafficFilter.
        :rtype: List[str]
        """
        return self._tgt_tunnel_address

    @tgt_tunnel_address.setter
    def tgt_tunnel_address(self, tgt_tunnel_address: List[str]):
        """Sets the tgt_tunnel_address of this TrafficFilter.

        Used for GTP tunnel based traffic rule.  # noqa: E501

        :param tgt_tunnel_address: The tgt_tunnel_address of this TrafficFilter.
        :type tgt_tunnel_address: List[str]
        """
        if tgt_tunnel_address is not None and len(tgt_tunnel_address) < 0:
            raise ValueError("Invalid value for `tgt_tunnel_address`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._tgt_tunnel_address = tgt_tunnel_address

    @property
    def src_tunnel_port(self) -> List[str]:
        """Gets the src_tunnel_port of this TrafficFilter.

        Used for GTP tunnel based traffic rule.  # noqa: E501

        :return: The src_tunnel_port of this TrafficFilter.
        :rtype: List[str]
        """
        return self._src_tunnel_port

    @src_tunnel_port.setter
    def src_tunnel_port(self, src_tunnel_port: List[str]):
        """Sets the src_tunnel_port of this TrafficFilter.

        Used for GTP tunnel based traffic rule.  # noqa: E501

        :param src_tunnel_port: The src_tunnel_port of this TrafficFilter.
        :type src_tunnel_port: List[str]
        """
        if src_tunnel_port is not None and len(src_tunnel_port) < 0:
            raise ValueError("Invalid value for `src_tunnel_port`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._src_tunnel_port = src_tunnel_port

    @property
    def dst_tunnel_port(self) -> List[str]:
        """Gets the dst_tunnel_port of this TrafficFilter.

        Used for GTP tunnel based traffic rule.  # noqa: E501

        :return: The dst_tunnel_port of this TrafficFilter.
        :rtype: List[str]
        """
        return self._dst_tunnel_port

    @dst_tunnel_port.setter
    def dst_tunnel_port(self, dst_tunnel_port: List[str]):
        """Sets the dst_tunnel_port of this TrafficFilter.

        Used for GTP tunnel based traffic rule.  # noqa: E501

        :param dst_tunnel_port: The dst_tunnel_port of this TrafficFilter.
        :type dst_tunnel_port: List[str]
        """
        if dst_tunnel_port is not None and len(dst_tunnel_port) < 0:
            raise ValueError("Invalid value for `dst_tunnel_port`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._dst_tunnel_port = dst_tunnel_port

    @property
    def q_ci(self) -> int:
        """Gets the q_ci of this TrafficFilter.

        Used to match all packets that have the same QCI.  # noqa: E501

        :return: The q_ci of this TrafficFilter.
        :rtype: int
        """
        return self._q_ci

    @q_ci.setter
    def q_ci(self, q_ci: int):
        """Sets the q_ci of this TrafficFilter.

        Used to match all packets that have the same QCI.  # noqa: E501

        :param q_ci: The q_ci of this TrafficFilter.
        :type q_ci: int
        """

        self._q_ci = q_ci

    @property
    def d_scp(self) -> int:
        """Gets the d_scp of this TrafficFilter.

        Used to match all IPv4 packets that have the same DSCP.  # noqa: E501

        :return: The d_scp of this TrafficFilter.
        :rtype: int
        """
        return self._d_scp

    @d_scp.setter
    def d_scp(self, d_scp: int):
        """Sets the d_scp of this TrafficFilter.

        Used to match all IPv4 packets that have the same DSCP.  # noqa: E501

        :param d_scp: The d_scp of this TrafficFilter.
        :type d_scp: int
        """

        self._d_scp = d_scp

    @property
    def t_c(self) -> int:
        """Gets the t_c of this TrafficFilter.

        Used to match all IPv6 packets that have the same TC.  # noqa: E501

        :return: The t_c of this TrafficFilter.
        :rtype: int
        """
        return self._t_c

    @t_c.setter
    def t_c(self, t_c: int):
        """Sets the t_c of this TrafficFilter.

        Used to match all IPv6 packets that have the same TC.  # noqa: E501

        :param t_c: The t_c of this TrafficFilter.
        :type t_c: int
        """

        self._t_c = t_c
