from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.security_info import SecurityInfo
from openapi_server.models.transport_types import TransportTypes
from openapi_server import util

from openapi_server.models.security_info import SecurityInfo  # noqa: E501
from openapi_server.models.transport_types import TransportTypes  # noqa: E501

class TransportDescriptor(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, description=None, type=None, protocol=None, version=None, security=None, impl_specific_info=None):  # noqa: E501
        """TransportDescriptor - a model defined in OpenAPI

        :param name: The name of this TransportDescriptor.  # noqa: E501
        :type name: str
        :param description: The description of this TransportDescriptor.  # noqa: E501
        :type description: str
        :param type: The type of this TransportDescriptor.  # noqa: E501
        :type type: TransportTypes
        :param protocol: The protocol of this TransportDescriptor.  # noqa: E501
        :type protocol: str
        :param version: The version of this TransportDescriptor.  # noqa: E501
        :type version: str
        :param security: The security of this TransportDescriptor.  # noqa: E501
        :type security: SecurityInfo
        :param impl_specific_info: The impl_specific_info of this TransportDescriptor.  # noqa: E501
        :type impl_specific_info: object
        """
        self.openapi_types = {
            'name': str,
            'description': str,
            'type': TransportTypes,
            'protocol': str,
            'version': str,
            'security': SecurityInfo,
            'impl_specific_info': object
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'type': 'type',
            'protocol': 'protocol',
            'version': 'version',
            'security': 'security',
            'impl_specific_info': 'implSpecificInfo'
        }

        self._name = name
        self._description = description
        self._type = type
        self._protocol = protocol
        self._version = version
        self._security = security
        self._impl_specific_info = impl_specific_info

    @classmethod
    def from_dict(cls, dikt) -> 'TransportDescriptor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TransportDescriptor of this TransportDescriptor.  # noqa: E501
        :rtype: TransportDescriptor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this TransportDescriptor.

        The name of this transport.  # noqa: E501

        :return: The name of this TransportDescriptor.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this TransportDescriptor.

        The name of this transport.  # noqa: E501

        :param name: The name of this TransportDescriptor.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this TransportDescriptor.

        Human-readable description of this transport.  # noqa: E501

        :return: The description of this TransportDescriptor.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this TransportDescriptor.

        Human-readable description of this transport.  # noqa: E501

        :param description: The description of this TransportDescriptor.
        :type description: str
        """

        self._description = description

    @property
    def type(self) -> TransportTypes:
        """Gets the type of this TransportDescriptor.


        :return: The type of this TransportDescriptor.
        :rtype: TransportTypes
        """
        return self._type

    @type.setter
    def type(self, type: TransportTypes):
        """Sets the type of this TransportDescriptor.


        :param type: The type of this TransportDescriptor.
        :type type: TransportTypes
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def protocol(self) -> str:
        """Gets the protocol of this TransportDescriptor.

        The name of the protocol used. Shall be set to \"HTTP\" for a REST API.  # noqa: E501

        :return: The protocol of this TransportDescriptor.
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol: str):
        """Sets the protocol of this TransportDescriptor.

        The name of the protocol used. Shall be set to \"HTTP\" for a REST API.  # noqa: E501

        :param protocol: The protocol of this TransportDescriptor.
        :type protocol: str
        """
        if protocol is None:
            raise ValueError("Invalid value for `protocol`, must not be `None`")  # noqa: E501

        self._protocol = protocol

    @property
    def version(self) -> str:
        """Gets the version of this TransportDescriptor.

        The version of the protocol used.  # noqa: E501

        :return: The version of this TransportDescriptor.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this TransportDescriptor.

        The version of the protocol used.  # noqa: E501

        :param version: The version of this TransportDescriptor.
        :type version: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    @property
    def security(self) -> SecurityInfo:
        """Gets the security of this TransportDescriptor.


        :return: The security of this TransportDescriptor.
        :rtype: SecurityInfo
        """
        return self._security

    @security.setter
    def security(self, security: SecurityInfo):
        """Sets the security of this TransportDescriptor.


        :param security: The security of this TransportDescriptor.
        :type security: SecurityInfo
        """
        if security is None:
            raise ValueError("Invalid value for `security`, must not be `None`")  # noqa: E501

        self._security = security

    @property
    def impl_specific_info(self) -> object:
        """Gets the impl_specific_info of this TransportDescriptor.

        Additional implementation specific details of the transport.  # noqa: E501

        :return: The impl_specific_info of this TransportDescriptor.
        :rtype: object
        """
        return self._impl_specific_info

    @impl_specific_info.setter
    def impl_specific_info(self, impl_specific_info: object):
        """Sets the impl_specific_info of this TransportDescriptor.

        Additional implementation specific details of the transport.  # noqa: E501

        :param impl_specific_info: The impl_specific_info of this TransportDescriptor.
        :type impl_specific_info: object
        """

        self._impl_specific_info = impl_specific_info
