from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TunnelInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, tunnel_type=None, tunnel_dst_address=None, tunnel_src_address=None):  # noqa: E501
        """TunnelInfo - a model defined in OpenAPI

        :param tunnel_type: The tunnel_type of this TunnelInfo.  # noqa: E501
        :type tunnel_type: str
        :param tunnel_dst_address: The tunnel_dst_address of this TunnelInfo.  # noqa: E501
        :type tunnel_dst_address: str
        :param tunnel_src_address: The tunnel_src_address of this TunnelInfo.  # noqa: E501
        :type tunnel_src_address: str
        """
        self.openapi_types = {
            'tunnel_type': str,
            'tunnel_dst_address': str,
            'tunnel_src_address': str
        }

        self.attribute_map = {
            'tunnel_type': 'tunnelType',
            'tunnel_dst_address': 'tunnelDstAddress',
            'tunnel_src_address': 'tunnelSrcAddress'
        }

        self._tunnel_type = tunnel_type
        self._tunnel_dst_address = tunnel_dst_address
        self._tunnel_src_address = tunnel_src_address

    @classmethod
    def from_dict(cls, dikt) -> 'TunnelInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TunnelInfo of this TunnelInfo.  # noqa: E501
        :rtype: TunnelInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tunnel_type(self) -> str:
        """Gets the tunnel_type of this TunnelInfo.

        Type of the tunnel, e.g. GTP_U, GRE, etc.  # noqa: E501

        :return: The tunnel_type of this TunnelInfo.
        :rtype: str
        """
        return self._tunnel_type

    @tunnel_type.setter
    def tunnel_type(self, tunnel_type: str):
        """Sets the tunnel_type of this TunnelInfo.

        Type of the tunnel, e.g. GTP_U, GRE, etc.  # noqa: E501

        :param tunnel_type: The tunnel_type of this TunnelInfo.
        :type tunnel_type: str
        """
        allowed_values = ["SEE_DESCRIPTION"]  # noqa: E501
        if tunnel_type not in allowed_values:
            raise ValueError(
                "Invalid value for `tunnel_type` ({0}), must be one of {1}"
                .format(tunnel_type, allowed_values)
            )

        self._tunnel_type = tunnel_type

    @property
    def tunnel_dst_address(self) -> str:
        """Gets the tunnel_dst_address of this TunnelInfo.

        Destination address of the tunnel  # noqa: E501

        :return: The tunnel_dst_address of this TunnelInfo.
        :rtype: str
        """
        return self._tunnel_dst_address

    @tunnel_dst_address.setter
    def tunnel_dst_address(self, tunnel_dst_address: str):
        """Sets the tunnel_dst_address of this TunnelInfo.

        Destination address of the tunnel  # noqa: E501

        :param tunnel_dst_address: The tunnel_dst_address of this TunnelInfo.
        :type tunnel_dst_address: str
        """

        self._tunnel_dst_address = tunnel_dst_address

    @property
    def tunnel_src_address(self) -> str:
        """Gets the tunnel_src_address of this TunnelInfo.

        Source address of the tunnel  # noqa: E501

        :return: The tunnel_src_address of this TunnelInfo.
        :rtype: str
        """
        return self._tunnel_src_address

    @tunnel_src_address.setter
    def tunnel_src_address(self, tunnel_src_address: str):
        """Sets the tunnel_src_address of this TunnelInfo.

        Source address of the tunnel  # noqa: E501

        :param tunnel_src_address: The tunnel_src_address of this TunnelInfo.
        :type tunnel_src_address: str
        """

        self._tunnel_src_address = tunnel_src_address
