from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.associate_id import AssociateId
from openapi_server.models.carrier_aggregation_meas_info1 import CarrierAggregationMeasInfo1
from openapi_server.models.ecgi import Ecgi
from openapi_server.models.link_type import LinkType
from openapi_server.models.links import Links
from openapi_server.models.secondary_cell_add import SecondaryCellAdd
from openapi_server.models.secondary_cell_remove import SecondaryCellRemove
from openapi_server.models.time_stamp import TimeStamp
from openapi_server import util

from openapi_server.models.associate_id import AssociateId  # noqa: E501
from openapi_server.models.carrier_aggregation_meas_info1 import CarrierAggregationMeasInfo1  # noqa: E501
from openapi_server.models.ecgi import Ecgi  # noqa: E501
from openapi_server.models.link_type import LinkType  # noqa: E501
from openapi_server.models.links import Links  # noqa: E501
from openapi_server.models.secondary_cell_add import SecondaryCellAdd  # noqa: E501
from openapi_server.models.secondary_cell_remove import SecondaryCellRemove  # noqa: E501
from openapi_server.models.time_stamp import TimeStamp  # noqa: E501

class CaReconfNotification(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, notification_type=None, time_stamp=None, ecgi=None, associate_id=None, secondary_cell_add=None, secondary_cell_remove=None, carrier_aggregation_meas_info=None, links=None, subscription=None):  # noqa: E501
        """CaReconfNotification - a model defined in OpenAPI

        :param notification_type: The notification_type of this CaReconfNotification.  # noqa: E501
        :type notification_type: str
        :param time_stamp: The time_stamp of this CaReconfNotification.  # noqa: E501
        :type time_stamp: TimeStamp
        :param ecgi: The ecgi of this CaReconfNotification.  # noqa: E501
        :type ecgi: Ecgi
        :param associate_id: The associate_id of this CaReconfNotification.  # noqa: E501
        :type associate_id: List[AssociateId]
        :param secondary_cell_add: The secondary_cell_add of this CaReconfNotification.  # noqa: E501
        :type secondary_cell_add: List[SecondaryCellAdd]
        :param secondary_cell_remove: The secondary_cell_remove of this CaReconfNotification.  # noqa: E501
        :type secondary_cell_remove: List[SecondaryCellRemove]
        :param carrier_aggregation_meas_info: The carrier_aggregation_meas_info of this CaReconfNotification.  # noqa: E501
        :type carrier_aggregation_meas_info: List[CarrierAggregationMeasInfo1]
        :param links: The links of this CaReconfNotification.  # noqa: E501
        :type links: List[Links]
        :param subscription: The subscription of this CaReconfNotification.  # noqa: E501
        :type subscription: List[LinkType]
        """
        self.openapi_types = {
            'notification_type': str,
            'time_stamp': TimeStamp,
            'ecgi': Ecgi,
            'associate_id': List[AssociateId],
            'secondary_cell_add': List[SecondaryCellAdd],
            'secondary_cell_remove': List[SecondaryCellRemove],
            'carrier_aggregation_meas_info': List[CarrierAggregationMeasInfo1],
            'links': List[Links],
            'subscription': List[LinkType]
        }

        self.attribute_map = {
            'notification_type': 'notificationType',
            'time_stamp': 'timeStamp',
            'ecgi': 'ecgi',
            'associate_id': 'associateId',
            'secondary_cell_add': 'secondaryCellAdd',
            'secondary_cell_remove': 'secondaryCellRemove',
            'carrier_aggregation_meas_info': 'carrierAggregationMeasInfo',
            'links': '_links',
            'subscription': 'subscription'
        }

        self._notification_type = notification_type
        self._time_stamp = time_stamp
        self._ecgi = ecgi
        self._associate_id = associate_id
        self._secondary_cell_add = secondary_cell_add
        self._secondary_cell_remove = secondary_cell_remove
        self._carrier_aggregation_meas_info = carrier_aggregation_meas_info
        self._links = links
        self._subscription = subscription

    @classmethod
    def from_dict(cls, dikt) -> 'CaReconfNotification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CaReconfNotification of this CaReconfNotification.  # noqa: E501
        :rtype: CaReconfNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_type(self) -> str:
        """Gets the notification_type of this CaReconfNotification.

        Shall be set to \"CaReconfNotification\".  # noqa: E501

        :return: The notification_type of this CaReconfNotification.
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type: str):
        """Sets the notification_type of this CaReconfNotification.

        Shall be set to \"CaReconfNotification\".  # noqa: E501

        :param notification_type: The notification_type of this CaReconfNotification.
        :type notification_type: str
        """
        if notification_type is None:
            raise ValueError("Invalid value for `notification_type`, must not be `None`")  # noqa: E501

        self._notification_type = notification_type

    @property
    def time_stamp(self) -> TimeStamp:
        """Gets the time_stamp of this CaReconfNotification.

        Time stamp.  # noqa: E501

        :return: The time_stamp of this CaReconfNotification.
        :rtype: TimeStamp
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: TimeStamp):
        """Sets the time_stamp of this CaReconfNotification.

        Time stamp.  # noqa: E501

        :param time_stamp: The time_stamp of this CaReconfNotification.
        :type time_stamp: TimeStamp
        """

        self._time_stamp = time_stamp

    @property
    def ecgi(self) -> Ecgi:
        """Gets the ecgi of this CaReconfNotification.

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :return: The ecgi of this CaReconfNotification.
        :rtype: Ecgi
        """
        return self._ecgi

    @ecgi.setter
    def ecgi(self, ecgi: Ecgi):
        """Sets the ecgi of this CaReconfNotification.

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :param ecgi: The ecgi of this CaReconfNotification.
        :type ecgi: Ecgi
        """
        if ecgi is None:
            raise ValueError("Invalid value for `ecgi`, must not be `None`")  # noqa: E501

        self._ecgi = ecgi

    @property
    def associate_id(self) -> List[AssociateId]:
        """Gets the associate_id of this CaReconfNotification.

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :return: The associate_id of this CaReconfNotification.
        :rtype: List[AssociateId]
        """
        return self._associate_id

    @associate_id.setter
    def associate_id(self, associate_id: List[AssociateId]):
        """Sets the associate_id of this CaReconfNotification.

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :param associate_id: The associate_id of this CaReconfNotification.
        :type associate_id: List[AssociateId]
        """
        if associate_id is not None and len(associate_id) < 0:
            raise ValueError("Invalid value for `associate_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._associate_id = associate_id

    @property
    def secondary_cell_add(self) -> List[SecondaryCellAdd]:
        """Gets the secondary_cell_add of this CaReconfNotification.


        :return: The secondary_cell_add of this CaReconfNotification.
        :rtype: List[SecondaryCellAdd]
        """
        return self._secondary_cell_add

    @secondary_cell_add.setter
    def secondary_cell_add(self, secondary_cell_add: List[SecondaryCellAdd]):
        """Sets the secondary_cell_add of this CaReconfNotification.


        :param secondary_cell_add: The secondary_cell_add of this CaReconfNotification.
        :type secondary_cell_add: List[SecondaryCellAdd]
        """

        self._secondary_cell_add = secondary_cell_add

    @property
    def secondary_cell_remove(self) -> List[SecondaryCellRemove]:
        """Gets the secondary_cell_remove of this CaReconfNotification.


        :return: The secondary_cell_remove of this CaReconfNotification.
        :rtype: List[SecondaryCellRemove]
        """
        return self._secondary_cell_remove

    @secondary_cell_remove.setter
    def secondary_cell_remove(self, secondary_cell_remove: List[SecondaryCellRemove]):
        """Sets the secondary_cell_remove of this CaReconfNotification.


        :param secondary_cell_remove: The secondary_cell_remove of this CaReconfNotification.
        :type secondary_cell_remove: List[SecondaryCellRemove]
        """

        self._secondary_cell_remove = secondary_cell_remove

    @property
    def carrier_aggregation_meas_info(self) -> List[CarrierAggregationMeasInfo1]:
        """Gets the carrier_aggregation_meas_info of this CaReconfNotification.


        :return: The carrier_aggregation_meas_info of this CaReconfNotification.
        :rtype: List[CarrierAggregationMeasInfo1]
        """
        return self._carrier_aggregation_meas_info

    @carrier_aggregation_meas_info.setter
    def carrier_aggregation_meas_info(self, carrier_aggregation_meas_info: List[CarrierAggregationMeasInfo1]):
        """Sets the carrier_aggregation_meas_info of this CaReconfNotification.


        :param carrier_aggregation_meas_info: The carrier_aggregation_meas_info of this CaReconfNotification.
        :type carrier_aggregation_meas_info: List[CarrierAggregationMeasInfo1]
        """

        self._carrier_aggregation_meas_info = carrier_aggregation_meas_info

    @property
    def links(self) -> List[Links]:
        """Gets the links of this CaReconfNotification.

        Links to resources related to this notification.  # noqa: E501

        :return: The links of this CaReconfNotification.
        :rtype: List[Links]
        """
        return self._links

    @links.setter
    def links(self, links: List[Links]):
        """Sets the links of this CaReconfNotification.

        Links to resources related to this notification.  # noqa: E501

        :param links: The links of this CaReconfNotification.
        :type links: List[Links]
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def subscription(self) -> List[LinkType]:
        """Gets the subscription of this CaReconfNotification.

        A link to the related subscription.  # noqa: E501

        :return: The subscription of this CaReconfNotification.
        :rtype: List[LinkType]
        """
        return self._subscription

    @subscription.setter
    def subscription(self, subscription: List[LinkType]):
        """Sets the subscription of this CaReconfNotification.

        A link to the related subscription.  # noqa: E501

        :param subscription: The subscription of this CaReconfNotification.
        :type subscription: List[LinkType]
        """
        if subscription is None:
            raise ValueError("Invalid value for `subscription`, must not be `None`")  # noqa: E501

        self._subscription = subscription
