from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CarrierAggregationMeasInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cell_id_srv=None, rsrp_srv=None, rsrp_srv_ex=None, rsrq_srv=None, rsrq_srv_ex=None, sinr_srv=None, cell_id_nei=None, rsrp_nei=None, rsrp_nei_ex=None, rsrq_nei=None, rsrq_nei_ex=None, sinr_nei=None):  # noqa: E501
        """CarrierAggregationMeasInfo - a model defined in OpenAPI

        :param cell_id_srv: The cell_id_srv of this CarrierAggregationMeasInfo.  # noqa: E501
        :type cell_id_srv: str
        :param rsrp_srv: The rsrp_srv of this CarrierAggregationMeasInfo.  # noqa: E501
        :type rsrp_srv: int
        :param rsrp_srv_ex: The rsrp_srv_ex of this CarrierAggregationMeasInfo.  # noqa: E501
        :type rsrp_srv_ex: int
        :param rsrq_srv: The rsrq_srv of this CarrierAggregationMeasInfo.  # noqa: E501
        :type rsrq_srv: int
        :param rsrq_srv_ex: The rsrq_srv_ex of this CarrierAggregationMeasInfo.  # noqa: E501
        :type rsrq_srv_ex: int
        :param sinr_srv: The sinr_srv of this CarrierAggregationMeasInfo.  # noqa: E501
        :type sinr_srv: int
        :param cell_id_nei: The cell_id_nei of this CarrierAggregationMeasInfo.  # noqa: E501
        :type cell_id_nei: str
        :param rsrp_nei: The rsrp_nei of this CarrierAggregationMeasInfo.  # noqa: E501
        :type rsrp_nei: int
        :param rsrp_nei_ex: The rsrp_nei_ex of this CarrierAggregationMeasInfo.  # noqa: E501
        :type rsrp_nei_ex: int
        :param rsrq_nei: The rsrq_nei of this CarrierAggregationMeasInfo.  # noqa: E501
        :type rsrq_nei: int
        :param rsrq_nei_ex: The rsrq_nei_ex of this CarrierAggregationMeasInfo.  # noqa: E501
        :type rsrq_nei_ex: int
        :param sinr_nei: The sinr_nei of this CarrierAggregationMeasInfo.  # noqa: E501
        :type sinr_nei: int
        """
        self.openapi_types = {
            'cell_id_srv': str,
            'rsrp_srv': int,
            'rsrp_srv_ex': int,
            'rsrq_srv': int,
            'rsrq_srv_ex': int,
            'sinr_srv': int,
            'cell_id_nei': str,
            'rsrp_nei': int,
            'rsrp_nei_ex': int,
            'rsrq_nei': int,
            'rsrq_nei_ex': int,
            'sinr_nei': int
        }

        self.attribute_map = {
            'cell_id_srv': 'cellIdSrv',
            'rsrp_srv': 'rsrpSrv',
            'rsrp_srv_ex': 'rsrpSrvEx',
            'rsrq_srv': 'rsrqSrv',
            'rsrq_srv_ex': 'rsrqSrvEx',
            'sinr_srv': 'sinrSrv',
            'cell_id_nei': 'cellIdNei',
            'rsrp_nei': 'rsrpNei',
            'rsrp_nei_ex': 'rsrpNeiEx',
            'rsrq_nei': 'rsrqNei',
            'rsrq_nei_ex': 'rsrqNeiEx',
            'sinr_nei': 'sinrNei'
        }

        self._cell_id_srv = cell_id_srv
        self._rsrp_srv = rsrp_srv
        self._rsrp_srv_ex = rsrp_srv_ex
        self._rsrq_srv = rsrq_srv
        self._rsrq_srv_ex = rsrq_srv_ex
        self._sinr_srv = sinr_srv
        self._cell_id_nei = cell_id_nei
        self._rsrp_nei = rsrp_nei
        self._rsrp_nei_ex = rsrp_nei_ex
        self._rsrq_nei = rsrq_nei
        self._rsrq_nei_ex = rsrq_nei_ex
        self._sinr_nei = sinr_nei

    @classmethod
    def from_dict(cls, dikt) -> 'CarrierAggregationMeasInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CarrierAggregationMeasInfo of this CarrierAggregationMeasInfo.  # noqa: E501
        :rtype: CarrierAggregationMeasInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cell_id_srv(self) -> str:
        """Gets the cell_id_srv of this CarrierAggregationMeasInfo.

        E-UTRAN Cell Identity of a Secondary serving Cell (SCell), as defined in ETSI TS 136 331 [i.7].  # noqa: E501

        :return: The cell_id_srv of this CarrierAggregationMeasInfo.
        :rtype: str
        """
        return self._cell_id_srv

    @cell_id_srv.setter
    def cell_id_srv(self, cell_id_srv: str):
        """Sets the cell_id_srv of this CarrierAggregationMeasInfo.

        E-UTRAN Cell Identity of a Secondary serving Cell (SCell), as defined in ETSI TS 136 331 [i.7].  # noqa: E501

        :param cell_id_srv: The cell_id_srv of this CarrierAggregationMeasInfo.
        :type cell_id_srv: str
        """
        if cell_id_srv is None:
            raise ValueError("Invalid value for `cell_id_srv`, must not be `None`")  # noqa: E501

        self._cell_id_srv = cell_id_srv

    @property
    def rsrp_srv(self) -> int:
        """Gets the rsrp_srv of this CarrierAggregationMeasInfo.

        Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :return: The rsrp_srv of this CarrierAggregationMeasInfo.
        :rtype: int
        """
        return self._rsrp_srv

    @rsrp_srv.setter
    def rsrp_srv(self, rsrp_srv: int):
        """Sets the rsrp_srv of this CarrierAggregationMeasInfo.

        Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :param rsrp_srv: The rsrp_srv of this CarrierAggregationMeasInfo.
        :type rsrp_srv: int
        """

        self._rsrp_srv = rsrp_srv

    @property
    def rsrp_srv_ex(self) -> int:
        """Gets the rsrp_srv_ex of this CarrierAggregationMeasInfo.

        Extended Reference Signal Received Power, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :return: The rsrp_srv_ex of this CarrierAggregationMeasInfo.
        :rtype: int
        """
        return self._rsrp_srv_ex

    @rsrp_srv_ex.setter
    def rsrp_srv_ex(self, rsrp_srv_ex: int):
        """Sets the rsrp_srv_ex of this CarrierAggregationMeasInfo.

        Extended Reference Signal Received Power, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :param rsrp_srv_ex: The rsrp_srv_ex of this CarrierAggregationMeasInfo.
        :type rsrp_srv_ex: int
        """

        self._rsrp_srv_ex = rsrp_srv_ex

    @property
    def rsrq_srv(self) -> int:
        """Gets the rsrq_srv of this CarrierAggregationMeasInfo.

        Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :return: The rsrq_srv of this CarrierAggregationMeasInfo.
        :rtype: int
        """
        return self._rsrq_srv

    @rsrq_srv.setter
    def rsrq_srv(self, rsrq_srv: int):
        """Sets the rsrq_srv of this CarrierAggregationMeasInfo.

        Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :param rsrq_srv: The rsrq_srv of this CarrierAggregationMeasInfo.
        :type rsrq_srv: int
        """

        self._rsrq_srv = rsrq_srv

    @property
    def rsrq_srv_ex(self) -> int:
        """Gets the rsrq_srv_ex of this CarrierAggregationMeasInfo.

        Extended Reference Signal Received Quality, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :return: The rsrq_srv_ex of this CarrierAggregationMeasInfo.
        :rtype: int
        """
        return self._rsrq_srv_ex

    @rsrq_srv_ex.setter
    def rsrq_srv_ex(self, rsrq_srv_ex: int):
        """Sets the rsrq_srv_ex of this CarrierAggregationMeasInfo.

        Extended Reference Signal Received Quality, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :param rsrq_srv_ex: The rsrq_srv_ex of this CarrierAggregationMeasInfo.
        :type rsrq_srv_ex: int
        """

        self._rsrq_srv_ex = rsrq_srv_ex

    @property
    def sinr_srv(self) -> int:
        """Gets the sinr_srv of this CarrierAggregationMeasInfo.

        Reference Signal \"Signal to Interference plus Noise Ratio\", with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :return: The sinr_srv of this CarrierAggregationMeasInfo.
        :rtype: int
        """
        return self._sinr_srv

    @sinr_srv.setter
    def sinr_srv(self, sinr_srv: int):
        """Sets the sinr_srv of this CarrierAggregationMeasInfo.

        Reference Signal \"Signal to Interference plus Noise Ratio\", with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :param sinr_srv: The sinr_srv of this CarrierAggregationMeasInfo.
        :type sinr_srv: int
        """

        self._sinr_srv = sinr_srv

    @property
    def cell_id_nei(self) -> str:
        """Gets the cell_id_nei of this CarrierAggregationMeasInfo.

        E-UTRAN Cell Identity of the best neighbouring cell (NCell) associated with the SCell, as defined in ETSI TS 136 331 [i.7].  # noqa: E501

        :return: The cell_id_nei of this CarrierAggregationMeasInfo.
        :rtype: str
        """
        return self._cell_id_nei

    @cell_id_nei.setter
    def cell_id_nei(self, cell_id_nei: str):
        """Sets the cell_id_nei of this CarrierAggregationMeasInfo.

        E-UTRAN Cell Identity of the best neighbouring cell (NCell) associated with the SCell, as defined in ETSI TS 136 331 [i.7].  # noqa: E501

        :param cell_id_nei: The cell_id_nei of this CarrierAggregationMeasInfo.
        :type cell_id_nei: str
        """

        self._cell_id_nei = cell_id_nei

    @property
    def rsrp_nei(self) -> int:
        """Gets the rsrp_nei of this CarrierAggregationMeasInfo.

        Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :return: The rsrp_nei of this CarrierAggregationMeasInfo.
        :rtype: int
        """
        return self._rsrp_nei

    @rsrp_nei.setter
    def rsrp_nei(self, rsrp_nei: int):
        """Sets the rsrp_nei of this CarrierAggregationMeasInfo.

        Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :param rsrp_nei: The rsrp_nei of this CarrierAggregationMeasInfo.
        :type rsrp_nei: int
        """

        self._rsrp_nei = rsrp_nei

    @property
    def rsrp_nei_ex(self) -> int:
        """Gets the rsrp_nei_ex of this CarrierAggregationMeasInfo.

        Extended Reference Signal Received Power, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :return: The rsrp_nei_ex of this CarrierAggregationMeasInfo.
        :rtype: int
        """
        return self._rsrp_nei_ex

    @rsrp_nei_ex.setter
    def rsrp_nei_ex(self, rsrp_nei_ex: int):
        """Sets the rsrp_nei_ex of this CarrierAggregationMeasInfo.

        Extended Reference Signal Received Power, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :param rsrp_nei_ex: The rsrp_nei_ex of this CarrierAggregationMeasInfo.
        :type rsrp_nei_ex: int
        """

        self._rsrp_nei_ex = rsrp_nei_ex

    @property
    def rsrq_nei(self) -> int:
        """Gets the rsrq_nei of this CarrierAggregationMeasInfo.

        Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :return: The rsrq_nei of this CarrierAggregationMeasInfo.
        :rtype: int
        """
        return self._rsrq_nei

    @rsrq_nei.setter
    def rsrq_nei(self, rsrq_nei: int):
        """Sets the rsrq_nei of this CarrierAggregationMeasInfo.

        Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :param rsrq_nei: The rsrq_nei of this CarrierAggregationMeasInfo.
        :type rsrq_nei: int
        """

        self._rsrq_nei = rsrq_nei

    @property
    def rsrq_nei_ex(self) -> int:
        """Gets the rsrq_nei_ex of this CarrierAggregationMeasInfo.

        Extended Reference Signal Received Quality, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :return: The rsrq_nei_ex of this CarrierAggregationMeasInfo.
        :rtype: int
        """
        return self._rsrq_nei_ex

    @rsrq_nei_ex.setter
    def rsrq_nei_ex(self, rsrq_nei_ex: int):
        """Sets the rsrq_nei_ex of this CarrierAggregationMeasInfo.

        Extended Reference Signal Received Quality, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :param rsrq_nei_ex: The rsrq_nei_ex of this CarrierAggregationMeasInfo.
        :type rsrq_nei_ex: int
        """

        self._rsrq_nei_ex = rsrq_nei_ex

    @property
    def sinr_nei(self) -> int:
        """Gets the sinr_nei of this CarrierAggregationMeasInfo.

        Reference Signal \"Signal to Interference plus Noise Ratio\", with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :return: The sinr_nei of this CarrierAggregationMeasInfo.
        :rtype: int
        """
        return self._sinr_nei

    @sinr_nei.setter
    def sinr_nei(self, sinr_nei: int):
        """Sets the sinr_nei of this CarrierAggregationMeasInfo.

        Reference Signal \"Signal to Interference plus Noise Ratio\", with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :param sinr_nei: The sinr_nei of this CarrierAggregationMeasInfo.
        :type sinr_nei: int
        """

        self._sinr_nei = sinr_nei
