from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.ecgi import Ecgi
from openapi_server.models.ue_info import UeInfo
from openapi_server import util

from openapi_server.models.ecgi import Ecgi  # noqa: E501
from openapi_server.models.ue_info import UeInfo  # noqa: E501

class CellUserInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ecgi=None, ue_info=None):  # noqa: E501
        """CellUserInfo - a model defined in OpenAPI

        :param ecgi: The ecgi of this CellUserInfo.  # noqa: E501
        :type ecgi: Ecgi
        :param ue_info: The ue_info of this CellUserInfo.  # noqa: E501
        :type ue_info: List[UeInfo]
        """
        self.openapi_types = {
            'ecgi': Ecgi,
            'ue_info': List[UeInfo]
        }

        self.attribute_map = {
            'ecgi': 'ecgi',
            'ue_info': 'ueInfo'
        }

        self._ecgi = ecgi
        self._ue_info = ue_info

    @classmethod
    def from_dict(cls, dikt) -> 'CellUserInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CellUserInfo of this CellUserInfo.  # noqa: E501
        :rtype: CellUserInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ecgi(self) -> Ecgi:
        """Gets the ecgi of this CellUserInfo.

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :return: The ecgi of this CellUserInfo.
        :rtype: Ecgi
        """
        return self._ecgi

    @ecgi.setter
    def ecgi(self, ecgi: Ecgi):
        """Sets the ecgi of this CellUserInfo.

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :param ecgi: The ecgi of this CellUserInfo.
        :type ecgi: Ecgi
        """
        if ecgi is None:
            raise ValueError("Invalid value for `ecgi`, must not be `None`")  # noqa: E501

        self._ecgi = ecgi

    @property
    def ue_info(self) -> List[UeInfo]:
        """Gets the ue_info of this CellUserInfo.


        :return: The ue_info of this CellUserInfo.
        :rtype: List[UeInfo]
        """
        return self._ue_info

    @ue_info.setter
    def ue_info(self, ue_info: List[UeInfo]):
        """Sets the ue_info of this CellUserInfo.


        :param ue_info: The ue_info of this CellUserInfo.
        :type ue_info: List[UeInfo]
        """
        if ue_info is None:
            raise ValueError("Invalid value for `ue_info`, must not be `None`")  # noqa: E501

        self._ue_info = ue_info
