from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.erab_qos_parameters import ErabQosParameters
from openapi_server import util

from openapi_server.models.erab_qos_parameters import ErabQosParameters  # noqa: E501

class ErabInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, erab_id=None, erab_qos_parameters=None):  # noqa: E501
        """ErabInfo - a model defined in OpenAPI

        :param erab_id: The erab_id of this ErabInfo.  # noqa: E501
        :type erab_id: int
        :param erab_qos_parameters: The erab_qos_parameters of this ErabInfo.  # noqa: E501
        :type erab_qos_parameters: ErabQosParameters
        """
        self.openapi_types = {
            'erab_id': int,
            'erab_qos_parameters': ErabQosParameters
        }

        self.attribute_map = {
            'erab_id': 'erabId',
            'erab_qos_parameters': 'erabQosParameters'
        }

        self._erab_id = erab_id
        self._erab_qos_parameters = erab_qos_parameters

    @classmethod
    def from_dict(cls, dikt) -> 'ErabInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErabInfo of this ErabInfo.  # noqa: E501
        :rtype: ErabInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def erab_id(self) -> int:
        """Gets the erab_id of this ErabInfo.

        The attribute that uniquely identifies a Radio Access bearer for specific UE as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :return: The erab_id of this ErabInfo.
        :rtype: int
        """
        return self._erab_id

    @erab_id.setter
    def erab_id(self, erab_id: int):
        """Sets the erab_id of this ErabInfo.

        The attribute that uniquely identifies a Radio Access bearer for specific UE as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :param erab_id: The erab_id of this ErabInfo.
        :type erab_id: int
        """
        if erab_id is None:
            raise ValueError("Invalid value for `erab_id`, must not be `None`")  # noqa: E501

        self._erab_id = erab_id

    @property
    def erab_qos_parameters(self) -> ErabQosParameters:
        """Gets the erab_qos_parameters of this ErabInfo.


        :return: The erab_qos_parameters of this ErabInfo.
        :rtype: ErabQosParameters
        """
        return self._erab_qos_parameters

    @erab_qos_parameters.setter
    def erab_qos_parameters(self, erab_qos_parameters: ErabQosParameters):
        """Sets the erab_qos_parameters of this ErabInfo.


        :param erab_qos_parameters: The erab_qos_parameters of this ErabInfo.
        :type erab_qos_parameters: ErabQosParameters
        """

        self._erab_qos_parameters = erab_qos_parameters
