from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.associate_id import AssociateId
from openapi_server.models.ecgi import Ecgi
from openapi_server import util

from openapi_server.models.associate_id import AssociateId  # noqa: E501
from openapi_server.models.ecgi import Ecgi  # noqa: E501

class FilterCriteriaAssocHo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, app_instance_id=None, associate_id=None, ecgi=None, ho_status=None):  # noqa: E501
        """FilterCriteriaAssocHo - a model defined in OpenAPI

        :param app_instance_id: The app_instance_id of this FilterCriteriaAssocHo.  # noqa: E501
        :type app_instance_id: str
        :param associate_id: The associate_id of this FilterCriteriaAssocHo.  # noqa: E501
        :type associate_id: List[AssociateId]
        :param ecgi: The ecgi of this FilterCriteriaAssocHo.  # noqa: E501
        :type ecgi: List[Ecgi]
        :param ho_status: The ho_status of this FilterCriteriaAssocHo.  # noqa: E501
        :type ho_status: List[int]
        """
        self.openapi_types = {
            'app_instance_id': str,
            'associate_id': List[AssociateId],
            'ecgi': List[Ecgi],
            'ho_status': List[int]
        }

        self.attribute_map = {
            'app_instance_id': 'appInstanceId',
            'associate_id': 'associateId',
            'ecgi': 'ecgi',
            'ho_status': 'hoStatus'
        }

        self._app_instance_id = app_instance_id
        self._associate_id = associate_id
        self._ecgi = ecgi
        self._ho_status = ho_status

    @classmethod
    def from_dict(cls, dikt) -> 'FilterCriteriaAssocHo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FilterCriteriaAssocHo of this FilterCriteriaAssocHo.  # noqa: E501
        :rtype: FilterCriteriaAssocHo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def app_instance_id(self) -> str:
        """Gets the app_instance_id of this FilterCriteriaAssocHo.

        Unique identifier for the MEC application instance.  # noqa: E501

        :return: The app_instance_id of this FilterCriteriaAssocHo.
        :rtype: str
        """
        return self._app_instance_id

    @app_instance_id.setter
    def app_instance_id(self, app_instance_id: str):
        """Sets the app_instance_id of this FilterCriteriaAssocHo.

        Unique identifier for the MEC application instance.  # noqa: E501

        :param app_instance_id: The app_instance_id of this FilterCriteriaAssocHo.
        :type app_instance_id: str
        """

        self._app_instance_id = app_instance_id

    @property
    def associate_id(self) -> List[AssociateId]:
        """Gets the associate_id of this FilterCriteriaAssocHo.

        0 to N identifiers to associate the information for a specific UE or flow.  # noqa: E501

        :return: The associate_id of this FilterCriteriaAssocHo.
        :rtype: List[AssociateId]
        """
        return self._associate_id

    @associate_id.setter
    def associate_id(self, associate_id: List[AssociateId]):
        """Sets the associate_id of this FilterCriteriaAssocHo.

        0 to N identifiers to associate the information for a specific UE or flow.  # noqa: E501

        :param associate_id: The associate_id of this FilterCriteriaAssocHo.
        :type associate_id: List[AssociateId]
        """
        if associate_id is not None and len(associate_id) < 0:
            raise ValueError("Invalid value for `associate_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._associate_id = associate_id

    @property
    def ecgi(self) -> List[Ecgi]:
        """Gets the ecgi of this FilterCriteriaAssocHo.

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :return: The ecgi of this FilterCriteriaAssocHo.
        :rtype: List[Ecgi]
        """
        return self._ecgi

    @ecgi.setter
    def ecgi(self, ecgi: List[Ecgi]):
        """Sets the ecgi of this FilterCriteriaAssocHo.

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :param ecgi: The ecgi of this FilterCriteriaAssocHo.
        :type ecgi: List[Ecgi]
        """
        if ecgi is not None and len(ecgi) < 0:
            raise ValueError("Invalid value for `ecgi`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._ecgi = ecgi

    @property
    def ho_status(self) -> List[int]:
        """Gets the ho_status of this FilterCriteriaAssocHo.

        In case hoStatus is not included in the subscription request, the default value 3 = COMPLETED shall be used and included in the response: 1 = IN_PREPARATION. 2 = IN_EXECUTION. 3 = COMPLETED. 4 = REJECTED. 5 = CANCELLED.  # noqa: E501

        :return: The ho_status of this FilterCriteriaAssocHo.
        :rtype: List[int]
        """
        return self._ho_status

    @ho_status.setter
    def ho_status(self, ho_status: List[int]):
        """Sets the ho_status of this FilterCriteriaAssocHo.

        In case hoStatus is not included in the subscription request, the default value 3 = COMPLETED shall be used and included in the response: 1 = IN_PREPARATION. 2 = IN_EXECUTION. 3 = COMPLETED. 4 = REJECTED. 5 = CANCELLED.  # noqa: E501

        :param ho_status: The ho_status of this FilterCriteriaAssocHo.
        :type ho_status: List[int]
        """
        if ho_status is not None and len(ho_status) < 0:
            raise ValueError("Invalid value for `ho_status`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._ho_status = ho_status
