from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.associate_id import AssociateId
from openapi_server.models.ca_reconf_notification import CaReconfNotification
from openapi_server.models.carrier_aggregation_meas_info1 import CarrierAggregationMeasInfo1
from openapi_server.models.cell_change_notification import CellChangeNotification
from openapi_server.models.ecgi import Ecgi
from openapi_server.models.erab_qos_parameters2 import ErabQosParameters2
from openapi_server.models.erab_release_info import ErabReleaseInfo
from openapi_server.models.eutra_neigh_cell_meas_info import EutraNeighCellMeasInfo
from openapi_server.models.eutran_neighbour_cell_meas_info import EutranNeighbourCellMeasInfo
from openapi_server.models.link_type import LinkType
from openapi_server.models.links import Links
from openapi_server.models.meas_rep_ue_notification import MeasRepUeNotification
from openapi_server.models.meas_ta_notification import MeasTaNotification
from openapi_server.models.new_radio_meas_info import NewRadioMeasInfo
from openapi_server.models.new_radio_meas_nei_info import NewRadioMeasNeiInfo
from openapi_server.models.nr_meas_rep_ue_notification import NrMeasRepUeNotification
from openapi_server.models.nr_neigh_cell_meas_info import NrNeighCellMeasInfo
from openapi_server.models.rab_est_notification import RabEstNotification
from openapi_server.models.rab_mod_notification import RabModNotification
from openapi_server.models.rab_rel_notification import RabRelNotification
from openapi_server.models.s1_bearer_notification import S1BearerNotification
from openapi_server.models.s1_ue_info1 import S1UeInfo1
from openapi_server.models.secondary_cell_add import SecondaryCellAdd
from openapi_server.models.secondary_cell_remove import SecondaryCellRemove
from openapi_server.models.serv_cell_meas_info import ServCellMeasInfo
from openapi_server.models.temp_ue_id1 import TempUeId1
from openapi_server.models.time_stamp import TimeStamp
from openapi_server.models.trigger import Trigger
from openapi_server.models.trigger_nr import TriggerNr
from openapi_server import util

from openapi_server.models.associate_id import AssociateId  # noqa: E501
from openapi_server.models.ca_reconf_notification import CaReconfNotification  # noqa: E501
from openapi_server.models.carrier_aggregation_meas_info1 import CarrierAggregationMeasInfo1  # noqa: E501
from openapi_server.models.cell_change_notification import CellChangeNotification  # noqa: E501
from openapi_server.models.ecgi import Ecgi  # noqa: E501
from openapi_server.models.erab_qos_parameters2 import ErabQosParameters2  # noqa: E501
from openapi_server.models.erab_release_info import ErabReleaseInfo  # noqa: E501
from openapi_server.models.eutra_neigh_cell_meas_info import EutraNeighCellMeasInfo  # noqa: E501
from openapi_server.models.eutran_neighbour_cell_meas_info import EutranNeighbourCellMeasInfo  # noqa: E501
from openapi_server.models.link_type import LinkType  # noqa: E501
from openapi_server.models.links import Links  # noqa: E501
from openapi_server.models.meas_rep_ue_notification import MeasRepUeNotification  # noqa: E501
from openapi_server.models.meas_ta_notification import MeasTaNotification  # noqa: E501
from openapi_server.models.new_radio_meas_info import NewRadioMeasInfo  # noqa: E501
from openapi_server.models.new_radio_meas_nei_info import NewRadioMeasNeiInfo  # noqa: E501
from openapi_server.models.nr_meas_rep_ue_notification import NrMeasRepUeNotification  # noqa: E501
from openapi_server.models.nr_neigh_cell_meas_info import NrNeighCellMeasInfo  # noqa: E501
from openapi_server.models.rab_est_notification import RabEstNotification  # noqa: E501
from openapi_server.models.rab_mod_notification import RabModNotification  # noqa: E501
from openapi_server.models.rab_rel_notification import RabRelNotification  # noqa: E501
from openapi_server.models.s1_bearer_notification import S1BearerNotification  # noqa: E501
from openapi_server.models.s1_ue_info1 import S1UeInfo1  # noqa: E501
from openapi_server.models.secondary_cell_add import SecondaryCellAdd  # noqa: E501
from openapi_server.models.secondary_cell_remove import SecondaryCellRemove  # noqa: E501
from openapi_server.models.serv_cell_meas_info import ServCellMeasInfo  # noqa: E501
from openapi_server.models.temp_ue_id1 import TempUeId1  # noqa: E501
from openapi_server.models.time_stamp import TimeStamp  # noqa: E501
from openapi_server.models.trigger import Trigger  # noqa: E501
from openapi_server.models.trigger_nr import TriggerNr  # noqa: E501

class InlineNotification(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, notification_type=None, time_stamp=None, associate_id=None, src_ecgi=None, trg_ecgi=None, ho_status=None, temp_ue_id=None, links=None, subscription=None, ecgi=None, erab_id=None, erab_qos_parameters=None, erab_release_info=None, rsrp=None, rsrp_ex=None, rsrq=None, rsrq_ex=None, sinr=None, trigger=None, eutran_neighbour_cell_meas_info=None, carrier_aggregation_meas_info=None, height_ue=None, new_radio_meas_info=None, new_radio_meas_nei_info=None, trigger_nr=None, serv_cell_meas_info=None, nr_neigh_cell_meas_info=None, eutra_neigh_cell_meas_info=None, timing_advance=None, secondary_cell_add=None, secondary_cell_remove=None, s1_event=None, s1_ue_info=None):  # noqa: E501
        """InlineNotification - a model defined in OpenAPI

        :param notification_type: The notification_type of this InlineNotification.  # noqa: E501
        :type notification_type: str
        :param time_stamp: The time_stamp of this InlineNotification.  # noqa: E501
        :type time_stamp: TimeStamp
        :param associate_id: The associate_id of this InlineNotification.  # noqa: E501
        :type associate_id: List[AssociateId]
        :param src_ecgi: The src_ecgi of this InlineNotification.  # noqa: E501
        :type src_ecgi: Ecgi
        :param trg_ecgi: The trg_ecgi of this InlineNotification.  # noqa: E501
        :type trg_ecgi: List[Ecgi]
        :param ho_status: The ho_status of this InlineNotification.  # noqa: E501
        :type ho_status: int
        :param temp_ue_id: The temp_ue_id of this InlineNotification.  # noqa: E501
        :type temp_ue_id: TempUeId1
        :param links: The links of this InlineNotification.  # noqa: E501
        :type links: List[Links]
        :param subscription: The subscription of this InlineNotification.  # noqa: E501
        :type subscription: List[LinkType]
        :param ecgi: The ecgi of this InlineNotification.  # noqa: E501
        :type ecgi: Ecgi
        :param erab_id: The erab_id of this InlineNotification.  # noqa: E501
        :type erab_id: int
        :param erab_qos_parameters: The erab_qos_parameters of this InlineNotification.  # noqa: E501
        :type erab_qos_parameters: ErabQosParameters2
        :param erab_release_info: The erab_release_info of this InlineNotification.  # noqa: E501
        :type erab_release_info: ErabReleaseInfo
        :param rsrp: The rsrp of this InlineNotification.  # noqa: E501
        :type rsrp: int
        :param rsrp_ex: The rsrp_ex of this InlineNotification.  # noqa: E501
        :type rsrp_ex: int
        :param rsrq: The rsrq of this InlineNotification.  # noqa: E501
        :type rsrq: int
        :param rsrq_ex: The rsrq_ex of this InlineNotification.  # noqa: E501
        :type rsrq_ex: int
        :param sinr: The sinr of this InlineNotification.  # noqa: E501
        :type sinr: int
        :param trigger: The trigger of this InlineNotification.  # noqa: E501
        :type trigger: Trigger
        :param eutran_neighbour_cell_meas_info: The eutran_neighbour_cell_meas_info of this InlineNotification.  # noqa: E501
        :type eutran_neighbour_cell_meas_info: List[EutranNeighbourCellMeasInfo]
        :param carrier_aggregation_meas_info: The carrier_aggregation_meas_info of this InlineNotification.  # noqa: E501
        :type carrier_aggregation_meas_info: List[CarrierAggregationMeasInfo1]
        :param height_ue: The height_ue of this InlineNotification.  # noqa: E501
        :type height_ue: int
        :param new_radio_meas_info: The new_radio_meas_info of this InlineNotification.  # noqa: E501
        :type new_radio_meas_info: List[NewRadioMeasInfo]
        :param new_radio_meas_nei_info: The new_radio_meas_nei_info of this InlineNotification.  # noqa: E501
        :type new_radio_meas_nei_info: List[NewRadioMeasNeiInfo]
        :param trigger_nr: The trigger_nr of this InlineNotification.  # noqa: E501
        :type trigger_nr: TriggerNr
        :param serv_cell_meas_info: The serv_cell_meas_info of this InlineNotification.  # noqa: E501
        :type serv_cell_meas_info: List[ServCellMeasInfo]
        :param nr_neigh_cell_meas_info: The nr_neigh_cell_meas_info of this InlineNotification.  # noqa: E501
        :type nr_neigh_cell_meas_info: List[NrNeighCellMeasInfo]
        :param eutra_neigh_cell_meas_info: The eutra_neigh_cell_meas_info of this InlineNotification.  # noqa: E501
        :type eutra_neigh_cell_meas_info: List[EutraNeighCellMeasInfo]
        :param timing_advance: The timing_advance of this InlineNotification.  # noqa: E501
        :type timing_advance: int
        :param secondary_cell_add: The secondary_cell_add of this InlineNotification.  # noqa: E501
        :type secondary_cell_add: List[SecondaryCellAdd]
        :param secondary_cell_remove: The secondary_cell_remove of this InlineNotification.  # noqa: E501
        :type secondary_cell_remove: List[SecondaryCellRemove]
        :param s1_event: The s1_event of this InlineNotification.  # noqa: E501
        :type s1_event: str
        :param s1_ue_info: The s1_ue_info of this InlineNotification.  # noqa: E501
        :type s1_ue_info: S1UeInfo1
        """
        self.openapi_types = {
            'notification_type': str,
            'time_stamp': TimeStamp,
            'associate_id': List[AssociateId],
            'src_ecgi': Ecgi,
            'trg_ecgi': List[Ecgi],
            'ho_status': int,
            'temp_ue_id': TempUeId1,
            'links': List[Links],
            'subscription': List[LinkType],
            'ecgi': Ecgi,
            'erab_id': int,
            'erab_qos_parameters': ErabQosParameters2,
            'erab_release_info': ErabReleaseInfo,
            'rsrp': int,
            'rsrp_ex': int,
            'rsrq': int,
            'rsrq_ex': int,
            'sinr': int,
            'trigger': Trigger,
            'eutran_neighbour_cell_meas_info': List[EutranNeighbourCellMeasInfo],
            'carrier_aggregation_meas_info': List[CarrierAggregationMeasInfo1],
            'height_ue': int,
            'new_radio_meas_info': List[NewRadioMeasInfo],
            'new_radio_meas_nei_info': List[NewRadioMeasNeiInfo],
            'trigger_nr': TriggerNr,
            'serv_cell_meas_info': List[ServCellMeasInfo],
            'nr_neigh_cell_meas_info': List[NrNeighCellMeasInfo],
            'eutra_neigh_cell_meas_info': List[EutraNeighCellMeasInfo],
            'timing_advance': int,
            'secondary_cell_add': List[SecondaryCellAdd],
            'secondary_cell_remove': List[SecondaryCellRemove],
            's1_event': str,
            's1_ue_info': S1UeInfo1
        }

        self.attribute_map = {
            'notification_type': 'notificationType',
            'time_stamp': 'timeStamp',
            'associate_id': 'associateId',
            'src_ecgi': 'srcEcgi',
            'trg_ecgi': 'trgEcgi',
            'ho_status': 'hoStatus',
            'temp_ue_id': 'tempUeId',
            'links': '_links',
            'subscription': 'subscription',
            'ecgi': 'ecgi',
            'erab_id': 'erabId',
            'erab_qos_parameters': 'erabQosParameters',
            'erab_release_info': 'erabReleaseInfo',
            'rsrp': 'rsrp',
            'rsrp_ex': 'rsrpEx',
            'rsrq': 'rsrq',
            'rsrq_ex': 'rsrqEx',
            'sinr': 'sinr',
            'trigger': 'trigger',
            'eutran_neighbour_cell_meas_info': 'eutranNeighbourCellMeasInfo',
            'carrier_aggregation_meas_info': 'carrierAggregationMeasInfo',
            'height_ue': 'heightUe',
            'new_radio_meas_info': 'newRadioMeasInfo',
            'new_radio_meas_nei_info': 'newRadioMeasNeiInfo',
            'trigger_nr': 'triggerNr',
            'serv_cell_meas_info': 'servCellMeasInfo',
            'nr_neigh_cell_meas_info': 'nrNeighCellMeasInfo',
            'eutra_neigh_cell_meas_info': 'eutraNeighCellMeasInfo',
            'timing_advance': 'timingAdvance',
            'secondary_cell_add': 'secondaryCellAdd',
            'secondary_cell_remove': 'secondaryCellRemove',
            's1_event': 's1Event',
            's1_ue_info': 's1UeInfo'
        }

        self._notification_type = notification_type
        self._time_stamp = time_stamp
        self._associate_id = associate_id
        self._src_ecgi = src_ecgi
        self._trg_ecgi = trg_ecgi
        self._ho_status = ho_status
        self._temp_ue_id = temp_ue_id
        self._links = links
        self._subscription = subscription
        self._ecgi = ecgi
        self._erab_id = erab_id
        self._erab_qos_parameters = erab_qos_parameters
        self._erab_release_info = erab_release_info
        self._rsrp = rsrp
        self._rsrp_ex = rsrp_ex
        self._rsrq = rsrq
        self._rsrq_ex = rsrq_ex
        self._sinr = sinr
        self._trigger = trigger
        self._eutran_neighbour_cell_meas_info = eutran_neighbour_cell_meas_info
        self._carrier_aggregation_meas_info = carrier_aggregation_meas_info
        self._height_ue = height_ue
        self._new_radio_meas_info = new_radio_meas_info
        self._new_radio_meas_nei_info = new_radio_meas_nei_info
        self._trigger_nr = trigger_nr
        self._serv_cell_meas_info = serv_cell_meas_info
        self._nr_neigh_cell_meas_info = nr_neigh_cell_meas_info
        self._eutra_neigh_cell_meas_info = eutra_neigh_cell_meas_info
        self._timing_advance = timing_advance
        self._secondary_cell_add = secondary_cell_add
        self._secondary_cell_remove = secondary_cell_remove
        self._s1_event = s1_event
        self._s1_ue_info = s1_ue_info

    @classmethod
    def from_dict(cls, dikt) -> 'InlineNotification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InlineNotification of this InlineNotification.  # noqa: E501
        :rtype: InlineNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_type(self) -> str:
        """Gets the notification_type of this InlineNotification.

        Shall be set to \"S1BearerNotification\".  # noqa: E501

        :return: The notification_type of this InlineNotification.
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type: str):
        """Sets the notification_type of this InlineNotification.

        Shall be set to \"S1BearerNotification\".  # noqa: E501

        :param notification_type: The notification_type of this InlineNotification.
        :type notification_type: str
        """
        if notification_type is None:
            raise ValueError("Invalid value for `notification_type`, must not be `None`")  # noqa: E501

        self._notification_type = notification_type

    @property
    def time_stamp(self) -> TimeStamp:
        """Gets the time_stamp of this InlineNotification.

        Time stamp.  # noqa: E501

        :return: The time_stamp of this InlineNotification.
        :rtype: TimeStamp
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: TimeStamp):
        """Sets the time_stamp of this InlineNotification.

        Time stamp.  # noqa: E501

        :param time_stamp: The time_stamp of this InlineNotification.
        :type time_stamp: TimeStamp
        """

        self._time_stamp = time_stamp

    @property
    def associate_id(self) -> List[AssociateId]:
        """Gets the associate_id of this InlineNotification.

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :return: The associate_id of this InlineNotification.
        :rtype: List[AssociateId]
        """
        return self._associate_id

    @associate_id.setter
    def associate_id(self, associate_id: List[AssociateId]):
        """Sets the associate_id of this InlineNotification.

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :param associate_id: The associate_id of this InlineNotification.
        :type associate_id: List[AssociateId]
        """
        if associate_id is not None and len(associate_id) < 0:
            raise ValueError("Invalid value for `associate_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._associate_id = associate_id

    @property
    def src_ecgi(self) -> Ecgi:
        """Gets the src_ecgi of this InlineNotification.

        E-UTRAN Cell Global Identifier of the source cell.  # noqa: E501

        :return: The src_ecgi of this InlineNotification.
        :rtype: Ecgi
        """
        return self._src_ecgi

    @src_ecgi.setter
    def src_ecgi(self, src_ecgi: Ecgi):
        """Sets the src_ecgi of this InlineNotification.

        E-UTRAN Cell Global Identifier of the source cell.  # noqa: E501

        :param src_ecgi: The src_ecgi of this InlineNotification.
        :type src_ecgi: Ecgi
        """
        if src_ecgi is None:
            raise ValueError("Invalid value for `src_ecgi`, must not be `None`")  # noqa: E501

        self._src_ecgi = src_ecgi

    @property
    def trg_ecgi(self) -> List[Ecgi]:
        """Gets the trg_ecgi of this InlineNotification.

        E-UTRAN Cell Global Identifier of the target cell. See note.  # noqa: E501

        :return: The trg_ecgi of this InlineNotification.
        :rtype: List[Ecgi]
        """
        return self._trg_ecgi

    @trg_ecgi.setter
    def trg_ecgi(self, trg_ecgi: List[Ecgi]):
        """Sets the trg_ecgi of this InlineNotification.

        E-UTRAN Cell Global Identifier of the target cell. See note.  # noqa: E501

        :param trg_ecgi: The trg_ecgi of this InlineNotification.
        :type trg_ecgi: List[Ecgi]
        """
        if trg_ecgi is None:
            raise ValueError("Invalid value for `trg_ecgi`, must not be `None`")  # noqa: E501
        if trg_ecgi is not None and len(trg_ecgi) < 1:
            raise ValueError("Invalid value for `trg_ecgi`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._trg_ecgi = trg_ecgi

    @property
    def ho_status(self) -> int:
        """Gets the ho_status of this InlineNotification.

        Indicate the status of the UE handover procedure. Values are defined as following: 1 = IN_PREPARATION. 2 = IN_EXECUTION. 3 = COMPLETED. 4 = REJECTED. 5 = CANCELLED.  # noqa: E501

        :return: The ho_status of this InlineNotification.
        :rtype: int
        """
        return self._ho_status

    @ho_status.setter
    def ho_status(self, ho_status: int):
        """Sets the ho_status of this InlineNotification.

        Indicate the status of the UE handover procedure. Values are defined as following: 1 = IN_PREPARATION. 2 = IN_EXECUTION. 3 = COMPLETED. 4 = REJECTED. 5 = CANCELLED.  # noqa: E501

        :param ho_status: The ho_status of this InlineNotification.
        :type ho_status: int
        """
        allowed_values = [1, 2, 3, 4, 5]  # noqa: E501
        if ho_status not in allowed_values:
            raise ValueError(
                "Invalid value for `ho_status` ({0}), must be one of {1}"
                .format(ho_status, allowed_values)
            )

        self._ho_status = ho_status

    @property
    def temp_ue_id(self) -> TempUeId1:
        """Gets the temp_ue_id of this InlineNotification.


        :return: The temp_ue_id of this InlineNotification.
        :rtype: TempUeId1
        """
        return self._temp_ue_id

    @temp_ue_id.setter
    def temp_ue_id(self, temp_ue_id: TempUeId1):
        """Sets the temp_ue_id of this InlineNotification.


        :param temp_ue_id: The temp_ue_id of this InlineNotification.
        :type temp_ue_id: TempUeId1
        """

        self._temp_ue_id = temp_ue_id

    @property
    def links(self) -> List[Links]:
        """Gets the links of this InlineNotification.

        Links to resources related to this notification.  # noqa: E501

        :return: The links of this InlineNotification.
        :rtype: List[Links]
        """
        return self._links

    @links.setter
    def links(self, links: List[Links]):
        """Sets the links of this InlineNotification.

        Links to resources related to this notification.  # noqa: E501

        :param links: The links of this InlineNotification.
        :type links: List[Links]
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def subscription(self) -> List[LinkType]:
        """Gets the subscription of this InlineNotification.

        A link to the related subscription.  # noqa: E501

        :return: The subscription of this InlineNotification.
        :rtype: List[LinkType]
        """
        return self._subscription

    @subscription.setter
    def subscription(self, subscription: List[LinkType]):
        """Sets the subscription of this InlineNotification.

        A link to the related subscription.  # noqa: E501

        :param subscription: The subscription of this InlineNotification.
        :type subscription: List[LinkType]
        """
        if subscription is None:
            raise ValueError("Invalid value for `subscription`, must not be `None`")  # noqa: E501

        self._subscription = subscription

    @property
    def ecgi(self) -> Ecgi:
        """Gets the ecgi of this InlineNotification.

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :return: The ecgi of this InlineNotification.
        :rtype: Ecgi
        """
        return self._ecgi

    @ecgi.setter
    def ecgi(self, ecgi: Ecgi):
        """Sets the ecgi of this InlineNotification.

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :param ecgi: The ecgi of this InlineNotification.
        :type ecgi: Ecgi
        """
        if ecgi is None:
            raise ValueError("Invalid value for `ecgi`, must not be `None`")  # noqa: E501

        self._ecgi = ecgi

    @property
    def erab_id(self) -> int:
        """Gets the erab_id of this InlineNotification.

        The attribute that uniquely identifies a Radio Access bearer for specific UE as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :return: The erab_id of this InlineNotification.
        :rtype: int
        """
        return self._erab_id

    @erab_id.setter
    def erab_id(self, erab_id: int):
        """Sets the erab_id of this InlineNotification.

        The attribute that uniquely identifies a Radio Access bearer for specific UE as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :param erab_id: The erab_id of this InlineNotification.
        :type erab_id: int
        """
        if erab_id is None:
            raise ValueError("Invalid value for `erab_id`, must not be `None`")  # noqa: E501

        self._erab_id = erab_id

    @property
    def erab_qos_parameters(self) -> ErabQosParameters2:
        """Gets the erab_qos_parameters of this InlineNotification.


        :return: The erab_qos_parameters of this InlineNotification.
        :rtype: ErabQosParameters2
        """
        return self._erab_qos_parameters

    @erab_qos_parameters.setter
    def erab_qos_parameters(self, erab_qos_parameters: ErabQosParameters2):
        """Sets the erab_qos_parameters of this InlineNotification.


        :param erab_qos_parameters: The erab_qos_parameters of this InlineNotification.
        :type erab_qos_parameters: ErabQosParameters2
        """

        self._erab_qos_parameters = erab_qos_parameters

    @property
    def erab_release_info(self) -> ErabReleaseInfo:
        """Gets the erab_release_info of this InlineNotification.


        :return: The erab_release_info of this InlineNotification.
        :rtype: ErabReleaseInfo
        """
        return self._erab_release_info

    @erab_release_info.setter
    def erab_release_info(self, erab_release_info: ErabReleaseInfo):
        """Sets the erab_release_info of this InlineNotification.


        :param erab_release_info: The erab_release_info of this InlineNotification.
        :type erab_release_info: ErabReleaseInfo
        """
        if erab_release_info is None:
            raise ValueError("Invalid value for `erab_release_info`, must not be `None`")  # noqa: E501

        self._erab_release_info = erab_release_info

    @property
    def rsrp(self) -> int:
        """Gets the rsrp of this InlineNotification.

        Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :return: The rsrp of this InlineNotification.
        :rtype: int
        """
        return self._rsrp

    @rsrp.setter
    def rsrp(self, rsrp: int):
        """Sets the rsrp of this InlineNotification.

        Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :param rsrp: The rsrp of this InlineNotification.
        :type rsrp: int
        """
        if rsrp is None:
            raise ValueError("Invalid value for `rsrp`, must not be `None`")  # noqa: E501

        self._rsrp = rsrp

    @property
    def rsrp_ex(self) -> int:
        """Gets the rsrp_ex of this InlineNotification.

        Extended Reference Signal Received Power, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :return: The rsrp_ex of this InlineNotification.
        :rtype: int
        """
        return self._rsrp_ex

    @rsrp_ex.setter
    def rsrp_ex(self, rsrp_ex: int):
        """Sets the rsrp_ex of this InlineNotification.

        Extended Reference Signal Received Power, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :param rsrp_ex: The rsrp_ex of this InlineNotification.
        :type rsrp_ex: int
        """

        self._rsrp_ex = rsrp_ex

    @property
    def rsrq(self) -> int:
        """Gets the rsrq of this InlineNotification.

        Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :return: The rsrq of this InlineNotification.
        :rtype: int
        """
        return self._rsrq

    @rsrq.setter
    def rsrq(self, rsrq: int):
        """Sets the rsrq of this InlineNotification.

        Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :param rsrq: The rsrq of this InlineNotification.
        :type rsrq: int
        """
        if rsrq is None:
            raise ValueError("Invalid value for `rsrq`, must not be `None`")  # noqa: E501

        self._rsrq = rsrq

    @property
    def rsrq_ex(self) -> int:
        """Gets the rsrq_ex of this InlineNotification.

        Extended Reference Signal Received Quality, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :return: The rsrq_ex of this InlineNotification.
        :rtype: int
        """
        return self._rsrq_ex

    @rsrq_ex.setter
    def rsrq_ex(self, rsrq_ex: int):
        """Sets the rsrq_ex of this InlineNotification.

        Extended Reference Signal Received Quality, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :param rsrq_ex: The rsrq_ex of this InlineNotification.
        :type rsrq_ex: int
        """

        self._rsrq_ex = rsrq_ex

    @property
    def sinr(self) -> int:
        """Gets the sinr of this InlineNotification.

        Reference Signal \"Signal to Interference plus Noise Ratio\", with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :return: The sinr of this InlineNotification.
        :rtype: int
        """
        return self._sinr

    @sinr.setter
    def sinr(self, sinr: int):
        """Sets the sinr of this InlineNotification.

        Reference Signal \"Signal to Interference plus Noise Ratio\", with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :param sinr: The sinr of this InlineNotification.
        :type sinr: int
        """

        self._sinr = sinr

    @property
    def trigger(self) -> Trigger:
        """Gets the trigger of this InlineNotification.

        Corresponds to a specific E-UTRAN UE Measurement Report trigger.  # noqa: E501

        :return: The trigger of this InlineNotification.
        :rtype: Trigger
        """
        return self._trigger

    @trigger.setter
    def trigger(self, trigger: Trigger):
        """Sets the trigger of this InlineNotification.

        Corresponds to a specific E-UTRAN UE Measurement Report trigger.  # noqa: E501

        :param trigger: The trigger of this InlineNotification.
        :type trigger: Trigger
        """
        if trigger is None:
            raise ValueError("Invalid value for `trigger`, must not be `None`")  # noqa: E501

        self._trigger = trigger

    @property
    def eutran_neighbour_cell_meas_info(self) -> List[EutranNeighbourCellMeasInfo]:
        """Gets the eutran_neighbour_cell_meas_info of this InlineNotification.


        :return: The eutran_neighbour_cell_meas_info of this InlineNotification.
        :rtype: List[EutranNeighbourCellMeasInfo]
        """
        return self._eutran_neighbour_cell_meas_info

    @eutran_neighbour_cell_meas_info.setter
    def eutran_neighbour_cell_meas_info(self, eutran_neighbour_cell_meas_info: List[EutranNeighbourCellMeasInfo]):
        """Sets the eutran_neighbour_cell_meas_info of this InlineNotification.


        :param eutran_neighbour_cell_meas_info: The eutran_neighbour_cell_meas_info of this InlineNotification.
        :type eutran_neighbour_cell_meas_info: List[EutranNeighbourCellMeasInfo]
        """

        self._eutran_neighbour_cell_meas_info = eutran_neighbour_cell_meas_info

    @property
    def carrier_aggregation_meas_info(self) -> List[CarrierAggregationMeasInfo1]:
        """Gets the carrier_aggregation_meas_info of this InlineNotification.


        :return: The carrier_aggregation_meas_info of this InlineNotification.
        :rtype: List[CarrierAggregationMeasInfo1]
        """
        return self._carrier_aggregation_meas_info

    @carrier_aggregation_meas_info.setter
    def carrier_aggregation_meas_info(self, carrier_aggregation_meas_info: List[CarrierAggregationMeasInfo1]):
        """Sets the carrier_aggregation_meas_info of this InlineNotification.


        :param carrier_aggregation_meas_info: The carrier_aggregation_meas_info of this InlineNotification.
        :type carrier_aggregation_meas_info: List[CarrierAggregationMeasInfo1]
        """

        self._carrier_aggregation_meas_info = carrier_aggregation_meas_info

    @property
    def height_ue(self) -> int:
        """Gets the height_ue of this InlineNotification.

        Indicates height of the UE in meters relative to the sea level as defined in ETSI TS 136 331 [i.7].  # noqa: E501

        :return: The height_ue of this InlineNotification.
        :rtype: int
        """
        return self._height_ue

    @height_ue.setter
    def height_ue(self, height_ue: int):
        """Sets the height_ue of this InlineNotification.

        Indicates height of the UE in meters relative to the sea level as defined in ETSI TS 136 331 [i.7].  # noqa: E501

        :param height_ue: The height_ue of this InlineNotification.
        :type height_ue: int
        """

        self._height_ue = height_ue

    @property
    def new_radio_meas_info(self) -> List[NewRadioMeasInfo]:
        """Gets the new_radio_meas_info of this InlineNotification.


        :return: The new_radio_meas_info of this InlineNotification.
        :rtype: List[NewRadioMeasInfo]
        """
        return self._new_radio_meas_info

    @new_radio_meas_info.setter
    def new_radio_meas_info(self, new_radio_meas_info: List[NewRadioMeasInfo]):
        """Sets the new_radio_meas_info of this InlineNotification.


        :param new_radio_meas_info: The new_radio_meas_info of this InlineNotification.
        :type new_radio_meas_info: List[NewRadioMeasInfo]
        """

        self._new_radio_meas_info = new_radio_meas_info

    @property
    def new_radio_meas_nei_info(self) -> List[NewRadioMeasNeiInfo]:
        """Gets the new_radio_meas_nei_info of this InlineNotification.


        :return: The new_radio_meas_nei_info of this InlineNotification.
        :rtype: List[NewRadioMeasNeiInfo]
        """
        return self._new_radio_meas_nei_info

    @new_radio_meas_nei_info.setter
    def new_radio_meas_nei_info(self, new_radio_meas_nei_info: List[NewRadioMeasNeiInfo]):
        """Sets the new_radio_meas_nei_info of this InlineNotification.


        :param new_radio_meas_nei_info: The new_radio_meas_nei_info of this InlineNotification.
        :type new_radio_meas_nei_info: List[NewRadioMeasNeiInfo]
        """

        self._new_radio_meas_nei_info = new_radio_meas_nei_info

    @property
    def trigger_nr(self) -> TriggerNr:
        """Gets the trigger_nr of this InlineNotification.

        Corresponds to a specific 5G UE Measurement Report trigger.  # noqa: E501

        :return: The trigger_nr of this InlineNotification.
        :rtype: TriggerNr
        """
        return self._trigger_nr

    @trigger_nr.setter
    def trigger_nr(self, trigger_nr: TriggerNr):
        """Sets the trigger_nr of this InlineNotification.

        Corresponds to a specific 5G UE Measurement Report trigger.  # noqa: E501

        :param trigger_nr: The trigger_nr of this InlineNotification.
        :type trigger_nr: TriggerNr
        """
        if trigger_nr is None:
            raise ValueError("Invalid value for `trigger_nr`, must not be `None`")  # noqa: E501

        self._trigger_nr = trigger_nr

    @property
    def serv_cell_meas_info(self) -> List[ServCellMeasInfo]:
        """Gets the serv_cell_meas_info of this InlineNotification.


        :return: The serv_cell_meas_info of this InlineNotification.
        :rtype: List[ServCellMeasInfo]
        """
        return self._serv_cell_meas_info

    @serv_cell_meas_info.setter
    def serv_cell_meas_info(self, serv_cell_meas_info: List[ServCellMeasInfo]):
        """Sets the serv_cell_meas_info of this InlineNotification.


        :param serv_cell_meas_info: The serv_cell_meas_info of this InlineNotification.
        :type serv_cell_meas_info: List[ServCellMeasInfo]
        """

        self._serv_cell_meas_info = serv_cell_meas_info

    @property
    def nr_neigh_cell_meas_info(self) -> List[NrNeighCellMeasInfo]:
        """Gets the nr_neigh_cell_meas_info of this InlineNotification.


        :return: The nr_neigh_cell_meas_info of this InlineNotification.
        :rtype: List[NrNeighCellMeasInfo]
        """
        return self._nr_neigh_cell_meas_info

    @nr_neigh_cell_meas_info.setter
    def nr_neigh_cell_meas_info(self, nr_neigh_cell_meas_info: List[NrNeighCellMeasInfo]):
        """Sets the nr_neigh_cell_meas_info of this InlineNotification.


        :param nr_neigh_cell_meas_info: The nr_neigh_cell_meas_info of this InlineNotification.
        :type nr_neigh_cell_meas_info: List[NrNeighCellMeasInfo]
        """

        self._nr_neigh_cell_meas_info = nr_neigh_cell_meas_info

    @property
    def eutra_neigh_cell_meas_info(self) -> List[EutraNeighCellMeasInfo]:
        """Gets the eutra_neigh_cell_meas_info of this InlineNotification.


        :return: The eutra_neigh_cell_meas_info of this InlineNotification.
        :rtype: List[EutraNeighCellMeasInfo]
        """
        return self._eutra_neigh_cell_meas_info

    @eutra_neigh_cell_meas_info.setter
    def eutra_neigh_cell_meas_info(self, eutra_neigh_cell_meas_info: List[EutraNeighCellMeasInfo]):
        """Sets the eutra_neigh_cell_meas_info of this InlineNotification.


        :param eutra_neigh_cell_meas_info: The eutra_neigh_cell_meas_info of this InlineNotification.
        :type eutra_neigh_cell_meas_info: List[EutraNeighCellMeasInfo]
        """

        self._eutra_neigh_cell_meas_info = eutra_neigh_cell_meas_info

    @property
    def timing_advance(self) -> int:
        """Gets the timing_advance of this InlineNotification.

        The timing advance as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :return: The timing_advance of this InlineNotification.
        :rtype: int
        """
        return self._timing_advance

    @timing_advance.setter
    def timing_advance(self, timing_advance: int):
        """Sets the timing_advance of this InlineNotification.

        The timing advance as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :param timing_advance: The timing_advance of this InlineNotification.
        :type timing_advance: int
        """
        if timing_advance is None:
            raise ValueError("Invalid value for `timing_advance`, must not be `None`")  # noqa: E501

        self._timing_advance = timing_advance

    @property
    def secondary_cell_add(self) -> List[SecondaryCellAdd]:
        """Gets the secondary_cell_add of this InlineNotification.


        :return: The secondary_cell_add of this InlineNotification.
        :rtype: List[SecondaryCellAdd]
        """
        return self._secondary_cell_add

    @secondary_cell_add.setter
    def secondary_cell_add(self, secondary_cell_add: List[SecondaryCellAdd]):
        """Sets the secondary_cell_add of this InlineNotification.


        :param secondary_cell_add: The secondary_cell_add of this InlineNotification.
        :type secondary_cell_add: List[SecondaryCellAdd]
        """

        self._secondary_cell_add = secondary_cell_add

    @property
    def secondary_cell_remove(self) -> List[SecondaryCellRemove]:
        """Gets the secondary_cell_remove of this InlineNotification.


        :return: The secondary_cell_remove of this InlineNotification.
        :rtype: List[SecondaryCellRemove]
        """
        return self._secondary_cell_remove

    @secondary_cell_remove.setter
    def secondary_cell_remove(self, secondary_cell_remove: List[SecondaryCellRemove]):
        """Sets the secondary_cell_remove of this InlineNotification.


        :param secondary_cell_remove: The secondary_cell_remove of this InlineNotification.
        :type secondary_cell_remove: List[SecondaryCellRemove]
        """

        self._secondary_cell_remove = secondary_cell_remove

    @property
    def s1_event(self) -> str:
        """Gets the s1_event of this InlineNotification.

        The subscribed event that triggered this notification in S1BearerSubscription.  # noqa: E501

        :return: The s1_event of this InlineNotification.
        :rtype: str
        """
        return self._s1_event

    @s1_event.setter
    def s1_event(self, s1_event: str):
        """Sets the s1_event of this InlineNotification.

        The subscribed event that triggered this notification in S1BearerSubscription.  # noqa: E501

        :param s1_event: The s1_event of this InlineNotification.
        :type s1_event: str
        """
        allowed_values = ["SEE_DESCRIPTION"]  # noqa: E501
        if s1_event not in allowed_values:
            raise ValueError(
                "Invalid value for `s1_event` ({0}), must be one of {1}"
                .format(s1_event, allowed_values)
            )

        self._s1_event = s1_event

    @property
    def s1_ue_info(self) -> S1UeInfo1:
        """Gets the s1_ue_info of this InlineNotification.


        :return: The s1_ue_info of this InlineNotification.
        :rtype: S1UeInfo1
        """
        return self._s1_ue_info

    @s1_ue_info.setter
    def s1_ue_info(self, s1_ue_info: S1UeInfo1):
        """Sets the s1_ue_info of this InlineNotification.


        :param s1_ue_info: The s1_ue_info of this InlineNotification.
        :type s1_ue_info: S1UeInfo1
        """
        if s1_ue_info is None:
            raise ValueError("Invalid value for `s1_ue_info`, must not be `None`")  # noqa: E501

        self._s1_ue_info = s1_ue_info
