from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.l2_meas1_cell_info_inner import L2Meas1CellInfoInner
from openapi_server.models.l2_meas1_cell_ue_info_inner import L2Meas1CellUEInfoInner
from openapi_server.models.time_stamp import TimeStamp
from openapi_server import util

from openapi_server.models.l2_meas1_cell_info_inner import L2Meas1CellInfoInner  # noqa: E501
from openapi_server.models.l2_meas1_cell_ue_info_inner import L2Meas1CellUEInfoInner  # noqa: E501
from openapi_server.models.time_stamp import TimeStamp  # noqa: E501

class L2Meas1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cell_info=None, cell_ue_info=None, time_stamp=None):  # noqa: E501
        """L2Meas1 - a model defined in OpenAPI

        :param cell_info: The cell_info of this L2Meas1.  # noqa: E501
        :type cell_info: List[L2Meas1CellInfoInner]
        :param cell_ue_info: The cell_ue_info of this L2Meas1.  # noqa: E501
        :type cell_ue_info: List[L2Meas1CellUEInfoInner]
        :param time_stamp: The time_stamp of this L2Meas1.  # noqa: E501
        :type time_stamp: TimeStamp
        """
        self.openapi_types = {
            'cell_info': List[L2Meas1CellInfoInner],
            'cell_ue_info': List[L2Meas1CellUEInfoInner],
            'time_stamp': TimeStamp
        }

        self.attribute_map = {
            'cell_info': 'cellInfo',
            'cell_ue_info': 'cellUEInfo',
            'time_stamp': 'timeStamp'
        }

        self._cell_info = cell_info
        self._cell_ue_info = cell_ue_info
        self._time_stamp = time_stamp

    @classmethod
    def from_dict(cls, dikt) -> 'L2Meas1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The L2Meas1_ of this L2Meas1.  # noqa: E501
        :rtype: L2Meas1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cell_info(self) -> List[L2Meas1CellInfoInner]:
        """Gets the cell_info of this L2Meas1.

        The per cell measurement information as defined below.  # noqa: E501

        :return: The cell_info of this L2Meas1.
        :rtype: List[L2Meas1CellInfoInner]
        """
        return self._cell_info

    @cell_info.setter
    def cell_info(self, cell_info: List[L2Meas1CellInfoInner]):
        """Sets the cell_info of this L2Meas1.

        The per cell measurement information as defined below.  # noqa: E501

        :param cell_info: The cell_info of this L2Meas1.
        :type cell_info: List[L2Meas1CellInfoInner]
        """
        if cell_info is not None and len(cell_info) < 0:
            raise ValueError("Invalid value for `cell_info`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._cell_info = cell_info

    @property
    def cell_ue_info(self) -> List[L2Meas1CellUEInfoInner]:
        """Gets the cell_ue_info of this L2Meas1.

        The per cell per UE layer 2 measurements information as defined below.  # noqa: E501

        :return: The cell_ue_info of this L2Meas1.
        :rtype: List[L2Meas1CellUEInfoInner]
        """
        return self._cell_ue_info

    @cell_ue_info.setter
    def cell_ue_info(self, cell_ue_info: List[L2Meas1CellUEInfoInner]):
        """Sets the cell_ue_info of this L2Meas1.

        The per cell per UE layer 2 measurements information as defined below.  # noqa: E501

        :param cell_ue_info: The cell_ue_info of this L2Meas1.
        :type cell_ue_info: List[L2Meas1CellUEInfoInner]
        """
        if cell_ue_info is not None and len(cell_ue_info) < 0:
            raise ValueError("Invalid value for `cell_ue_info`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._cell_ue_info = cell_ue_info

    @property
    def time_stamp(self) -> TimeStamp:
        """Gets the time_stamp of this L2Meas1.

        Time stamp.  # noqa: E501

        :return: The time_stamp of this L2Meas1.
        :rtype: TimeStamp
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: TimeStamp):
        """Sets the time_stamp of this L2Meas1.

        Time stamp.  # noqa: E501

        :param time_stamp: The time_stamp of this L2Meas1.
        :type time_stamp: TimeStamp
        """

        self._time_stamp = time_stamp
