from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.cell_info import CellInfo
from openapi_server.models.cell_ue_info import CellUEInfo
from openapi_server.models.time_stamp import TimeStamp
from openapi_server import util

from openapi_server.models.cell_info import CellInfo  # noqa: E501
from openapi_server.models.cell_ue_info import CellUEInfo  # noqa: E501
from openapi_server.models.time_stamp import TimeStamp  # noqa: E501

class L2Meas(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, time_stamp=None, cell_info=None, cell_ue_info=None):  # noqa: E501
        """L2Meas - a model defined in OpenAPI

        :param time_stamp: The time_stamp of this L2Meas.  # noqa: E501
        :type time_stamp: TimeStamp
        :param cell_info: The cell_info of this L2Meas.  # noqa: E501
        :type cell_info: List[CellInfo]
        :param cell_ue_info: The cell_ue_info of this L2Meas.  # noqa: E501
        :type cell_ue_info: List[CellUEInfo]
        """
        self.openapi_types = {
            'time_stamp': TimeStamp,
            'cell_info': List[CellInfo],
            'cell_ue_info': List[CellUEInfo]
        }

        self.attribute_map = {
            'time_stamp': 'timeStamp',
            'cell_info': 'cellInfo',
            'cell_ue_info': 'cellUEInfo'
        }

        self._time_stamp = time_stamp
        self._cell_info = cell_info
        self._cell_ue_info = cell_ue_info

    @classmethod
    def from_dict(cls, dikt) -> 'L2Meas':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The L2Meas of this L2Meas.  # noqa: E501
        :rtype: L2Meas
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time_stamp(self) -> TimeStamp:
        """Gets the time_stamp of this L2Meas.

        Time stamp.  # noqa: E501

        :return: The time_stamp of this L2Meas.
        :rtype: TimeStamp
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: TimeStamp):
        """Sets the time_stamp of this L2Meas.

        Time stamp.  # noqa: E501

        :param time_stamp: The time_stamp of this L2Meas.
        :type time_stamp: TimeStamp
        """

        self._time_stamp = time_stamp

    @property
    def cell_info(self) -> List[CellInfo]:
        """Gets the cell_info of this L2Meas.


        :return: The cell_info of this L2Meas.
        :rtype: List[CellInfo]
        """
        return self._cell_info

    @cell_info.setter
    def cell_info(self, cell_info: List[CellInfo]):
        """Sets the cell_info of this L2Meas.


        :param cell_info: The cell_info of this L2Meas.
        :type cell_info: List[CellInfo]
        """

        self._cell_info = cell_info

    @property
    def cell_ue_info(self) -> List[CellUEInfo]:
        """Gets the cell_ue_info of this L2Meas.


        :return: The cell_ue_info of this L2Meas.
        :rtype: List[CellUEInfo]
        """
        return self._cell_ue_info

    @cell_ue_info.setter
    def cell_ue_info(self, cell_ue_info: List[CellUEInfo]):
        """Sets the cell_ue_info of this L2Meas.


        :param cell_ue_info: The cell_ue_info of this L2Meas.
        :type cell_ue_info: List[CellUEInfo]
        """

        self._cell_ue_info = cell_ue_info
