from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.associate_id import AssociateId
from openapi_server.models.carrier_aggregation_meas_info import CarrierAggregationMeasInfo
from openapi_server.models.ecgi import Ecgi
from openapi_server.models.eutran_neighbour_cell_meas_info import EutranNeighbourCellMeasInfo
from openapi_server.models.link_type import LinkType
from openapi_server.models.links import Links
from openapi_server.models.new_radio_meas_info import NewRadioMeasInfo
from openapi_server.models.new_radio_meas_nei_info import NewRadioMeasNeiInfo
from openapi_server.models.time_stamp import TimeStamp
from openapi_server.models.trigger import Trigger
from openapi_server import util

from openapi_server.models.associate_id import AssociateId  # noqa: E501
from openapi_server.models.carrier_aggregation_meas_info import CarrierAggregationMeasInfo  # noqa: E501
from openapi_server.models.ecgi import Ecgi  # noqa: E501
from openapi_server.models.eutran_neighbour_cell_meas_info import EutranNeighbourCellMeasInfo  # noqa: E501
from openapi_server.models.link_type import LinkType  # noqa: E501
from openapi_server.models.links import Links  # noqa: E501
from openapi_server.models.new_radio_meas_info import NewRadioMeasInfo  # noqa: E501
from openapi_server.models.new_radio_meas_nei_info import NewRadioMeasNeiInfo  # noqa: E501
from openapi_server.models.time_stamp import TimeStamp  # noqa: E501
from openapi_server.models.trigger import Trigger  # noqa: E501

class MeasRepUeNotification(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, notification_type=None, time_stamp=None, ecgi=None, associate_id=None, rsrp=None, rsrp_ex=None, rsrq=None, rsrq_ex=None, sinr=None, trigger=None, eutran_neighbour_cell_meas_info=None, carrier_aggregation_meas_info=None, height_ue=None, new_radio_meas_info=None, new_radio_meas_nei_info=None, links=None, subscription=None):  # noqa: E501
        """MeasRepUeNotification - a model defined in OpenAPI

        :param notification_type: The notification_type of this MeasRepUeNotification.  # noqa: E501
        :type notification_type: str
        :param time_stamp: The time_stamp of this MeasRepUeNotification.  # noqa: E501
        :type time_stamp: TimeStamp
        :param ecgi: The ecgi of this MeasRepUeNotification.  # noqa: E501
        :type ecgi: Ecgi
        :param associate_id: The associate_id of this MeasRepUeNotification.  # noqa: E501
        :type associate_id: List[AssociateId]
        :param rsrp: The rsrp of this MeasRepUeNotification.  # noqa: E501
        :type rsrp: int
        :param rsrp_ex: The rsrp_ex of this MeasRepUeNotification.  # noqa: E501
        :type rsrp_ex: int
        :param rsrq: The rsrq of this MeasRepUeNotification.  # noqa: E501
        :type rsrq: int
        :param rsrq_ex: The rsrq_ex of this MeasRepUeNotification.  # noqa: E501
        :type rsrq_ex: int
        :param sinr: The sinr of this MeasRepUeNotification.  # noqa: E501
        :type sinr: int
        :param trigger: The trigger of this MeasRepUeNotification.  # noqa: E501
        :type trigger: Trigger
        :param eutran_neighbour_cell_meas_info: The eutran_neighbour_cell_meas_info of this MeasRepUeNotification.  # noqa: E501
        :type eutran_neighbour_cell_meas_info: List[EutranNeighbourCellMeasInfo]
        :param carrier_aggregation_meas_info: The carrier_aggregation_meas_info of this MeasRepUeNotification.  # noqa: E501
        :type carrier_aggregation_meas_info: List[CarrierAggregationMeasInfo]
        :param height_ue: The height_ue of this MeasRepUeNotification.  # noqa: E501
        :type height_ue: int
        :param new_radio_meas_info: The new_radio_meas_info of this MeasRepUeNotification.  # noqa: E501
        :type new_radio_meas_info: List[NewRadioMeasInfo]
        :param new_radio_meas_nei_info: The new_radio_meas_nei_info of this MeasRepUeNotification.  # noqa: E501
        :type new_radio_meas_nei_info: List[NewRadioMeasNeiInfo]
        :param links: The links of this MeasRepUeNotification.  # noqa: E501
        :type links: List[Links]
        :param subscription: The subscription of this MeasRepUeNotification.  # noqa: E501
        :type subscription: List[LinkType]
        """
        self.openapi_types = {
            'notification_type': str,
            'time_stamp': TimeStamp,
            'ecgi': Ecgi,
            'associate_id': List[AssociateId],
            'rsrp': int,
            'rsrp_ex': int,
            'rsrq': int,
            'rsrq_ex': int,
            'sinr': int,
            'trigger': Trigger,
            'eutran_neighbour_cell_meas_info': List[EutranNeighbourCellMeasInfo],
            'carrier_aggregation_meas_info': List[CarrierAggregationMeasInfo],
            'height_ue': int,
            'new_radio_meas_info': List[NewRadioMeasInfo],
            'new_radio_meas_nei_info': List[NewRadioMeasNeiInfo],
            'links': List[Links],
            'subscription': List[LinkType]
        }

        self.attribute_map = {
            'notification_type': 'notificationType',
            'time_stamp': 'timeStamp',
            'ecgi': 'ecgi',
            'associate_id': 'associateId',
            'rsrp': 'rsrp',
            'rsrp_ex': 'rsrpEx',
            'rsrq': 'rsrq',
            'rsrq_ex': 'rsrqEx',
            'sinr': 'sinr',
            'trigger': 'trigger',
            'eutran_neighbour_cell_meas_info': 'eutranNeighbourCellMeasInfo',
            'carrier_aggregation_meas_info': 'carrierAggregationMeasInfo',
            'height_ue': 'heightUe',
            'new_radio_meas_info': 'newRadioMeasInfo',
            'new_radio_meas_nei_info': 'newRadioMeasNeiInfo',
            'links': '_links',
            'subscription': 'subscription'
        }

        self._notification_type = notification_type
        self._time_stamp = time_stamp
        self._ecgi = ecgi
        self._associate_id = associate_id
        self._rsrp = rsrp
        self._rsrp_ex = rsrp_ex
        self._rsrq = rsrq
        self._rsrq_ex = rsrq_ex
        self._sinr = sinr
        self._trigger = trigger
        self._eutran_neighbour_cell_meas_info = eutran_neighbour_cell_meas_info
        self._carrier_aggregation_meas_info = carrier_aggregation_meas_info
        self._height_ue = height_ue
        self._new_radio_meas_info = new_radio_meas_info
        self._new_radio_meas_nei_info = new_radio_meas_nei_info
        self._links = links
        self._subscription = subscription

    @classmethod
    def from_dict(cls, dikt) -> 'MeasRepUeNotification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MeasRepUeNotification of this MeasRepUeNotification.  # noqa: E501
        :rtype: MeasRepUeNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_type(self) -> str:
        """Gets the notification_type of this MeasRepUeNotification.

        Shall be set to \"MeasRepUeNotification\".  # noqa: E501

        :return: The notification_type of this MeasRepUeNotification.
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type: str):
        """Sets the notification_type of this MeasRepUeNotification.

        Shall be set to \"MeasRepUeNotification\".  # noqa: E501

        :param notification_type: The notification_type of this MeasRepUeNotification.
        :type notification_type: str
        """
        if notification_type is None:
            raise ValueError("Invalid value for `notification_type`, must not be `None`")  # noqa: E501

        self._notification_type = notification_type

    @property
    def time_stamp(self) -> TimeStamp:
        """Gets the time_stamp of this MeasRepUeNotification.

        Time stamp.  # noqa: E501

        :return: The time_stamp of this MeasRepUeNotification.
        :rtype: TimeStamp
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: TimeStamp):
        """Sets the time_stamp of this MeasRepUeNotification.

        Time stamp.  # noqa: E501

        :param time_stamp: The time_stamp of this MeasRepUeNotification.
        :type time_stamp: TimeStamp
        """

        self._time_stamp = time_stamp

    @property
    def ecgi(self) -> Ecgi:
        """Gets the ecgi of this MeasRepUeNotification.

        E-UTRAN Cell Global Identifier of the Primary serving Cell (PCell), as defined in ETSI TS 136 331 [i.7].  # noqa: E501

        :return: The ecgi of this MeasRepUeNotification.
        :rtype: Ecgi
        """
        return self._ecgi

    @ecgi.setter
    def ecgi(self, ecgi: Ecgi):
        """Sets the ecgi of this MeasRepUeNotification.

        E-UTRAN Cell Global Identifier of the Primary serving Cell (PCell), as defined in ETSI TS 136 331 [i.7].  # noqa: E501

        :param ecgi: The ecgi of this MeasRepUeNotification.
        :type ecgi: Ecgi
        """
        if ecgi is None:
            raise ValueError("Invalid value for `ecgi`, must not be `None`")  # noqa: E501

        self._ecgi = ecgi

    @property
    def associate_id(self) -> List[AssociateId]:
        """Gets the associate_id of this MeasRepUeNotification.

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :return: The associate_id of this MeasRepUeNotification.
        :rtype: List[AssociateId]
        """
        return self._associate_id

    @associate_id.setter
    def associate_id(self, associate_id: List[AssociateId]):
        """Sets the associate_id of this MeasRepUeNotification.

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :param associate_id: The associate_id of this MeasRepUeNotification.
        :type associate_id: List[AssociateId]
        """
        if associate_id is not None and len(associate_id) < 0:
            raise ValueError("Invalid value for `associate_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._associate_id = associate_id

    @property
    def rsrp(self) -> int:
        """Gets the rsrp of this MeasRepUeNotification.

        Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :return: The rsrp of this MeasRepUeNotification.
        :rtype: int
        """
        return self._rsrp

    @rsrp.setter
    def rsrp(self, rsrp: int):
        """Sets the rsrp of this MeasRepUeNotification.

        Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :param rsrp: The rsrp of this MeasRepUeNotification.
        :type rsrp: int
        """
        if rsrp is None:
            raise ValueError("Invalid value for `rsrp`, must not be `None`")  # noqa: E501

        self._rsrp = rsrp

    @property
    def rsrp_ex(self) -> int:
        """Gets the rsrp_ex of this MeasRepUeNotification.

        Extended Reference Signal Received Power, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :return: The rsrp_ex of this MeasRepUeNotification.
        :rtype: int
        """
        return self._rsrp_ex

    @rsrp_ex.setter
    def rsrp_ex(self, rsrp_ex: int):
        """Sets the rsrp_ex of this MeasRepUeNotification.

        Extended Reference Signal Received Power, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :param rsrp_ex: The rsrp_ex of this MeasRepUeNotification.
        :type rsrp_ex: int
        """

        self._rsrp_ex = rsrp_ex

    @property
    def rsrq(self) -> int:
        """Gets the rsrq of this MeasRepUeNotification.

        Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :return: The rsrq of this MeasRepUeNotification.
        :rtype: int
        """
        return self._rsrq

    @rsrq.setter
    def rsrq(self, rsrq: int):
        """Sets the rsrq of this MeasRepUeNotification.

        Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :param rsrq: The rsrq of this MeasRepUeNotification.
        :type rsrq: int
        """
        if rsrq is None:
            raise ValueError("Invalid value for `rsrq`, must not be `None`")  # noqa: E501

        self._rsrq = rsrq

    @property
    def rsrq_ex(self) -> int:
        """Gets the rsrq_ex of this MeasRepUeNotification.

        Extended Reference Signal Received Quality, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :return: The rsrq_ex of this MeasRepUeNotification.
        :rtype: int
        """
        return self._rsrq_ex

    @rsrq_ex.setter
    def rsrq_ex(self, rsrq_ex: int):
        """Sets the rsrq_ex of this MeasRepUeNotification.

        Extended Reference Signal Received Quality, with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :param rsrq_ex: The rsrq_ex of this MeasRepUeNotification.
        :type rsrq_ex: int
        """

        self._rsrq_ex = rsrq_ex

    @property
    def sinr(self) -> int:
        """Gets the sinr of this MeasRepUeNotification.

        Reference Signal \"Signal to Interference plus Noise Ratio\", with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :return: The sinr of this MeasRepUeNotification.
        :rtype: int
        """
        return self._sinr

    @sinr.setter
    def sinr(self, sinr: int):
        """Sets the sinr of this MeasRepUeNotification.

        Reference Signal \"Signal to Interference plus Noise Ratio\", with value mapping defined in ETSI TS 136 133 [i.16].  # noqa: E501

        :param sinr: The sinr of this MeasRepUeNotification.
        :type sinr: int
        """

        self._sinr = sinr

    @property
    def trigger(self) -> Trigger:
        """Gets the trigger of this MeasRepUeNotification.

        Corresponds to a specific E-UTRAN UE Measurement Report trigger.  # noqa: E501

        :return: The trigger of this MeasRepUeNotification.
        :rtype: Trigger
        """
        return self._trigger

    @trigger.setter
    def trigger(self, trigger: Trigger):
        """Sets the trigger of this MeasRepUeNotification.

        Corresponds to a specific E-UTRAN UE Measurement Report trigger.  # noqa: E501

        :param trigger: The trigger of this MeasRepUeNotification.
        :type trigger: Trigger
        """
        if trigger is None:
            raise ValueError("Invalid value for `trigger`, must not be `None`")  # noqa: E501

        self._trigger = trigger

    @property
    def eutran_neighbour_cell_meas_info(self) -> List[EutranNeighbourCellMeasInfo]:
        """Gets the eutran_neighbour_cell_meas_info of this MeasRepUeNotification.


        :return: The eutran_neighbour_cell_meas_info of this MeasRepUeNotification.
        :rtype: List[EutranNeighbourCellMeasInfo]
        """
        return self._eutran_neighbour_cell_meas_info

    @eutran_neighbour_cell_meas_info.setter
    def eutran_neighbour_cell_meas_info(self, eutran_neighbour_cell_meas_info: List[EutranNeighbourCellMeasInfo]):
        """Sets the eutran_neighbour_cell_meas_info of this MeasRepUeNotification.


        :param eutran_neighbour_cell_meas_info: The eutran_neighbour_cell_meas_info of this MeasRepUeNotification.
        :type eutran_neighbour_cell_meas_info: List[EutranNeighbourCellMeasInfo]
        """

        self._eutran_neighbour_cell_meas_info = eutran_neighbour_cell_meas_info

    @property
    def carrier_aggregation_meas_info(self) -> List[CarrierAggregationMeasInfo]:
        """Gets the carrier_aggregation_meas_info of this MeasRepUeNotification.


        :return: The carrier_aggregation_meas_info of this MeasRepUeNotification.
        :rtype: List[CarrierAggregationMeasInfo]
        """
        return self._carrier_aggregation_meas_info

    @carrier_aggregation_meas_info.setter
    def carrier_aggregation_meas_info(self, carrier_aggregation_meas_info: List[CarrierAggregationMeasInfo]):
        """Sets the carrier_aggregation_meas_info of this MeasRepUeNotification.


        :param carrier_aggregation_meas_info: The carrier_aggregation_meas_info of this MeasRepUeNotification.
        :type carrier_aggregation_meas_info: List[CarrierAggregationMeasInfo]
        """

        self._carrier_aggregation_meas_info = carrier_aggregation_meas_info

    @property
    def height_ue(self) -> int:
        """Gets the height_ue of this MeasRepUeNotification.

        Indicates height of the UE in meters relative to the sea level as defined in ETSI TS 136 331 [i.7].  # noqa: E501

        :return: The height_ue of this MeasRepUeNotification.
        :rtype: int
        """
        return self._height_ue

    @height_ue.setter
    def height_ue(self, height_ue: int):
        """Sets the height_ue of this MeasRepUeNotification.

        Indicates height of the UE in meters relative to the sea level as defined in ETSI TS 136 331 [i.7].  # noqa: E501

        :param height_ue: The height_ue of this MeasRepUeNotification.
        :type height_ue: int
        """

        self._height_ue = height_ue

    @property
    def new_radio_meas_info(self) -> List[NewRadioMeasInfo]:
        """Gets the new_radio_meas_info of this MeasRepUeNotification.


        :return: The new_radio_meas_info of this MeasRepUeNotification.
        :rtype: List[NewRadioMeasInfo]
        """
        return self._new_radio_meas_info

    @new_radio_meas_info.setter
    def new_radio_meas_info(self, new_radio_meas_info: List[NewRadioMeasInfo]):
        """Sets the new_radio_meas_info of this MeasRepUeNotification.


        :param new_radio_meas_info: The new_radio_meas_info of this MeasRepUeNotification.
        :type new_radio_meas_info: List[NewRadioMeasInfo]
        """

        self._new_radio_meas_info = new_radio_meas_info

    @property
    def new_radio_meas_nei_info(self) -> List[NewRadioMeasNeiInfo]:
        """Gets the new_radio_meas_nei_info of this MeasRepUeNotification.


        :return: The new_radio_meas_nei_info of this MeasRepUeNotification.
        :rtype: List[NewRadioMeasNeiInfo]
        """
        return self._new_radio_meas_nei_info

    @new_radio_meas_nei_info.setter
    def new_radio_meas_nei_info(self, new_radio_meas_nei_info: List[NewRadioMeasNeiInfo]):
        """Sets the new_radio_meas_nei_info of this MeasRepUeNotification.


        :param new_radio_meas_nei_info: The new_radio_meas_nei_info of this MeasRepUeNotification.
        :type new_radio_meas_nei_info: List[NewRadioMeasNeiInfo]
        """

        self._new_radio_meas_nei_info = new_radio_meas_nei_info

    @property
    def links(self) -> List[Links]:
        """Gets the links of this MeasRepUeNotification.

        Links to resources related to this notification.  # noqa: E501

        :return: The links of this MeasRepUeNotification.
        :rtype: List[Links]
        """
        return self._links

    @links.setter
    def links(self, links: List[Links]):
        """Sets the links of this MeasRepUeNotification.

        Links to resources related to this notification.  # noqa: E501

        :param links: The links of this MeasRepUeNotification.
        :type links: List[Links]
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def subscription(self) -> List[LinkType]:
        """Gets the subscription of this MeasRepUeNotification.

        A link to the related subscription.  # noqa: E501

        :return: The subscription of this MeasRepUeNotification.
        :rtype: List[LinkType]
        """
        return self._subscription

    @subscription.setter
    def subscription(self, subscription: List[LinkType]):
        """Sets the subscription of this MeasRepUeNotification.

        A link to the related subscription.  # noqa: E501

        :param subscription: The subscription of this MeasRepUeNotification.
        :type subscription: List[LinkType]
        """
        if subscription is None:
            raise ValueError("Invalid value for `subscription`, must not be `None`")  # noqa: E501

        self._subscription = subscription
