from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.associate_id import AssociateId
from openapi_server.models.ecgi import Ecgi
from openapi_server.models.link_type import LinkType
from openapi_server.models.links import Links
from openapi_server.models.time_stamp import TimeStamp
from openapi_server import util

from openapi_server.models.associate_id import AssociateId  # noqa: E501
from openapi_server.models.ecgi import Ecgi  # noqa: E501
from openapi_server.models.link_type import LinkType  # noqa: E501
from openapi_server.models.links import Links  # noqa: E501
from openapi_server.models.time_stamp import TimeStamp  # noqa: E501

class MeasTaNotification(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, notification_type=None, time_stamp=None, ecgi=None, associate_id=None, timing_advance=None, links=None, subscription=None):  # noqa: E501
        """MeasTaNotification - a model defined in OpenAPI

        :param notification_type: The notification_type of this MeasTaNotification.  # noqa: E501
        :type notification_type: str
        :param time_stamp: The time_stamp of this MeasTaNotification.  # noqa: E501
        :type time_stamp: TimeStamp
        :param ecgi: The ecgi of this MeasTaNotification.  # noqa: E501
        :type ecgi: Ecgi
        :param associate_id: The associate_id of this MeasTaNotification.  # noqa: E501
        :type associate_id: List[AssociateId]
        :param timing_advance: The timing_advance of this MeasTaNotification.  # noqa: E501
        :type timing_advance: int
        :param links: The links of this MeasTaNotification.  # noqa: E501
        :type links: List[Links]
        :param subscription: The subscription of this MeasTaNotification.  # noqa: E501
        :type subscription: List[LinkType]
        """
        self.openapi_types = {
            'notification_type': str,
            'time_stamp': TimeStamp,
            'ecgi': Ecgi,
            'associate_id': List[AssociateId],
            'timing_advance': int,
            'links': List[Links],
            'subscription': List[LinkType]
        }

        self.attribute_map = {
            'notification_type': 'notificationType',
            'time_stamp': 'timeStamp',
            'ecgi': 'ecgi',
            'associate_id': 'associateId',
            'timing_advance': 'timingAdvance',
            'links': '_links',
            'subscription': 'subscription'
        }

        self._notification_type = notification_type
        self._time_stamp = time_stamp
        self._ecgi = ecgi
        self._associate_id = associate_id
        self._timing_advance = timing_advance
        self._links = links
        self._subscription = subscription

    @classmethod
    def from_dict(cls, dikt) -> 'MeasTaNotification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MeasTaNotification of this MeasTaNotification.  # noqa: E501
        :rtype: MeasTaNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_type(self) -> str:
        """Gets the notification_type of this MeasTaNotification.

        Shall be set to \"MeasTaNotification\".  # noqa: E501

        :return: The notification_type of this MeasTaNotification.
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type: str):
        """Sets the notification_type of this MeasTaNotification.

        Shall be set to \"MeasTaNotification\".  # noqa: E501

        :param notification_type: The notification_type of this MeasTaNotification.
        :type notification_type: str
        """
        if notification_type is None:
            raise ValueError("Invalid value for `notification_type`, must not be `None`")  # noqa: E501

        self._notification_type = notification_type

    @property
    def time_stamp(self) -> TimeStamp:
        """Gets the time_stamp of this MeasTaNotification.

        Time stamp.  # noqa: E501

        :return: The time_stamp of this MeasTaNotification.
        :rtype: TimeStamp
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: TimeStamp):
        """Sets the time_stamp of this MeasTaNotification.

        Time stamp.  # noqa: E501

        :param time_stamp: The time_stamp of this MeasTaNotification.
        :type time_stamp: TimeStamp
        """

        self._time_stamp = time_stamp

    @property
    def ecgi(self) -> Ecgi:
        """Gets the ecgi of this MeasTaNotification.

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :return: The ecgi of this MeasTaNotification.
        :rtype: Ecgi
        """
        return self._ecgi

    @ecgi.setter
    def ecgi(self, ecgi: Ecgi):
        """Sets the ecgi of this MeasTaNotification.

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :param ecgi: The ecgi of this MeasTaNotification.
        :type ecgi: Ecgi
        """
        if ecgi is None:
            raise ValueError("Invalid value for `ecgi`, must not be `None`")  # noqa: E501

        self._ecgi = ecgi

    @property
    def associate_id(self) -> List[AssociateId]:
        """Gets the associate_id of this MeasTaNotification.

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :return: The associate_id of this MeasTaNotification.
        :rtype: List[AssociateId]
        """
        return self._associate_id

    @associate_id.setter
    def associate_id(self, associate_id: List[AssociateId]):
        """Sets the associate_id of this MeasTaNotification.

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :param associate_id: The associate_id of this MeasTaNotification.
        :type associate_id: List[AssociateId]
        """
        if associate_id is not None and len(associate_id) < 0:
            raise ValueError("Invalid value for `associate_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._associate_id = associate_id

    @property
    def timing_advance(self) -> int:
        """Gets the timing_advance of this MeasTaNotification.

        The timing advance as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :return: The timing_advance of this MeasTaNotification.
        :rtype: int
        """
        return self._timing_advance

    @timing_advance.setter
    def timing_advance(self, timing_advance: int):
        """Sets the timing_advance of this MeasTaNotification.

        The timing advance as defined in ETSI TS 136 214 [i.5].  # noqa: E501

        :param timing_advance: The timing_advance of this MeasTaNotification.
        :type timing_advance: int
        """
        if timing_advance is None:
            raise ValueError("Invalid value for `timing_advance`, must not be `None`")  # noqa: E501

        self._timing_advance = timing_advance

    @property
    def links(self) -> List[Links]:
        """Gets the links of this MeasTaNotification.

        Links to resources related to this notification.  # noqa: E501

        :return: The links of this MeasTaNotification.
        :rtype: List[Links]
        """
        return self._links

    @links.setter
    def links(self, links: List[Links]):
        """Sets the links of this MeasTaNotification.

        Links to resources related to this notification.  # noqa: E501

        :param links: The links of this MeasTaNotification.
        :type links: List[Links]
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def subscription(self) -> List[LinkType]:
        """Gets the subscription of this MeasTaNotification.

        A link to the related subscription.  # noqa: E501

        :return: The subscription of this MeasTaNotification.
        :rtype: List[LinkType]
        """
        return self._subscription

    @subscription.setter
    def subscription(self, subscription: List[LinkType]):
        """Sets the subscription of this MeasTaNotification.

        A link to the related subscription.  # noqa: E501

        :param subscription: The subscription of this MeasTaNotification.
        :type subscription: List[LinkType]
        """
        if subscription is None:
            raise ValueError("Invalid value for `subscription`, must not be `None`")  # noqa: E501

        self._subscription = subscription
