from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.notification_post_request_subscription_notification import NotificationPOSTRequestSubscriptionNotification
from openapi_server import util

from openapi_server.models.notification_post_request_subscription_notification import NotificationPOSTRequestSubscriptionNotification  # noqa: E501

class NotificationPOSTRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, subscription_notification=None):  # noqa: E501
        """NotificationPOSTRequest - a model defined in OpenAPI

        :param subscription_notification: The subscription_notification of this NotificationPOSTRequest.  # noqa: E501
        :type subscription_notification: NotificationPOSTRequestSubscriptionNotification
        """
        self.openapi_types = {
            'subscription_notification': NotificationPOSTRequestSubscriptionNotification
        }

        self.attribute_map = {
            'subscription_notification': 'subscriptionNotification'
        }

        self._subscription_notification = subscription_notification

    @classmethod
    def from_dict(cls, dikt) -> 'NotificationPOSTRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The notificationPOST_request of this NotificationPOSTRequest.  # noqa: E501
        :rtype: NotificationPOSTRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subscription_notification(self) -> NotificationPOSTRequestSubscriptionNotification:
        """Gets the subscription_notification of this NotificationPOSTRequest.


        :return: The subscription_notification of this NotificationPOSTRequest.
        :rtype: NotificationPOSTRequestSubscriptionNotification
        """
        return self._subscription_notification

    @subscription_notification.setter
    def subscription_notification(self, subscription_notification: NotificationPOSTRequestSubscriptionNotification):
        """Sets the subscription_notification of this NotificationPOSTRequest.


        :param subscription_notification: The subscription_notification of this NotificationPOSTRequest.
        :type subscription_notification: NotificationPOSTRequestSubscriptionNotification
        """

        self._subscription_notification = subscription_notification
