from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.ca_reconf_subscription import CaReconfSubscription
from openapi_server.models.cell_change_subscription import CellChangeSubscription
from openapi_server.models.filter_criteria_assoc import FilterCriteriaAssoc
from openapi_server.models.filter_criteria_assoc_ho import FilterCriteriaAssocHo
from openapi_server.models.filter_criteria_assoc_tri import FilterCriteriaAssocTri
from openapi_server.models.filter_criteria_nr_mrs import FilterCriteriaNrMrs
from openapi_server.models.filter_criteria_qci1 import FilterCriteriaQci1
from openapi_server.models.links import Links
from openapi_server.models.meas_rep_ue_subscription import MeasRepUeSubscription
from openapi_server.models.meas_ta_subscription import MeasTaSubscription
from openapi_server.models.nr_meas_rep_ue_subscription import NrMeasRepUeSubscription
from openapi_server.models.rab_est_subscription import RabEstSubscription
from openapi_server.models.rab_mod_subscription import RabModSubscription
from openapi_server.models.rab_rel_subscription import RabRelSubscription
from openapi_server.models.s1_bearer_subscription import S1BearerSubscription
from openapi_server.models.s1_bearer_subscription_criteria import S1BearerSubscriptionCriteria
from openapi_server.models.time_stamp import TimeStamp
from openapi_server.models.websock_notif_config import WebsockNotifConfig
from openapi_server import util

from openapi_server.models.ca_reconf_subscription import CaReconfSubscription  # noqa: E501
from openapi_server.models.cell_change_subscription import CellChangeSubscription  # noqa: E501
from openapi_server.models.filter_criteria_assoc import FilterCriteriaAssoc  # noqa: E501
from openapi_server.models.filter_criteria_assoc_ho import FilterCriteriaAssocHo  # noqa: E501
from openapi_server.models.filter_criteria_assoc_tri import FilterCriteriaAssocTri  # noqa: E501
from openapi_server.models.filter_criteria_nr_mrs import FilterCriteriaNrMrs  # noqa: E501
from openapi_server.models.filter_criteria_qci1 import FilterCriteriaQci1  # noqa: E501
from openapi_server.models.links import Links  # noqa: E501
from openapi_server.models.meas_rep_ue_subscription import MeasRepUeSubscription  # noqa: E501
from openapi_server.models.meas_ta_subscription import MeasTaSubscription  # noqa: E501
from openapi_server.models.nr_meas_rep_ue_subscription import NrMeasRepUeSubscription  # noqa: E501
from openapi_server.models.rab_est_subscription import RabEstSubscription  # noqa: E501
from openapi_server.models.rab_mod_subscription import RabModSubscription  # noqa: E501
from openapi_server.models.rab_rel_subscription import RabRelSubscription  # noqa: E501
from openapi_server.models.s1_bearer_subscription import S1BearerSubscription  # noqa: E501
from openapi_server.models.s1_bearer_subscription_criteria import S1BearerSubscriptionCriteria  # noqa: E501
from openapi_server.models.time_stamp import TimeStamp  # noqa: E501
from openapi_server.models.websock_notif_config import WebsockNotifConfig  # noqa: E501

class NotificationPOSTRequestSubscriptionNotification(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, subscription_type=None, callback_reference=None, request_test_notification=None, websock_notif_config=None, links=None, filter_criteria_assoc_ho=None, expiry_deadline=None, filter_criteria_qci=None, filter_criteria_assoc_tri=None, filter_criteria_nr_mrs=None, filter_criteria_assoc=None, event_type=None, s1_bearer_subscription_criteria=None):  # noqa: E501
        """NotificationPOSTRequestSubscriptionNotification - a model defined in OpenAPI

        :param subscription_type: The subscription_type of this NotificationPOSTRequestSubscriptionNotification.  # noqa: E501
        :type subscription_type: str
        :param callback_reference: The callback_reference of this NotificationPOSTRequestSubscriptionNotification.  # noqa: E501
        :type callback_reference: str
        :param request_test_notification: The request_test_notification of this NotificationPOSTRequestSubscriptionNotification.  # noqa: E501
        :type request_test_notification: bool
        :param websock_notif_config: The websock_notif_config of this NotificationPOSTRequestSubscriptionNotification.  # noqa: E501
        :type websock_notif_config: WebsockNotifConfig
        :param links: The links of this NotificationPOSTRequestSubscriptionNotification.  # noqa: E501
        :type links: Links
        :param filter_criteria_assoc_ho: The filter_criteria_assoc_ho of this NotificationPOSTRequestSubscriptionNotification.  # noqa: E501
        :type filter_criteria_assoc_ho: FilterCriteriaAssocHo
        :param expiry_deadline: The expiry_deadline of this NotificationPOSTRequestSubscriptionNotification.  # noqa: E501
        :type expiry_deadline: TimeStamp
        :param filter_criteria_qci: The filter_criteria_qci of this NotificationPOSTRequestSubscriptionNotification.  # noqa: E501
        :type filter_criteria_qci: FilterCriteriaQci1
        :param filter_criteria_assoc_tri: The filter_criteria_assoc_tri of this NotificationPOSTRequestSubscriptionNotification.  # noqa: E501
        :type filter_criteria_assoc_tri: FilterCriteriaAssocTri
        :param filter_criteria_nr_mrs: The filter_criteria_nr_mrs of this NotificationPOSTRequestSubscriptionNotification.  # noqa: E501
        :type filter_criteria_nr_mrs: FilterCriteriaNrMrs
        :param filter_criteria_assoc: The filter_criteria_assoc of this NotificationPOSTRequestSubscriptionNotification.  # noqa: E501
        :type filter_criteria_assoc: FilterCriteriaAssoc
        :param event_type: The event_type of this NotificationPOSTRequestSubscriptionNotification.  # noqa: E501
        :type event_type: List[int]
        :param s1_bearer_subscription_criteria: The s1_bearer_subscription_criteria of this NotificationPOSTRequestSubscriptionNotification.  # noqa: E501
        :type s1_bearer_subscription_criteria: S1BearerSubscriptionCriteria
        """
        self.openapi_types = {
            'subscription_type': str,
            'callback_reference': str,
            'request_test_notification': bool,
            'websock_notif_config': WebsockNotifConfig,
            'links': Links,
            'filter_criteria_assoc_ho': FilterCriteriaAssocHo,
            'expiry_deadline': TimeStamp,
            'filter_criteria_qci': FilterCriteriaQci1,
            'filter_criteria_assoc_tri': FilterCriteriaAssocTri,
            'filter_criteria_nr_mrs': FilterCriteriaNrMrs,
            'filter_criteria_assoc': FilterCriteriaAssoc,
            'event_type': List[int],
            's1_bearer_subscription_criteria': S1BearerSubscriptionCriteria
        }

        self.attribute_map = {
            'subscription_type': 'subscriptionType',
            'callback_reference': 'callbackReference',
            'request_test_notification': 'requestTestNotification',
            'websock_notif_config': 'websockNotifConfig',
            'links': '_links',
            'filter_criteria_assoc_ho': 'filterCriteriaAssocHo',
            'expiry_deadline': 'expiryDeadline',
            'filter_criteria_qci': 'filterCriteriaQci',
            'filter_criteria_assoc_tri': 'filterCriteriaAssocTri',
            'filter_criteria_nr_mrs': 'filterCriteriaNrMrs',
            'filter_criteria_assoc': 'filterCriteriaAssoc',
            'event_type': 'eventType',
            's1_bearer_subscription_criteria': 'S1BearerSubscriptionCriteria'
        }

        self._subscription_type = subscription_type
        self._callback_reference = callback_reference
        self._request_test_notification = request_test_notification
        self._websock_notif_config = websock_notif_config
        self._links = links
        self._filter_criteria_assoc_ho = filter_criteria_assoc_ho
        self._expiry_deadline = expiry_deadline
        self._filter_criteria_qci = filter_criteria_qci
        self._filter_criteria_assoc_tri = filter_criteria_assoc_tri
        self._filter_criteria_nr_mrs = filter_criteria_nr_mrs
        self._filter_criteria_assoc = filter_criteria_assoc
        self._event_type = event_type
        self._s1_bearer_subscription_criteria = s1_bearer_subscription_criteria

    @classmethod
    def from_dict(cls, dikt) -> 'NotificationPOSTRequestSubscriptionNotification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The notificationPOST_request_subscriptionNotification of this NotificationPOSTRequestSubscriptionNotification.  # noqa: E501
        :rtype: NotificationPOSTRequestSubscriptionNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subscription_type(self) -> str:
        """Gets the subscription_type of this NotificationPOSTRequestSubscriptionNotification.

        Shall be set to \"S1BearerSubscription\".  # noqa: E501

        :return: The subscription_type of this NotificationPOSTRequestSubscriptionNotification.
        :rtype: str
        """
        return self._subscription_type

    @subscription_type.setter
    def subscription_type(self, subscription_type: str):
        """Sets the subscription_type of this NotificationPOSTRequestSubscriptionNotification.

        Shall be set to \"S1BearerSubscription\".  # noqa: E501

        :param subscription_type: The subscription_type of this NotificationPOSTRequestSubscriptionNotification.
        :type subscription_type: str
        """
        if subscription_type is None:
            raise ValueError("Invalid value for `subscription_type`, must not be `None`")  # noqa: E501

        self._subscription_type = subscription_type

    @property
    def callback_reference(self) -> str:
        """Gets the callback_reference of this NotificationPOSTRequestSubscriptionNotification.

        URI exposed by the client on which to receive notifications via HTTP. See note.  # noqa: E501

        :return: The callback_reference of this NotificationPOSTRequestSubscriptionNotification.
        :rtype: str
        """
        return self._callback_reference

    @callback_reference.setter
    def callback_reference(self, callback_reference: str):
        """Sets the callback_reference of this NotificationPOSTRequestSubscriptionNotification.

        URI exposed by the client on which to receive notifications via HTTP. See note.  # noqa: E501

        :param callback_reference: The callback_reference of this NotificationPOSTRequestSubscriptionNotification.
        :type callback_reference: str
        """

        self._callback_reference = callback_reference

    @property
    def request_test_notification(self) -> bool:
        """Gets the request_test_notification of this NotificationPOSTRequestSubscriptionNotification.

        Shall be set to TRUE by the service consumer to request a test notification via HTTP on the callbackReference URI, specified in ETSI GS MEC 009 [6], as described in clause 6.12a.   # noqa: E501

        :return: The request_test_notification of this NotificationPOSTRequestSubscriptionNotification.
        :rtype: bool
        """
        return self._request_test_notification

    @request_test_notification.setter
    def request_test_notification(self, request_test_notification: bool):
        """Sets the request_test_notification of this NotificationPOSTRequestSubscriptionNotification.

        Shall be set to TRUE by the service consumer to request a test notification via HTTP on the callbackReference URI, specified in ETSI GS MEC 009 [6], as described in clause 6.12a.   # noqa: E501

        :param request_test_notification: The request_test_notification of this NotificationPOSTRequestSubscriptionNotification.
        :type request_test_notification: bool
        """

        self._request_test_notification = request_test_notification

    @property
    def websock_notif_config(self) -> WebsockNotifConfig:
        """Gets the websock_notif_config of this NotificationPOSTRequestSubscriptionNotification.

        Provides details to negotiate and signal the use of a Websocket connection between RNIS and the service consumer for notifications. See note.  # noqa: E501

        :return: The websock_notif_config of this NotificationPOSTRequestSubscriptionNotification.
        :rtype: WebsockNotifConfig
        """
        return self._websock_notif_config

    @websock_notif_config.setter
    def websock_notif_config(self, websock_notif_config: WebsockNotifConfig):
        """Sets the websock_notif_config of this NotificationPOSTRequestSubscriptionNotification.

        Provides details to negotiate and signal the use of a Websocket connection between RNIS and the service consumer for notifications. See note.  # noqa: E501

        :param websock_notif_config: The websock_notif_config of this NotificationPOSTRequestSubscriptionNotification.
        :type websock_notif_config: WebsockNotifConfig
        """

        self._websock_notif_config = websock_notif_config

    @property
    def links(self) -> Links:
        """Gets the links of this NotificationPOSTRequestSubscriptionNotification.


        :return: The links of this NotificationPOSTRequestSubscriptionNotification.
        :rtype: Links
        """
        return self._links

    @links.setter
    def links(self, links: Links):
        """Sets the links of this NotificationPOSTRequestSubscriptionNotification.


        :param links: The links of this NotificationPOSTRequestSubscriptionNotification.
        :type links: Links
        """

        self._links = links

    @property
    def filter_criteria_assoc_ho(self) -> FilterCriteriaAssocHo:
        """Gets the filter_criteria_assoc_ho of this NotificationPOSTRequestSubscriptionNotification.


        :return: The filter_criteria_assoc_ho of this NotificationPOSTRequestSubscriptionNotification.
        :rtype: FilterCriteriaAssocHo
        """
        return self._filter_criteria_assoc_ho

    @filter_criteria_assoc_ho.setter
    def filter_criteria_assoc_ho(self, filter_criteria_assoc_ho: FilterCriteriaAssocHo):
        """Sets the filter_criteria_assoc_ho of this NotificationPOSTRequestSubscriptionNotification.


        :param filter_criteria_assoc_ho: The filter_criteria_assoc_ho of this NotificationPOSTRequestSubscriptionNotification.
        :type filter_criteria_assoc_ho: FilterCriteriaAssocHo
        """
        if filter_criteria_assoc_ho is None:
            raise ValueError("Invalid value for `filter_criteria_assoc_ho`, must not be `None`")  # noqa: E501

        self._filter_criteria_assoc_ho = filter_criteria_assoc_ho

    @property
    def expiry_deadline(self) -> TimeStamp:
        """Gets the expiry_deadline of this NotificationPOSTRequestSubscriptionNotification.

        Time stamp.  # noqa: E501

        :return: The expiry_deadline of this NotificationPOSTRequestSubscriptionNotification.
        :rtype: TimeStamp
        """
        return self._expiry_deadline

    @expiry_deadline.setter
    def expiry_deadline(self, expiry_deadline: TimeStamp):
        """Sets the expiry_deadline of this NotificationPOSTRequestSubscriptionNotification.

        Time stamp.  # noqa: E501

        :param expiry_deadline: The expiry_deadline of this NotificationPOSTRequestSubscriptionNotification.
        :type expiry_deadline: TimeStamp
        """

        self._expiry_deadline = expiry_deadline

    @property
    def filter_criteria_qci(self) -> FilterCriteriaQci1:
        """Gets the filter_criteria_qci of this NotificationPOSTRequestSubscriptionNotification.


        :return: The filter_criteria_qci of this NotificationPOSTRequestSubscriptionNotification.
        :rtype: FilterCriteriaQci1
        """
        return self._filter_criteria_qci

    @filter_criteria_qci.setter
    def filter_criteria_qci(self, filter_criteria_qci: FilterCriteriaQci1):
        """Sets the filter_criteria_qci of this NotificationPOSTRequestSubscriptionNotification.


        :param filter_criteria_qci: The filter_criteria_qci of this NotificationPOSTRequestSubscriptionNotification.
        :type filter_criteria_qci: FilterCriteriaQci1
        """
        if filter_criteria_qci is None:
            raise ValueError("Invalid value for `filter_criteria_qci`, must not be `None`")  # noqa: E501

        self._filter_criteria_qci = filter_criteria_qci

    @property
    def filter_criteria_assoc_tri(self) -> FilterCriteriaAssocTri:
        """Gets the filter_criteria_assoc_tri of this NotificationPOSTRequestSubscriptionNotification.


        :return: The filter_criteria_assoc_tri of this NotificationPOSTRequestSubscriptionNotification.
        :rtype: FilterCriteriaAssocTri
        """
        return self._filter_criteria_assoc_tri

    @filter_criteria_assoc_tri.setter
    def filter_criteria_assoc_tri(self, filter_criteria_assoc_tri: FilterCriteriaAssocTri):
        """Sets the filter_criteria_assoc_tri of this NotificationPOSTRequestSubscriptionNotification.


        :param filter_criteria_assoc_tri: The filter_criteria_assoc_tri of this NotificationPOSTRequestSubscriptionNotification.
        :type filter_criteria_assoc_tri: FilterCriteriaAssocTri
        """
        if filter_criteria_assoc_tri is None:
            raise ValueError("Invalid value for `filter_criteria_assoc_tri`, must not be `None`")  # noqa: E501

        self._filter_criteria_assoc_tri = filter_criteria_assoc_tri

    @property
    def filter_criteria_nr_mrs(self) -> FilterCriteriaNrMrs:
        """Gets the filter_criteria_nr_mrs of this NotificationPOSTRequestSubscriptionNotification.


        :return: The filter_criteria_nr_mrs of this NotificationPOSTRequestSubscriptionNotification.
        :rtype: FilterCriteriaNrMrs
        """
        return self._filter_criteria_nr_mrs

    @filter_criteria_nr_mrs.setter
    def filter_criteria_nr_mrs(self, filter_criteria_nr_mrs: FilterCriteriaNrMrs):
        """Sets the filter_criteria_nr_mrs of this NotificationPOSTRequestSubscriptionNotification.


        :param filter_criteria_nr_mrs: The filter_criteria_nr_mrs of this NotificationPOSTRequestSubscriptionNotification.
        :type filter_criteria_nr_mrs: FilterCriteriaNrMrs
        """
        if filter_criteria_nr_mrs is None:
            raise ValueError("Invalid value for `filter_criteria_nr_mrs`, must not be `None`")  # noqa: E501

        self._filter_criteria_nr_mrs = filter_criteria_nr_mrs

    @property
    def filter_criteria_assoc(self) -> FilterCriteriaAssoc:
        """Gets the filter_criteria_assoc of this NotificationPOSTRequestSubscriptionNotification.


        :return: The filter_criteria_assoc of this NotificationPOSTRequestSubscriptionNotification.
        :rtype: FilterCriteriaAssoc
        """
        return self._filter_criteria_assoc

    @filter_criteria_assoc.setter
    def filter_criteria_assoc(self, filter_criteria_assoc: FilterCriteriaAssoc):
        """Sets the filter_criteria_assoc of this NotificationPOSTRequestSubscriptionNotification.


        :param filter_criteria_assoc: The filter_criteria_assoc of this NotificationPOSTRequestSubscriptionNotification.
        :type filter_criteria_assoc: FilterCriteriaAssoc
        """
        if filter_criteria_assoc is None:
            raise ValueError("Invalid value for `filter_criteria_assoc`, must not be `None`")  # noqa: E501

        self._filter_criteria_assoc = filter_criteria_assoc

    @property
    def event_type(self) -> List[int]:
        """Gets the event_type of this NotificationPOSTRequestSubscriptionNotification.

        Description of the subscribed event. The event is included both in the request and in the response.  For the eventType, the following values are currently defined: 0 = RESERVED. 1 = S1_BEARER_ESTABLISH. 2 = S1_BEARER_MODIFY. 3 = S1_BEARER_RELEASE.  # noqa: E501

        :return: The event_type of this NotificationPOSTRequestSubscriptionNotification.
        :rtype: List[int]
        """
        return self._event_type

    @event_type.setter
    def event_type(self, event_type: List[int]):
        """Sets the event_type of this NotificationPOSTRequestSubscriptionNotification.

        Description of the subscribed event. The event is included both in the request and in the response.  For the eventType, the following values are currently defined: 0 = RESERVED. 1 = S1_BEARER_ESTABLISH. 2 = S1_BEARER_MODIFY. 3 = S1_BEARER_RELEASE.  # noqa: E501

        :param event_type: The event_type of this NotificationPOSTRequestSubscriptionNotification.
        :type event_type: List[int]
        """
        if event_type is None:
            raise ValueError("Invalid value for `event_type`, must not be `None`")  # noqa: E501
        if event_type is not None and len(event_type) < 1:
            raise ValueError("Invalid value for `event_type`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._event_type = event_type

    @property
    def s1_bearer_subscription_criteria(self) -> S1BearerSubscriptionCriteria:
        """Gets the s1_bearer_subscription_criteria of this NotificationPOSTRequestSubscriptionNotification.


        :return: The s1_bearer_subscription_criteria of this NotificationPOSTRequestSubscriptionNotification.
        :rtype: S1BearerSubscriptionCriteria
        """
        return self._s1_bearer_subscription_criteria

    @s1_bearer_subscription_criteria.setter
    def s1_bearer_subscription_criteria(self, s1_bearer_subscription_criteria: S1BearerSubscriptionCriteria):
        """Sets the s1_bearer_subscription_criteria of this NotificationPOSTRequestSubscriptionNotification.


        :param s1_bearer_subscription_criteria: The s1_bearer_subscription_criteria of this NotificationPOSTRequestSubscriptionNotification.
        :type s1_bearer_subscription_criteria: S1BearerSubscriptionCriteria
        """
        if s1_bearer_subscription_criteria is None:
            raise ValueError("Invalid value for `s1_bearer_subscription_criteria`, must not be `None`")  # noqa: E501

        self._s1_bearer_subscription_criteria = s1_bearer_subscription_criteria
