from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.plmn import Plmn
from openapi_server import util

from openapi_server.models.plmn import Plmn  # noqa: E501

class NrBNCellInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, nr_bn_cell_plmn=None, nr_bn_cell_gid=None):  # noqa: E501
        """NrBNCellInfo - a model defined in OpenAPI

        :param nr_bn_cell_plmn: The nr_bn_cell_plmn of this NrBNCellInfo.  # noqa: E501
        :type nr_bn_cell_plmn: List[Plmn]
        :param nr_bn_cell_gid: The nr_bn_cell_gid of this NrBNCellInfo.  # noqa: E501
        :type nr_bn_cell_gid: str
        """
        self.openapi_types = {
            'nr_bn_cell_plmn': List[Plmn],
            'nr_bn_cell_gid': str
        }

        self.attribute_map = {
            'nr_bn_cell_plmn': 'nrBNCellPlmn',
            'nr_bn_cell_gid': 'nrBNCellGId'
        }

        self._nr_bn_cell_plmn = nr_bn_cell_plmn
        self._nr_bn_cell_gid = nr_bn_cell_gid

    @classmethod
    def from_dict(cls, dikt) -> 'NrBNCellInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NrBNCellInfo of this NrBNCellInfo.  # noqa: E501
        :rtype: NrBNCellInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nr_bn_cell_plmn(self) -> List[Plmn]:
        """Gets the nr_bn_cell_plmn of this NrBNCellInfo.

        Public land mobile network identities.  # noqa: E501

        :return: The nr_bn_cell_plmn of this NrBNCellInfo.
        :rtype: List[Plmn]
        """
        return self._nr_bn_cell_plmn

    @nr_bn_cell_plmn.setter
    def nr_bn_cell_plmn(self, nr_bn_cell_plmn: List[Plmn]):
        """Sets the nr_bn_cell_plmn of this NrBNCellInfo.

        Public land mobile network identities.  # noqa: E501

        :param nr_bn_cell_plmn: The nr_bn_cell_plmn of this NrBNCellInfo.
        :type nr_bn_cell_plmn: List[Plmn]
        """
        if nr_bn_cell_plmn is None:
            raise ValueError("Invalid value for `nr_bn_cell_plmn`, must not be `None`")  # noqa: E501
        if nr_bn_cell_plmn is not None and len(nr_bn_cell_plmn) < 1:
            raise ValueError("Invalid value for `nr_bn_cell_plmn`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._nr_bn_cell_plmn = nr_bn_cell_plmn

    @property
    def nr_bn_cell_gid(self) -> str:
        """Gets the nr_bn_cell_gid of this NrBNCellInfo.

        Cell Global Identifier, as defined in ETSI TS 138 331 [i.13].  # noqa: E501

        :return: The nr_bn_cell_gid of this NrBNCellInfo.
        :rtype: str
        """
        return self._nr_bn_cell_gid

    @nr_bn_cell_gid.setter
    def nr_bn_cell_gid(self, nr_bn_cell_gid: str):
        """Sets the nr_bn_cell_gid of this NrBNCellInfo.

        Cell Global Identifier, as defined in ETSI TS 138 331 [i.13].  # noqa: E501

        :param nr_bn_cell_gid: The nr_bn_cell_gid of this NrBNCellInfo.
        :type nr_bn_cell_gid: str
        """
        if nr_bn_cell_gid is None:
            raise ValueError("Invalid value for `nr_bn_cell_gid`, must not be `None`")  # noqa: E501

        self._nr_bn_cell_gid = nr_bn_cell_gid
