from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.associate_id import AssociateId
from openapi_server.models.eutra_neigh_cell_meas_info import EutraNeighCellMeasInfo
from openapi_server.models.link_type import LinkType
from openapi_server.models.links import Links
from openapi_server.models.nr_neigh_cell_meas_info import NrNeighCellMeasInfo
from openapi_server.models.serv_cell_meas_info import ServCellMeasInfo
from openapi_server.models.time_stamp import TimeStamp
from openapi_server.models.trigger_nr import TriggerNr
from openapi_server import util

from openapi_server.models.associate_id import AssociateId  # noqa: E501
from openapi_server.models.eutra_neigh_cell_meas_info import EutraNeighCellMeasInfo  # noqa: E501
from openapi_server.models.link_type import LinkType  # noqa: E501
from openapi_server.models.links import Links  # noqa: E501
from openapi_server.models.nr_neigh_cell_meas_info import NrNeighCellMeasInfo  # noqa: E501
from openapi_server.models.serv_cell_meas_info import ServCellMeasInfo  # noqa: E501
from openapi_server.models.time_stamp import TimeStamp  # noqa: E501
from openapi_server.models.trigger_nr import TriggerNr  # noqa: E501

class NrMeasRepUeNotification(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, notification_type=None, time_stamp=None, associate_id=None, trigger_nr=None, serv_cell_meas_info=None, nr_neigh_cell_meas_info=None, eutra_neigh_cell_meas_info=None, links=None, subscription=None):  # noqa: E501
        """NrMeasRepUeNotification - a model defined in OpenAPI

        :param notification_type: The notification_type of this NrMeasRepUeNotification.  # noqa: E501
        :type notification_type: str
        :param time_stamp: The time_stamp of this NrMeasRepUeNotification.  # noqa: E501
        :type time_stamp: TimeStamp
        :param associate_id: The associate_id of this NrMeasRepUeNotification.  # noqa: E501
        :type associate_id: List[AssociateId]
        :param trigger_nr: The trigger_nr of this NrMeasRepUeNotification.  # noqa: E501
        :type trigger_nr: TriggerNr
        :param serv_cell_meas_info: The serv_cell_meas_info of this NrMeasRepUeNotification.  # noqa: E501
        :type serv_cell_meas_info: List[ServCellMeasInfo]
        :param nr_neigh_cell_meas_info: The nr_neigh_cell_meas_info of this NrMeasRepUeNotification.  # noqa: E501
        :type nr_neigh_cell_meas_info: List[NrNeighCellMeasInfo]
        :param eutra_neigh_cell_meas_info: The eutra_neigh_cell_meas_info of this NrMeasRepUeNotification.  # noqa: E501
        :type eutra_neigh_cell_meas_info: List[EutraNeighCellMeasInfo]
        :param links: The links of this NrMeasRepUeNotification.  # noqa: E501
        :type links: List[Links]
        :param subscription: The subscription of this NrMeasRepUeNotification.  # noqa: E501
        :type subscription: List[LinkType]
        """
        self.openapi_types = {
            'notification_type': str,
            'time_stamp': TimeStamp,
            'associate_id': List[AssociateId],
            'trigger_nr': TriggerNr,
            'serv_cell_meas_info': List[ServCellMeasInfo],
            'nr_neigh_cell_meas_info': List[NrNeighCellMeasInfo],
            'eutra_neigh_cell_meas_info': List[EutraNeighCellMeasInfo],
            'links': List[Links],
            'subscription': List[LinkType]
        }

        self.attribute_map = {
            'notification_type': 'notificationType',
            'time_stamp': 'timeStamp',
            'associate_id': 'associateId',
            'trigger_nr': 'triggerNr',
            'serv_cell_meas_info': 'servCellMeasInfo',
            'nr_neigh_cell_meas_info': 'nrNeighCellMeasInfo',
            'eutra_neigh_cell_meas_info': 'eutraNeighCellMeasInfo',
            'links': '_links',
            'subscription': 'subscription'
        }

        self._notification_type = notification_type
        self._time_stamp = time_stamp
        self._associate_id = associate_id
        self._trigger_nr = trigger_nr
        self._serv_cell_meas_info = serv_cell_meas_info
        self._nr_neigh_cell_meas_info = nr_neigh_cell_meas_info
        self._eutra_neigh_cell_meas_info = eutra_neigh_cell_meas_info
        self._links = links
        self._subscription = subscription

    @classmethod
    def from_dict(cls, dikt) -> 'NrMeasRepUeNotification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NrMeasRepUeNotification of this NrMeasRepUeNotification.  # noqa: E501
        :rtype: NrMeasRepUeNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_type(self) -> str:
        """Gets the notification_type of this NrMeasRepUeNotification.

        Shall be set to \"NrMeasRepUeNotification\".  # noqa: E501

        :return: The notification_type of this NrMeasRepUeNotification.
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type: str):
        """Sets the notification_type of this NrMeasRepUeNotification.

        Shall be set to \"NrMeasRepUeNotification\".  # noqa: E501

        :param notification_type: The notification_type of this NrMeasRepUeNotification.
        :type notification_type: str
        """
        if notification_type is None:
            raise ValueError("Invalid value for `notification_type`, must not be `None`")  # noqa: E501

        self._notification_type = notification_type

    @property
    def time_stamp(self) -> TimeStamp:
        """Gets the time_stamp of this NrMeasRepUeNotification.

        Time stamp.  # noqa: E501

        :return: The time_stamp of this NrMeasRepUeNotification.
        :rtype: TimeStamp
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: TimeStamp):
        """Sets the time_stamp of this NrMeasRepUeNotification.

        Time stamp.  # noqa: E501

        :param time_stamp: The time_stamp of this NrMeasRepUeNotification.
        :type time_stamp: TimeStamp
        """

        self._time_stamp = time_stamp

    @property
    def associate_id(self) -> List[AssociateId]:
        """Gets the associate_id of this NrMeasRepUeNotification.

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :return: The associate_id of this NrMeasRepUeNotification.
        :rtype: List[AssociateId]
        """
        return self._associate_id

    @associate_id.setter
    def associate_id(self, associate_id: List[AssociateId]):
        """Sets the associate_id of this NrMeasRepUeNotification.

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :param associate_id: The associate_id of this NrMeasRepUeNotification.
        :type associate_id: List[AssociateId]
        """
        if associate_id is not None and len(associate_id) < 0:
            raise ValueError("Invalid value for `associate_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._associate_id = associate_id

    @property
    def trigger_nr(self) -> TriggerNr:
        """Gets the trigger_nr of this NrMeasRepUeNotification.

        Corresponds to a specific 5G UE Measurement Report trigger.  # noqa: E501

        :return: The trigger_nr of this NrMeasRepUeNotification.
        :rtype: TriggerNr
        """
        return self._trigger_nr

    @trigger_nr.setter
    def trigger_nr(self, trigger_nr: TriggerNr):
        """Sets the trigger_nr of this NrMeasRepUeNotification.

        Corresponds to a specific 5G UE Measurement Report trigger.  # noqa: E501

        :param trigger_nr: The trigger_nr of this NrMeasRepUeNotification.
        :type trigger_nr: TriggerNr
        """
        if trigger_nr is None:
            raise ValueError("Invalid value for `trigger_nr`, must not be `None`")  # noqa: E501

        self._trigger_nr = trigger_nr

    @property
    def serv_cell_meas_info(self) -> List[ServCellMeasInfo]:
        """Gets the serv_cell_meas_info of this NrMeasRepUeNotification.


        :return: The serv_cell_meas_info of this NrMeasRepUeNotification.
        :rtype: List[ServCellMeasInfo]
        """
        return self._serv_cell_meas_info

    @serv_cell_meas_info.setter
    def serv_cell_meas_info(self, serv_cell_meas_info: List[ServCellMeasInfo]):
        """Sets the serv_cell_meas_info of this NrMeasRepUeNotification.


        :param serv_cell_meas_info: The serv_cell_meas_info of this NrMeasRepUeNotification.
        :type serv_cell_meas_info: List[ServCellMeasInfo]
        """

        self._serv_cell_meas_info = serv_cell_meas_info

    @property
    def nr_neigh_cell_meas_info(self) -> List[NrNeighCellMeasInfo]:
        """Gets the nr_neigh_cell_meas_info of this NrMeasRepUeNotification.


        :return: The nr_neigh_cell_meas_info of this NrMeasRepUeNotification.
        :rtype: List[NrNeighCellMeasInfo]
        """
        return self._nr_neigh_cell_meas_info

    @nr_neigh_cell_meas_info.setter
    def nr_neigh_cell_meas_info(self, nr_neigh_cell_meas_info: List[NrNeighCellMeasInfo]):
        """Sets the nr_neigh_cell_meas_info of this NrMeasRepUeNotification.


        :param nr_neigh_cell_meas_info: The nr_neigh_cell_meas_info of this NrMeasRepUeNotification.
        :type nr_neigh_cell_meas_info: List[NrNeighCellMeasInfo]
        """

        self._nr_neigh_cell_meas_info = nr_neigh_cell_meas_info

    @property
    def eutra_neigh_cell_meas_info(self) -> List[EutraNeighCellMeasInfo]:
        """Gets the eutra_neigh_cell_meas_info of this NrMeasRepUeNotification.


        :return: The eutra_neigh_cell_meas_info of this NrMeasRepUeNotification.
        :rtype: List[EutraNeighCellMeasInfo]
        """
        return self._eutra_neigh_cell_meas_info

    @eutra_neigh_cell_meas_info.setter
    def eutra_neigh_cell_meas_info(self, eutra_neigh_cell_meas_info: List[EutraNeighCellMeasInfo]):
        """Sets the eutra_neigh_cell_meas_info of this NrMeasRepUeNotification.


        :param eutra_neigh_cell_meas_info: The eutra_neigh_cell_meas_info of this NrMeasRepUeNotification.
        :type eutra_neigh_cell_meas_info: List[EutraNeighCellMeasInfo]
        """

        self._eutra_neigh_cell_meas_info = eutra_neigh_cell_meas_info

    @property
    def links(self) -> List[Links]:
        """Gets the links of this NrMeasRepUeNotification.

        Links to resources related to this notification.  # noqa: E501

        :return: The links of this NrMeasRepUeNotification.
        :rtype: List[Links]
        """
        return self._links

    @links.setter
    def links(self, links: List[Links]):
        """Sets the links of this NrMeasRepUeNotification.

        Links to resources related to this notification.  # noqa: E501

        :param links: The links of this NrMeasRepUeNotification.
        :type links: List[Links]
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def subscription(self) -> List[LinkType]:
        """Gets the subscription of this NrMeasRepUeNotification.

        A link to the related subscription.  # noqa: E501

        :return: The subscription of this NrMeasRepUeNotification.
        :rtype: List[LinkType]
        """
        return self._subscription

    @subscription.setter
    def subscription(self, subscription: List[LinkType]):
        """Sets the subscription of this NrMeasRepUeNotification.

        A link to the related subscription.  # noqa: E501

        :param subscription: The subscription of this NrMeasRepUeNotification.
        :type subscription: List[LinkType]
        """
        if subscription is None:
            raise ValueError("Invalid value for `subscription`, must not be `None`")  # noqa: E501

        self._subscription = subscription
