from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.plmn import Plmn
from openapi_server.models.time_stamp import TimeStamp
from openapi_server import util

from openapi_server.models.plmn import Plmn  # noqa: E501
from openapi_server.models.time_stamp import TimeStamp  # noqa: E501

class PlmnInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, time_stamp=None, app_instance_id=None, plmn=None):  # noqa: E501
        """PlmnInfo - a model defined in OpenAPI

        :param time_stamp: The time_stamp of this PlmnInfo.  # noqa: E501
        :type time_stamp: TimeStamp
        :param app_instance_id: The app_instance_id of this PlmnInfo.  # noqa: E501
        :type app_instance_id: str
        :param plmn: The plmn of this PlmnInfo.  # noqa: E501
        :type plmn: List[Plmn]
        """
        self.openapi_types = {
            'time_stamp': TimeStamp,
            'app_instance_id': str,
            'plmn': List[Plmn]
        }

        self.attribute_map = {
            'time_stamp': 'timeStamp',
            'app_instance_id': 'appInstanceId',
            'plmn': 'plmn'
        }

        self._time_stamp = time_stamp
        self._app_instance_id = app_instance_id
        self._plmn = plmn

    @classmethod
    def from_dict(cls, dikt) -> 'PlmnInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlmnInfo of this PlmnInfo.  # noqa: E501
        :rtype: PlmnInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time_stamp(self) -> TimeStamp:
        """Gets the time_stamp of this PlmnInfo.

        Time stamp.  # noqa: E501

        :return: The time_stamp of this PlmnInfo.
        :rtype: TimeStamp
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: TimeStamp):
        """Sets the time_stamp of this PlmnInfo.

        Time stamp.  # noqa: E501

        :param time_stamp: The time_stamp of this PlmnInfo.
        :type time_stamp: TimeStamp
        """

        self._time_stamp = time_stamp

    @property
    def app_instance_id(self) -> str:
        """Gets the app_instance_id of this PlmnInfo.

        Unique identifier for the MEC application instance.  # noqa: E501

        :return: The app_instance_id of this PlmnInfo.
        :rtype: str
        """
        return self._app_instance_id

    @app_instance_id.setter
    def app_instance_id(self, app_instance_id: str):
        """Sets the app_instance_id of this PlmnInfo.

        Unique identifier for the MEC application instance.  # noqa: E501

        :param app_instance_id: The app_instance_id of this PlmnInfo.
        :type app_instance_id: str
        """
        if app_instance_id is None:
            raise ValueError("Invalid value for `app_instance_id`, must not be `None`")  # noqa: E501

        self._app_instance_id = app_instance_id

    @property
    def plmn(self) -> List[Plmn]:
        """Gets the plmn of this PlmnInfo.

        Public Land Mobile Network Identity.  # noqa: E501

        :return: The plmn of this PlmnInfo.
        :rtype: List[Plmn]
        """
        return self._plmn

    @plmn.setter
    def plmn(self, plmn: List[Plmn]):
        """Sets the plmn of this PlmnInfo.

        Public Land Mobile Network Identity.  # noqa: E501

        :param plmn: The plmn of this PlmnInfo.
        :type plmn: List[Plmn]
        """
        if plmn is None:
            raise ValueError("Invalid value for `plmn`, must not be `None`")  # noqa: E501
        if plmn is not None and len(plmn) < 1:
            raise ValueError("Invalid value for `plmn`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._plmn = plmn
