from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.rab_info import RabInfo
from openapi_server import util

from openapi_server.models.rab_info import RabInfo  # noqa: E501

class QueriesRabinfoGET200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, rab_info=None):  # noqa: E501
        """QueriesRabinfoGET200Response - a model defined in OpenAPI

        :param rab_info: The rab_info of this QueriesRabinfoGET200Response.  # noqa: E501
        :type rab_info: RabInfo
        """
        self.openapi_types = {
            'rab_info': RabInfo
        }

        self.attribute_map = {
            'rab_info': 'RabInfo'
        }

        self._rab_info = rab_info

    @classmethod
    def from_dict(cls, dikt) -> 'QueriesRabinfoGET200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueriesRabinfoGET_200_response of this QueriesRabinfoGET200Response.  # noqa: E501
        :rtype: QueriesRabinfoGET200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rab_info(self) -> RabInfo:
        """Gets the rab_info of this QueriesRabinfoGET200Response.


        :return: The rab_info of this QueriesRabinfoGET200Response.
        :rtype: RabInfo
        """
        return self._rab_info

    @rab_info.setter
    def rab_info(self, rab_info: RabInfo):
        """Sets the rab_info of this QueriesRabinfoGET200Response.


        :param rab_info: The rab_info of this QueriesRabinfoGET200Response.
        :type rab_info: RabInfo
        """

        self._rab_info = rab_info
