from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.s1_bearer_info import S1BearerInfo
from openapi_server import util

from openapi_server.models.s1_bearer_info import S1BearerInfo  # noqa: E501

class QueriesS1BearerinfoGET200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, s1_bearer_info=None):  # noqa: E501
        """QueriesS1BearerinfoGET200Response - a model defined in OpenAPI

        :param s1_bearer_info: The s1_bearer_info of this QueriesS1BearerinfoGET200Response.  # noqa: E501
        :type s1_bearer_info: S1BearerInfo
        """
        self.openapi_types = {
            's1_bearer_info': S1BearerInfo
        }

        self.attribute_map = {
            's1_bearer_info': 'S1BearerInfo'
        }

        self._s1_bearer_info = s1_bearer_info

    @classmethod
    def from_dict(cls, dikt) -> 'QueriesS1BearerinfoGET200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueriesS1BearerinfoGET_200_response of this QueriesS1BearerinfoGET200Response.  # noqa: E501
        :rtype: QueriesS1BearerinfoGET200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def s1_bearer_info(self) -> S1BearerInfo:
        """Gets the s1_bearer_info of this QueriesS1BearerinfoGET200Response.


        :return: The s1_bearer_info of this QueriesS1BearerinfoGET200Response.
        :rtype: S1BearerInfo
        """
        return self._s1_bearer_info

    @s1_bearer_info.setter
    def s1_bearer_info(self, s1_bearer_info: S1BearerInfo):
        """Sets the s1_bearer_info of this QueriesS1BearerinfoGET200Response.


        :param s1_bearer_info: The s1_bearer_info of this QueriesS1BearerinfoGET200Response.
        :type s1_bearer_info: S1BearerInfo
        """

        self._s1_bearer_info = s1_bearer_info
