from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.filter_criteria_qci import FilterCriteriaQci
from openapi_server.models.links import Links
from openapi_server.models.time_stamp import TimeStamp
from openapi_server.models.websock_notif_config import WebsockNotifConfig
from openapi_server import util

from openapi_server.models.filter_criteria_qci import FilterCriteriaQci  # noqa: E501
from openapi_server.models.links import Links  # noqa: E501
from openapi_server.models.time_stamp import TimeStamp  # noqa: E501
from openapi_server.models.websock_notif_config import WebsockNotifConfig  # noqa: E501

class RabEstSubscription(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, subscription_type=None, callback_reference=None, request_test_notification=None, websock_notif_config=None, links=None, filter_criteria_qci=None, expiry_deadline=None):  # noqa: E501
        """RabEstSubscription - a model defined in OpenAPI

        :param subscription_type: The subscription_type of this RabEstSubscription.  # noqa: E501
        :type subscription_type: str
        :param callback_reference: The callback_reference of this RabEstSubscription.  # noqa: E501
        :type callback_reference: str
        :param request_test_notification: The request_test_notification of this RabEstSubscription.  # noqa: E501
        :type request_test_notification: bool
        :param websock_notif_config: The websock_notif_config of this RabEstSubscription.  # noqa: E501
        :type websock_notif_config: WebsockNotifConfig
        :param links: The links of this RabEstSubscription.  # noqa: E501
        :type links: Links
        :param filter_criteria_qci: The filter_criteria_qci of this RabEstSubscription.  # noqa: E501
        :type filter_criteria_qci: FilterCriteriaQci
        :param expiry_deadline: The expiry_deadline of this RabEstSubscription.  # noqa: E501
        :type expiry_deadline: TimeStamp
        """
        self.openapi_types = {
            'subscription_type': str,
            'callback_reference': str,
            'request_test_notification': bool,
            'websock_notif_config': WebsockNotifConfig,
            'links': Links,
            'filter_criteria_qci': FilterCriteriaQci,
            'expiry_deadline': TimeStamp
        }

        self.attribute_map = {
            'subscription_type': 'subscriptionType',
            'callback_reference': 'callbackReference',
            'request_test_notification': 'requestTestNotification',
            'websock_notif_config': 'websockNotifConfig',
            'links': '_links',
            'filter_criteria_qci': 'filterCriteriaQci',
            'expiry_deadline': 'expiryDeadline'
        }

        self._subscription_type = subscription_type
        self._callback_reference = callback_reference
        self._request_test_notification = request_test_notification
        self._websock_notif_config = websock_notif_config
        self._links = links
        self._filter_criteria_qci = filter_criteria_qci
        self._expiry_deadline = expiry_deadline

    @classmethod
    def from_dict(cls, dikt) -> 'RabEstSubscription':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RabEstSubscription of this RabEstSubscription.  # noqa: E501
        :rtype: RabEstSubscription
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subscription_type(self) -> str:
        """Gets the subscription_type of this RabEstSubscription.

        Shall be set to \"RabEstSubscription\".  # noqa: E501

        :return: The subscription_type of this RabEstSubscription.
        :rtype: str
        """
        return self._subscription_type

    @subscription_type.setter
    def subscription_type(self, subscription_type: str):
        """Sets the subscription_type of this RabEstSubscription.

        Shall be set to \"RabEstSubscription\".  # noqa: E501

        :param subscription_type: The subscription_type of this RabEstSubscription.
        :type subscription_type: str
        """
        if subscription_type is None:
            raise ValueError("Invalid value for `subscription_type`, must not be `None`")  # noqa: E501

        self._subscription_type = subscription_type

    @property
    def callback_reference(self) -> str:
        """Gets the callback_reference of this RabEstSubscription.

        URI exposed by the client on which to receive notifications via HTTP. See note.  # noqa: E501

        :return: The callback_reference of this RabEstSubscription.
        :rtype: str
        """
        return self._callback_reference

    @callback_reference.setter
    def callback_reference(self, callback_reference: str):
        """Sets the callback_reference of this RabEstSubscription.

        URI exposed by the client on which to receive notifications via HTTP. See note.  # noqa: E501

        :param callback_reference: The callback_reference of this RabEstSubscription.
        :type callback_reference: str
        """

        self._callback_reference = callback_reference

    @property
    def request_test_notification(self) -> bool:
        """Gets the request_test_notification of this RabEstSubscription.

        Shall be set to TRUE by the service consumer to request a test notification via HTTP on the callbackReference URI, specified in ETSI GS MEC 009 [6], as described in clause 6.12a.   # noqa: E501

        :return: The request_test_notification of this RabEstSubscription.
        :rtype: bool
        """
        return self._request_test_notification

    @request_test_notification.setter
    def request_test_notification(self, request_test_notification: bool):
        """Sets the request_test_notification of this RabEstSubscription.

        Shall be set to TRUE by the service consumer to request a test notification via HTTP on the callbackReference URI, specified in ETSI GS MEC 009 [6], as described in clause 6.12a.   # noqa: E501

        :param request_test_notification: The request_test_notification of this RabEstSubscription.
        :type request_test_notification: bool
        """

        self._request_test_notification = request_test_notification

    @property
    def websock_notif_config(self) -> WebsockNotifConfig:
        """Gets the websock_notif_config of this RabEstSubscription.

        Provides details to negotiate and signal the use of a Websocket connection between RNIS and the service consumer for notifications. See note.  # noqa: E501

        :return: The websock_notif_config of this RabEstSubscription.
        :rtype: WebsockNotifConfig
        """
        return self._websock_notif_config

    @websock_notif_config.setter
    def websock_notif_config(self, websock_notif_config: WebsockNotifConfig):
        """Sets the websock_notif_config of this RabEstSubscription.

        Provides details to negotiate and signal the use of a Websocket connection between RNIS and the service consumer for notifications. See note.  # noqa: E501

        :param websock_notif_config: The websock_notif_config of this RabEstSubscription.
        :type websock_notif_config: WebsockNotifConfig
        """

        self._websock_notif_config = websock_notif_config

    @property
    def links(self) -> Links:
        """Gets the links of this RabEstSubscription.


        :return: The links of this RabEstSubscription.
        :rtype: Links
        """
        return self._links

    @links.setter
    def links(self, links: Links):
        """Sets the links of this RabEstSubscription.


        :param links: The links of this RabEstSubscription.
        :type links: Links
        """

        self._links = links

    @property
    def filter_criteria_qci(self) -> FilterCriteriaQci:
        """Gets the filter_criteria_qci of this RabEstSubscription.


        :return: The filter_criteria_qci of this RabEstSubscription.
        :rtype: FilterCriteriaQci
        """
        return self._filter_criteria_qci

    @filter_criteria_qci.setter
    def filter_criteria_qci(self, filter_criteria_qci: FilterCriteriaQci):
        """Sets the filter_criteria_qci of this RabEstSubscription.


        :param filter_criteria_qci: The filter_criteria_qci of this RabEstSubscription.
        :type filter_criteria_qci: FilterCriteriaQci
        """
        if filter_criteria_qci is None:
            raise ValueError("Invalid value for `filter_criteria_qci`, must not be `None`")  # noqa: E501

        self._filter_criteria_qci = filter_criteria_qci

    @property
    def expiry_deadline(self) -> TimeStamp:
        """Gets the expiry_deadline of this RabEstSubscription.

        Time stamp.  # noqa: E501

        :return: The expiry_deadline of this RabEstSubscription.
        :rtype: TimeStamp
        """
        return self._expiry_deadline

    @expiry_deadline.setter
    def expiry_deadline(self, expiry_deadline: TimeStamp):
        """Sets the expiry_deadline of this RabEstSubscription.

        Time stamp.  # noqa: E501

        :param expiry_deadline: The expiry_deadline of this RabEstSubscription.
        :type expiry_deadline: TimeStamp
        """

        self._expiry_deadline = expiry_deadline
