from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.cell_user_info import CellUserInfo
from openapi_server.models.time_stamp import TimeStamp
from openapi_server import util

from openapi_server.models.cell_user_info import CellUserInfo  # noqa: E501
from openapi_server.models.time_stamp import TimeStamp  # noqa: E501

class RabInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, time_stamp=None, app_instance_id=None, request_id=None, cell_user_info=None):  # noqa: E501
        """RabInfo - a model defined in OpenAPI

        :param time_stamp: The time_stamp of this RabInfo.  # noqa: E501
        :type time_stamp: TimeStamp
        :param app_instance_id: The app_instance_id of this RabInfo.  # noqa: E501
        :type app_instance_id: str
        :param request_id: The request_id of this RabInfo.  # noqa: E501
        :type request_id: str
        :param cell_user_info: The cell_user_info of this RabInfo.  # noqa: E501
        :type cell_user_info: List[CellUserInfo]
        """
        self.openapi_types = {
            'time_stamp': TimeStamp,
            'app_instance_id': str,
            'request_id': str,
            'cell_user_info': List[CellUserInfo]
        }

        self.attribute_map = {
            'time_stamp': 'timeStamp',
            'app_instance_id': 'appInstanceId',
            'request_id': 'requestId',
            'cell_user_info': 'cellUserInfo'
        }

        self._time_stamp = time_stamp
        self._app_instance_id = app_instance_id
        self._request_id = request_id
        self._cell_user_info = cell_user_info

    @classmethod
    def from_dict(cls, dikt) -> 'RabInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RabInfo of this RabInfo.  # noqa: E501
        :rtype: RabInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time_stamp(self) -> TimeStamp:
        """Gets the time_stamp of this RabInfo.

        Time stamp.  # noqa: E501

        :return: The time_stamp of this RabInfo.
        :rtype: TimeStamp
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: TimeStamp):
        """Sets the time_stamp of this RabInfo.

        Time stamp.  # noqa: E501

        :param time_stamp: The time_stamp of this RabInfo.
        :type time_stamp: TimeStamp
        """

        self._time_stamp = time_stamp

    @property
    def app_instance_id(self) -> str:
        """Gets the app_instance_id of this RabInfo.

        Unique identifier for the MEC application instance.  # noqa: E501

        :return: The app_instance_id of this RabInfo.
        :rtype: str
        """
        return self._app_instance_id

    @app_instance_id.setter
    def app_instance_id(self, app_instance_id: str):
        """Sets the app_instance_id of this RabInfo.

        Unique identifier for the MEC application instance.  # noqa: E501

        :param app_instance_id: The app_instance_id of this RabInfo.
        :type app_instance_id: str
        """
        if app_instance_id is None:
            raise ValueError("Invalid value for `app_instance_id`, must not be `None`")  # noqa: E501

        self._app_instance_id = app_instance_id

    @property
    def request_id(self) -> str:
        """Gets the request_id of this RabInfo.

        Unique identifier allocated by the service consumer for the RAB Information request.  # noqa: E501

        :return: The request_id of this RabInfo.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id: str):
        """Sets the request_id of this RabInfo.

        Unique identifier allocated by the service consumer for the RAB Information request.  # noqa: E501

        :param request_id: The request_id of this RabInfo.
        :type request_id: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def cell_user_info(self) -> List[CellUserInfo]:
        """Gets the cell_user_info of this RabInfo.


        :return: The cell_user_info of this RabInfo.
        :rtype: List[CellUserInfo]
        """
        return self._cell_user_info

    @cell_user_info.setter
    def cell_user_info(self, cell_user_info: List[CellUserInfo]):
        """Sets the cell_user_info of this RabInfo.


        :param cell_user_info: The cell_user_info of this RabInfo.
        :type cell_user_info: List[CellUserInfo]
        """

        self._cell_user_info = cell_user_info
