from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.associate_id import AssociateId
from openapi_server.models.ecgi import Ecgi
from openapi_server.models.erab_qos_parameters1 import ErabQosParameters1
from openapi_server.models.link_type import LinkType
from openapi_server.models.links import Links
from openapi_server.models.temp_ue_id1 import TempUeId1
from openapi_server.models.time_stamp import TimeStamp
from openapi_server import util

from openapi_server.models.associate_id import AssociateId  # noqa: E501
from openapi_server.models.ecgi import Ecgi  # noqa: E501
from openapi_server.models.erab_qos_parameters1 import ErabQosParameters1  # noqa: E501
from openapi_server.models.link_type import LinkType  # noqa: E501
from openapi_server.models.links import Links  # noqa: E501
from openapi_server.models.temp_ue_id1 import TempUeId1  # noqa: E501
from openapi_server.models.time_stamp import TimeStamp  # noqa: E501

class RabEstNotification(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, notification_type=None, time_stamp=None, ecgi=None, associate_id=None, erab_id=None, erab_qos_parameters=None, temp_ue_id=None, links=None, subscription=None):  # noqa: E501
        """RabEstNotification - a model defined in OpenAPI

        :param notification_type: The notification_type of this RabEstNotification.  # noqa: E501
        :type notification_type: str
        :param time_stamp: The time_stamp of this RabEstNotification.  # noqa: E501
        :type time_stamp: TimeStamp
        :param ecgi: The ecgi of this RabEstNotification.  # noqa: E501
        :type ecgi: Ecgi
        :param associate_id: The associate_id of this RabEstNotification.  # noqa: E501
        :type associate_id: List[AssociateId]
        :param erab_id: The erab_id of this RabEstNotification.  # noqa: E501
        :type erab_id: int
        :param erab_qos_parameters: The erab_qos_parameters of this RabEstNotification.  # noqa: E501
        :type erab_qos_parameters: ErabQosParameters1
        :param temp_ue_id: The temp_ue_id of this RabEstNotification.  # noqa: E501
        :type temp_ue_id: TempUeId1
        :param links: The links of this RabEstNotification.  # noqa: E501
        :type links: List[Links]
        :param subscription: The subscription of this RabEstNotification.  # noqa: E501
        :type subscription: List[LinkType]
        """
        self.openapi_types = {
            'notification_type': str,
            'time_stamp': TimeStamp,
            'ecgi': Ecgi,
            'associate_id': List[AssociateId],
            'erab_id': int,
            'erab_qos_parameters': ErabQosParameters1,
            'temp_ue_id': TempUeId1,
            'links': List[Links],
            'subscription': List[LinkType]
        }

        self.attribute_map = {
            'notification_type': 'notificationType',
            'time_stamp': 'timeStamp',
            'ecgi': 'ecgi',
            'associate_id': 'associateId',
            'erab_id': 'erabId',
            'erab_qos_parameters': 'erabQosParameters',
            'temp_ue_id': 'tempUeId',
            'links': '_links',
            'subscription': 'subscription'
        }

        self._notification_type = notification_type
        self._time_stamp = time_stamp
        self._ecgi = ecgi
        self._associate_id = associate_id
        self._erab_id = erab_id
        self._erab_qos_parameters = erab_qos_parameters
        self._temp_ue_id = temp_ue_id
        self._links = links
        self._subscription = subscription

    @classmethod
    def from_dict(cls, dikt) -> 'RabEstNotification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RabEstNotification of this RabEstNotification.  # noqa: E501
        :rtype: RabEstNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_type(self) -> str:
        """Gets the notification_type of this RabEstNotification.

        Shall be set to \"RabEstNotification\".  # noqa: E501

        :return: The notification_type of this RabEstNotification.
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type: str):
        """Sets the notification_type of this RabEstNotification.

        Shall be set to \"RabEstNotification\".  # noqa: E501

        :param notification_type: The notification_type of this RabEstNotification.
        :type notification_type: str
        """
        if notification_type is None:
            raise ValueError("Invalid value for `notification_type`, must not be `None`")  # noqa: E501

        self._notification_type = notification_type

    @property
    def time_stamp(self) -> TimeStamp:
        """Gets the time_stamp of this RabEstNotification.

        Time stamp.  # noqa: E501

        :return: The time_stamp of this RabEstNotification.
        :rtype: TimeStamp
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: TimeStamp):
        """Sets the time_stamp of this RabEstNotification.

        Time stamp.  # noqa: E501

        :param time_stamp: The time_stamp of this RabEstNotification.
        :type time_stamp: TimeStamp
        """

        self._time_stamp = time_stamp

    @property
    def ecgi(self) -> Ecgi:
        """Gets the ecgi of this RabEstNotification.

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :return: The ecgi of this RabEstNotification.
        :rtype: Ecgi
        """
        return self._ecgi

    @ecgi.setter
    def ecgi(self, ecgi: Ecgi):
        """Sets the ecgi of this RabEstNotification.

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :param ecgi: The ecgi of this RabEstNotification.
        :type ecgi: Ecgi
        """
        if ecgi is None:
            raise ValueError("Invalid value for `ecgi`, must not be `None`")  # noqa: E501

        self._ecgi = ecgi

    @property
    def associate_id(self) -> List[AssociateId]:
        """Gets the associate_id of this RabEstNotification.

        0 to N identifiers to bind the event for a specific UE or flow.   # noqa: E501

        :return: The associate_id of this RabEstNotification.
        :rtype: List[AssociateId]
        """
        return self._associate_id

    @associate_id.setter
    def associate_id(self, associate_id: List[AssociateId]):
        """Sets the associate_id of this RabEstNotification.

        0 to N identifiers to bind the event for a specific UE or flow.   # noqa: E501

        :param associate_id: The associate_id of this RabEstNotification.
        :type associate_id: List[AssociateId]
        """
        if associate_id is not None and len(associate_id) < 0:
            raise ValueError("Invalid value for `associate_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._associate_id = associate_id

    @property
    def erab_id(self) -> int:
        """Gets the erab_id of this RabEstNotification.

        The attribute that uniquely identifies a Radio Access bearer for specific UE as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :return: The erab_id of this RabEstNotification.
        :rtype: int
        """
        return self._erab_id

    @erab_id.setter
    def erab_id(self, erab_id: int):
        """Sets the erab_id of this RabEstNotification.

        The attribute that uniquely identifies a Radio Access bearer for specific UE as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :param erab_id: The erab_id of this RabEstNotification.
        :type erab_id: int
        """
        if erab_id is None:
            raise ValueError("Invalid value for `erab_id`, must not be `None`")  # noqa: E501

        self._erab_id = erab_id

    @property
    def erab_qos_parameters(self) -> ErabQosParameters1:
        """Gets the erab_qos_parameters of this RabEstNotification.


        :return: The erab_qos_parameters of this RabEstNotification.
        :rtype: ErabQosParameters1
        """
        return self._erab_qos_parameters

    @erab_qos_parameters.setter
    def erab_qos_parameters(self, erab_qos_parameters: ErabQosParameters1):
        """Sets the erab_qos_parameters of this RabEstNotification.


        :param erab_qos_parameters: The erab_qos_parameters of this RabEstNotification.
        :type erab_qos_parameters: ErabQosParameters1
        """

        self._erab_qos_parameters = erab_qos_parameters

    @property
    def temp_ue_id(self) -> TempUeId1:
        """Gets the temp_ue_id of this RabEstNotification.


        :return: The temp_ue_id of this RabEstNotification.
        :rtype: TempUeId1
        """
        return self._temp_ue_id

    @temp_ue_id.setter
    def temp_ue_id(self, temp_ue_id: TempUeId1):
        """Sets the temp_ue_id of this RabEstNotification.


        :param temp_ue_id: The temp_ue_id of this RabEstNotification.
        :type temp_ue_id: TempUeId1
        """

        self._temp_ue_id = temp_ue_id

    @property
    def links(self) -> List[Links]:
        """Gets the links of this RabEstNotification.

        Links to resources related to this notification.  # noqa: E501

        :return: The links of this RabEstNotification.
        :rtype: List[Links]
        """
        return self._links

    @links.setter
    def links(self, links: List[Links]):
        """Sets the links of this RabEstNotification.

        Links to resources related to this notification.  # noqa: E501

        :param links: The links of this RabEstNotification.
        :type links: List[Links]
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def subscription(self) -> List[LinkType]:
        """Gets the subscription of this RabEstNotification.

        A link to the related subscription.  # noqa: E501

        :return: The subscription of this RabEstNotification.
        :rtype: List[LinkType]
        """
        return self._subscription

    @subscription.setter
    def subscription(self, subscription: List[LinkType]):
        """Sets the subscription of this RabEstNotification.

        A link to the related subscription.  # noqa: E501

        :param subscription: The subscription of this RabEstNotification.
        :type subscription: List[LinkType]
        """
        if subscription is None:
            raise ValueError("Invalid value for `subscription`, must not be `None`")  # noqa: E501

        self._subscription = subscription
