from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.enb_info import EnbInfo
from openapi_server.models.sgw_info import SGwInfo
from openapi_server import util

from openapi_server.models.enb_info import EnbInfo  # noqa: E501
from openapi_server.models.sgw_info import SGwInfo  # noqa: E501

class S1BearerInfoDetailed(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, erab_id=None, enb_info=None, s_gw_info=None):  # noqa: E501
        """S1BearerInfoDetailed - a model defined in OpenAPI

        :param erab_id: The erab_id of this S1BearerInfoDetailed.  # noqa: E501
        :type erab_id: int
        :param enb_info: The enb_info of this S1BearerInfoDetailed.  # noqa: E501
        :type enb_info: EnbInfo
        :param s_gw_info: The s_gw_info of this S1BearerInfoDetailed.  # noqa: E501
        :type s_gw_info: SGwInfo
        """
        self.openapi_types = {
            'erab_id': int,
            'enb_info': EnbInfo,
            's_gw_info': SGwInfo
        }

        self.attribute_map = {
            'erab_id': 'erabId',
            'enb_info': 'enbInfo',
            's_gw_info': 'sGwInfo'
        }

        self._erab_id = erab_id
        self._enb_info = enb_info
        self._s_gw_info = s_gw_info

    @classmethod
    def from_dict(cls, dikt) -> 'S1BearerInfoDetailed':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The S1BearerInfoDetailed of this S1BearerInfoDetailed.  # noqa: E501
        :rtype: S1BearerInfoDetailed
        """
        return util.deserialize_model(dikt, cls)

    @property
    def erab_id(self) -> int:
        """Gets the erab_id of this S1BearerInfoDetailed.

        The attribute that uniquely identifies a S1 bearer for a specific UE, as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :return: The erab_id of this S1BearerInfoDetailed.
        :rtype: int
        """
        return self._erab_id

    @erab_id.setter
    def erab_id(self, erab_id: int):
        """Sets the erab_id of this S1BearerInfoDetailed.

        The attribute that uniquely identifies a S1 bearer for a specific UE, as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :param erab_id: The erab_id of this S1BearerInfoDetailed.
        :type erab_id: int
        """
        if erab_id is None:
            raise ValueError("Invalid value for `erab_id`, must not be `None`")  # noqa: E501

        self._erab_id = erab_id

    @property
    def enb_info(self) -> EnbInfo:
        """Gets the enb_info of this S1BearerInfoDetailed.


        :return: The enb_info of this S1BearerInfoDetailed.
        :rtype: EnbInfo
        """
        return self._enb_info

    @enb_info.setter
    def enb_info(self, enb_info: EnbInfo):
        """Sets the enb_info of this S1BearerInfoDetailed.


        :param enb_info: The enb_info of this S1BearerInfoDetailed.
        :type enb_info: EnbInfo
        """
        if enb_info is None:
            raise ValueError("Invalid value for `enb_info`, must not be `None`")  # noqa: E501

        self._enb_info = enb_info

    @property
    def s_gw_info(self) -> SGwInfo:
        """Gets the s_gw_info of this S1BearerInfoDetailed.


        :return: The s_gw_info of this S1BearerInfoDetailed.
        :rtype: SGwInfo
        """
        return self._s_gw_info

    @s_gw_info.setter
    def s_gw_info(self, s_gw_info: SGwInfo):
        """Sets the s_gw_info of this S1BearerInfoDetailed.


        :param s_gw_info: The s_gw_info of this S1BearerInfoDetailed.
        :type s_gw_info: SGwInfo
        """
        if s_gw_info is None:
            raise ValueError("Invalid value for `s_gw_info`, must not be `None`")  # noqa: E501

        self._s_gw_info = s_gw_info
