from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.link_type import LinkType
from openapi_server.models.links import Links
from openapi_server.models.s1_ue_info1 import S1UeInfo1
from openapi_server.models.time_stamp import TimeStamp
from openapi_server import util

from openapi_server.models.link_type import LinkType  # noqa: E501
from openapi_server.models.links import Links  # noqa: E501
from openapi_server.models.s1_ue_info1 import S1UeInfo1  # noqa: E501
from openapi_server.models.time_stamp import TimeStamp  # noqa: E501

class S1BearerNotification(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, notification_type=None, time_stamp=None, s1_event=None, s1_ue_info=None, links=None, subscription=None):  # noqa: E501
        """S1BearerNotification - a model defined in OpenAPI

        :param notification_type: The notification_type of this S1BearerNotification.  # noqa: E501
        :type notification_type: str
        :param time_stamp: The time_stamp of this S1BearerNotification.  # noqa: E501
        :type time_stamp: TimeStamp
        :param s1_event: The s1_event of this S1BearerNotification.  # noqa: E501
        :type s1_event: str
        :param s1_ue_info: The s1_ue_info of this S1BearerNotification.  # noqa: E501
        :type s1_ue_info: S1UeInfo1
        :param links: The links of this S1BearerNotification.  # noqa: E501
        :type links: List[Links]
        :param subscription: The subscription of this S1BearerNotification.  # noqa: E501
        :type subscription: List[LinkType]
        """
        self.openapi_types = {
            'notification_type': str,
            'time_stamp': TimeStamp,
            's1_event': str,
            's1_ue_info': S1UeInfo1,
            'links': List[Links],
            'subscription': List[LinkType]
        }

        self.attribute_map = {
            'notification_type': 'notificationType',
            'time_stamp': 'timeStamp',
            's1_event': 's1Event',
            's1_ue_info': 's1UeInfo',
            'links': '_links',
            'subscription': 'subscription'
        }

        self._notification_type = notification_type
        self._time_stamp = time_stamp
        self._s1_event = s1_event
        self._s1_ue_info = s1_ue_info
        self._links = links
        self._subscription = subscription

    @classmethod
    def from_dict(cls, dikt) -> 'S1BearerNotification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The S1BearerNotification of this S1BearerNotification.  # noqa: E501
        :rtype: S1BearerNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_type(self) -> str:
        """Gets the notification_type of this S1BearerNotification.

        Shall be set to \"S1BearerNotification\".  # noqa: E501

        :return: The notification_type of this S1BearerNotification.
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type: str):
        """Sets the notification_type of this S1BearerNotification.

        Shall be set to \"S1BearerNotification\".  # noqa: E501

        :param notification_type: The notification_type of this S1BearerNotification.
        :type notification_type: str
        """
        if notification_type is None:
            raise ValueError("Invalid value for `notification_type`, must not be `None`")  # noqa: E501

        self._notification_type = notification_type

    @property
    def time_stamp(self) -> TimeStamp:
        """Gets the time_stamp of this S1BearerNotification.

        Time stamp.  # noqa: E501

        :return: The time_stamp of this S1BearerNotification.
        :rtype: TimeStamp
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: TimeStamp):
        """Sets the time_stamp of this S1BearerNotification.

        Time stamp.  # noqa: E501

        :param time_stamp: The time_stamp of this S1BearerNotification.
        :type time_stamp: TimeStamp
        """

        self._time_stamp = time_stamp

    @property
    def s1_event(self) -> str:
        """Gets the s1_event of this S1BearerNotification.

        The subscribed event that triggered this notification in S1BearerSubscription.  # noqa: E501

        :return: The s1_event of this S1BearerNotification.
        :rtype: str
        """
        return self._s1_event

    @s1_event.setter
    def s1_event(self, s1_event: str):
        """Sets the s1_event of this S1BearerNotification.

        The subscribed event that triggered this notification in S1BearerSubscription.  # noqa: E501

        :param s1_event: The s1_event of this S1BearerNotification.
        :type s1_event: str
        """
        allowed_values = ["SEE_DESCRIPTION"]  # noqa: E501
        if s1_event not in allowed_values:
            raise ValueError(
                "Invalid value for `s1_event` ({0}), must be one of {1}"
                .format(s1_event, allowed_values)
            )

        self._s1_event = s1_event

    @property
    def s1_ue_info(self) -> S1UeInfo1:
        """Gets the s1_ue_info of this S1BearerNotification.


        :return: The s1_ue_info of this S1BearerNotification.
        :rtype: S1UeInfo1
        """
        return self._s1_ue_info

    @s1_ue_info.setter
    def s1_ue_info(self, s1_ue_info: S1UeInfo1):
        """Sets the s1_ue_info of this S1BearerNotification.


        :param s1_ue_info: The s1_ue_info of this S1BearerNotification.
        :type s1_ue_info: S1UeInfo1
        """
        if s1_ue_info is None:
            raise ValueError("Invalid value for `s1_ue_info`, must not be `None`")  # noqa: E501

        self._s1_ue_info = s1_ue_info

    @property
    def links(self) -> List[Links]:
        """Gets the links of this S1BearerNotification.

        Links to resources related to this notification.  # noqa: E501

        :return: The links of this S1BearerNotification.
        :rtype: List[Links]
        """
        return self._links

    @links.setter
    def links(self, links: List[Links]):
        """Sets the links of this S1BearerNotification.

        Links to resources related to this notification.  # noqa: E501

        :param links: The links of this S1BearerNotification.
        :type links: List[Links]
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def subscription(self) -> List[LinkType]:
        """Gets the subscription of this S1BearerNotification.

        A link to the related subscription.  # noqa: E501

        :return: The subscription of this S1BearerNotification.
        :rtype: List[LinkType]
        """
        return self._subscription

    @subscription.setter
    def subscription(self, subscription: List[LinkType]):
        """Sets the subscription of this S1BearerNotification.

        A link to the related subscription.  # noqa: E501

        :param subscription: The subscription of this S1BearerNotification.
        :type subscription: List[LinkType]
        """
        if subscription is None:
            raise ValueError("Invalid value for `subscription`, must not be `None`")  # noqa: E501

        self._subscription = subscription
