from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.associate_id import AssociateId
from openapi_server.models.ecgi import Ecgi
from openapi_server.models.s1_bearer_info import S1BearerInfo
from openapi_server.models.temp_ue_id import TempUeId
from openapi_server import util

from openapi_server.models.associate_id import AssociateId  # noqa: E501
from openapi_server.models.ecgi import Ecgi  # noqa: E501
from openapi_server.models.s1_bearer_info import S1BearerInfo  # noqa: E501
from openapi_server.models.temp_ue_id import TempUeId  # noqa: E501

class S1UeInfo1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, temp_ue_id=None, associate_id=None, ecgi=None, s1_bearer_info=None):  # noqa: E501
        """S1UeInfo1 - a model defined in OpenAPI

        :param temp_ue_id: The temp_ue_id of this S1UeInfo1.  # noqa: E501
        :type temp_ue_id: TempUeId
        :param associate_id: The associate_id of this S1UeInfo1.  # noqa: E501
        :type associate_id: List[AssociateId]
        :param ecgi: The ecgi of this S1UeInfo1.  # noqa: E501
        :type ecgi: List[Ecgi]
        :param s1_bearer_info: The s1_bearer_info of this S1UeInfo1.  # noqa: E501
        :type s1_bearer_info: List[S1BearerInfo]
        """
        self.openapi_types = {
            'temp_ue_id': TempUeId,
            'associate_id': List[AssociateId],
            'ecgi': List[Ecgi],
            's1_bearer_info': List[S1BearerInfo]
        }

        self.attribute_map = {
            'temp_ue_id': 'tempUeId',
            'associate_id': 'associateId',
            'ecgi': 'ecgi',
            's1_bearer_info': 's1BearerInfo'
        }

        self._temp_ue_id = temp_ue_id
        self._associate_id = associate_id
        self._ecgi = ecgi
        self._s1_bearer_info = s1_bearer_info

    @classmethod
    def from_dict(cls, dikt) -> 'S1UeInfo1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The S1UeInfo1 of this S1UeInfo1.  # noqa: E501
        :rtype: S1UeInfo1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def temp_ue_id(self) -> TempUeId:
        """Gets the temp_ue_id of this S1UeInfo1.


        :return: The temp_ue_id of this S1UeInfo1.
        :rtype: TempUeId
        """
        return self._temp_ue_id

    @temp_ue_id.setter
    def temp_ue_id(self, temp_ue_id: TempUeId):
        """Sets the temp_ue_id of this S1UeInfo1.


        :param temp_ue_id: The temp_ue_id of this S1UeInfo1.
        :type temp_ue_id: TempUeId
        """

        self._temp_ue_id = temp_ue_id

    @property
    def associate_id(self) -> List[AssociateId]:
        """Gets the associate_id of this S1UeInfo1.

        0 to N identifiers to associate the information for a specific UE or flow.  # noqa: E501

        :return: The associate_id of this S1UeInfo1.
        :rtype: List[AssociateId]
        """
        return self._associate_id

    @associate_id.setter
    def associate_id(self, associate_id: List[AssociateId]):
        """Sets the associate_id of this S1UeInfo1.

        0 to N identifiers to associate the information for a specific UE or flow.  # noqa: E501

        :param associate_id: The associate_id of this S1UeInfo1.
        :type associate_id: List[AssociateId]
        """
        if associate_id is not None and len(associate_id) < 0:
            raise ValueError("Invalid value for `associate_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._associate_id = associate_id

    @property
    def ecgi(self) -> List[Ecgi]:
        """Gets the ecgi of this S1UeInfo1.

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :return: The ecgi of this S1UeInfo1.
        :rtype: List[Ecgi]
        """
        return self._ecgi

    @ecgi.setter
    def ecgi(self, ecgi: List[Ecgi]):
        """Sets the ecgi of this S1UeInfo1.

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :param ecgi: The ecgi of this S1UeInfo1.
        :type ecgi: List[Ecgi]
        """
        if ecgi is None:
            raise ValueError("Invalid value for `ecgi`, must not be `None`")  # noqa: E501
        if ecgi is not None and len(ecgi) < 1:
            raise ValueError("Invalid value for `ecgi`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._ecgi = ecgi

    @property
    def s1_bearer_info(self) -> List[S1BearerInfo]:
        """Gets the s1_bearer_info of this S1UeInfo1.


        :return: The s1_bearer_info of this S1UeInfo1.
        :rtype: List[S1BearerInfo]
        """
        return self._s1_bearer_info

    @s1_bearer_info.setter
    def s1_bearer_info(self, s1_bearer_info: List[S1BearerInfo]):
        """Sets the s1_bearer_info of this S1UeInfo1.


        :param s1_bearer_info: The s1_bearer_info of this S1UeInfo1.
        :type s1_bearer_info: List[S1BearerInfo]
        """
        if s1_bearer_info is None:
            raise ValueError("Invalid value for `s1_bearer_info`, must not be `None`")  # noqa: E501

        self._s1_bearer_info = s1_bearer_info
