from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Trigger(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NUMBER_0 = 0
    NUMBER_1 = 1
    NUMBER_2 = 2
    NUMBER_3 = 3
    NUMBER_4 = 4
    NUMBER_5 = 5
    NUMBER_10 = 10
    NUMBER_11 = 11
    NUMBER_12 = 12
    NUMBER_13 = 13
    NUMBER_14 = 14
    NUMBER_15 = 15
    NUMBER_20 = 20
    NUMBER_21 = 21
    NUMBER_30 = 30
    NUMBER_31 = 31
    NUMBER_40 = 40
    NUMBER_41 = 41
    NUMBER_42 = 42
    NUMBER_50 = 50
    NUMBER_51 = 51
    NUMBER_60 = 60
    NUMBER_61 = 61
    def __init__(self):  # noqa: E501
        """Trigger - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Trigger':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Trigger of this Trigger.  # noqa: E501
        :rtype: Trigger
        """
        return util.deserialize_model(dikt, cls)
