from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.associate_id import AssociateId
from openapi_server.models.erab_info import ErabInfo
from openapi_server import util

from openapi_server.models.associate_id import AssociateId  # noqa: E501
from openapi_server.models.erab_info import ErabInfo  # noqa: E501

class UeInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, associate_id=None, erab_info=None):  # noqa: E501
        """UeInfo - a model defined in OpenAPI

        :param associate_id: The associate_id of this UeInfo.  # noqa: E501
        :type associate_id: List[AssociateId]
        :param erab_info: The erab_info of this UeInfo.  # noqa: E501
        :type erab_info: List[ErabInfo]
        """
        self.openapi_types = {
            'associate_id': List[AssociateId],
            'erab_info': List[ErabInfo]
        }

        self.attribute_map = {
            'associate_id': 'associateId',
            'erab_info': 'erabInfo'
        }

        self._associate_id = associate_id
        self._erab_info = erab_info

    @classmethod
    def from_dict(cls, dikt) -> 'UeInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UeInfo of this UeInfo.  # noqa: E501
        :rtype: UeInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def associate_id(self) -> List[AssociateId]:
        """Gets the associate_id of this UeInfo.

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :return: The associate_id of this UeInfo.
        :rtype: List[AssociateId]
        """
        return self._associate_id

    @associate_id.setter
    def associate_id(self, associate_id: List[AssociateId]):
        """Sets the associate_id of this UeInfo.

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :param associate_id: The associate_id of this UeInfo.
        :type associate_id: List[AssociateId]
        """
        if associate_id is not None and len(associate_id) < 0:
            raise ValueError("Invalid value for `associate_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._associate_id = associate_id

    @property
    def erab_info(self) -> List[ErabInfo]:
        """Gets the erab_info of this UeInfo.


        :return: The erab_info of this UeInfo.
        :rtype: List[ErabInfo]
        """
        return self._erab_info

    @erab_info.setter
    def erab_info(self, erab_info: List[ErabInfo]):
        """Sets the erab_info of this UeInfo.


        :param erab_info: The erab_info of this UeInfo.
        :type erab_info: List[ErabInfo]
        """
        if erab_info is None:
            raise ValueError("Invalid value for `erab_info`, must not be `None`")  # noqa: E501

        self._erab_info = erab_info
