# Data connection definition is done through sequential blocks like the following:
#
# name:<connection name>
# type:4|6|8
# apn:<apn>
# profile:<profile index>
# default-gateway:Y|N
# dns:Y|N
#
# Note the following:
#
# - apn/type and profile are mutually exclusive
# - Without qmap only a single data connection definition can be setup
# - When type is 8 ip-type is unspecified and will be given by the modem
# - If default gateway is Y, the tool will set the default route with the gateway available for the chosen data connection: only a single default-gateway for ip-type is allowed. When ip-type is unspecified, the tool will set the one available
# - If dns is set dns addresses will be added for the specific network interface
#
# ATTENTION!!!
#
# When the default-gateway flag is set, the tool will override the default gateway set in the host: the original default route WON'T be restored at the end of the process. Take care if you are using the tool in a remote system.
#
# Example of a IPV4 only data connection not setting default gateway, setting dns
#
# name:vodafone
# type:4
# apn:mobile.vodafone.it
# default-gateway:N
# dns:Y
#
# Example of a IPV4V6 data connection setting default gateway, not setting dns
# name:vodafone
# type:0
# apn:mobile.vodafone.it
# default-gateway:N
# dns:N
#
# Example of a IPV4 and IPV6 data connection using the same APN
#
# name:vodafone_ipv4
# type:4
# apn:mobile.vodafone.it
# default-gateway:Y
# dns:Y
# name:vodafone_ipv6
# type:6
# apn:mobile.vodafone.it
# default-gateway:Y
# dns:Y
#
# Example of two IPV4 data connections using different APN
#
name:vodafone_ipv4
apn:internet
type:4
default-gateway:N
dns:Y
#apn: internet
#default-gateway: N
#dns: Y
# name:vodafone_ipv6
# type:4
# apn:web.omnitel.it
# default-gateway:N
# dns:Y
#
# Example of an IPV4 data connection using profile 2
#
# name:vodafone_ipv4
# profile: 2
# default-gateway:N
# dns:Y
